[package]
name = "hew-pkg"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "The Hew package manager"
readme = "README.md"
repository = "https://github.com/hew-lang/hew"
keywords = ["hew", "package-manager"]
categories = ["command-line-utilities"]

[dependencies]
clap.workspace = true
semver = "1"
toml.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
ed25519-dalek = { version = "2", features = ["rand_core"] }
rand = "0.10.1"
rand_core = "0.10.1"
base64.workspace = true
fd-lock.workspace = true
libc.workspace = true
tar = "0.4"
zstd = "0.13"
ureq = { version = "3", features = ["json"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = [
  "Win32_Foundation",
  "Win32_Storage_FileSystem",
] }

[dev-dependencies]
tempfile.workspace = true
tiny_http = "0.12"
serde_json.workspace = true

[lints]
workspace = true
