//! Shared types for the `hew-export-macro` proc macro.
//!
//! This crate is kept separate from `hew-export-macro` because Rust
//! `proc-macro` crates cannot export ordinary public types.

/// Metadata describing a single Hew stdlib function exported from the runtime.
///
/// Instances are produced by the `__hew_export_meta_*` companion functions
/// generated by `#[hew_export]`.  A build-time tool (or `build.rs`) can
/// collect all such functions, gather their [`ExportMeta`] values, and
/// auto-generate `stdlib.rs` type-checker entries and `.hew` stub files.
#[derive(Debug)]
pub struct ExportMeta {
    /// Hew module path, e.g. `"std::encoding::json"`.
    pub module: &'static str,
    /// Hew-level function name, e.g. `"parse"`.
    pub hew_name: &'static str,
    /// The C symbol name, e.g. `"hew_json_parse"`.
    pub c_name: &'static str,
    /// Parameter list as `(hew_param_name, hew_type)` pairs.
    pub params: Vec<(&'static str, &'static str)>,
    /// Hew return type, or `None` for void.
    pub return_type: Option<&'static str>,
    /// Optional documentation string.
    pub doc: &'static str,
}
