//! Hew runtime: `sign` module.
//!
//! Provides Ed25519 key-pair generation, signing, and verification for
//! compiled Hew programs.  All key and signature material is carried as
//! raw byte buffers; there are no opaque handle types.
//!
//! ## Size constants (Ed25519 / ring 0.17)
//!
//! | Constant              | Bytes | Source                                      |
//! |-----------------------|-------|---------------------------------------------|
//! | `ED25519_PKCS8_LEN`   |   83  | `ring` PKCS#8 v2 document (private + public)|
//! | `ED25519_PUBLIC_LEN`  |   32  | raw 32-byte Curve25519 public point         |
//! | `ED25519_SIG_LEN`     |   64  | raw 64-byte signature (r ‖ s)               |
//!
//! ## Ownership / ABI contract (for the reviewer)
//!
//! Every `_hew`-suffixed function follows the same ownership contract as the
//! sibling `std/crypto/crypto` module:
//!
//! - **Input** `*mut HewVec` pointers are borrowed for the duration of the
//!   call.  Ownership stays with the Hew caller; the callee does NOT free them.
//!   `hwvec_to_u8` / `try_hwvec_to_u8` **copies** the payload bytes into a
//!   fresh `Vec<u8>` — it does not consume or free the `HewVec` header.
//! - **Output** `*mut HewVec` pointers are fresh allocations from
//!   `u8_to_hwvec`, which copies the Rust-side bytes into a new runtime-owned
//!   `HewVec`.  The Hew runtime's standard vec-drop path (`hew_vec_dealloc`)
//!   is the only correct way to release them.  No bespoke free entrypoint is
//!   introduced.
//! - The caller must never free an input `HewVec` before it is out of scope,
//!   nor alias an output `HewVec` pointer after passing it back to the runtime.
//! - `hew_ed25519_verify_hew` returns `i32` (0/1), not a `*mut HewVec`.
//!   Its ABI mirrors `hew_constant_time_eq_hew` in the crypto module.
//! - The raw C-ABI variants (`hew_ed25519_*` without `_hew` suffix) are
//!   provided for direct use from other native Rust code or future FFI callers;
//!   they do not touch `HewVec` at all.
//!
//! ## Hew surface mapping
//!
//! The Hew `keypair()` function calls two `_hew` functions in sequence:
//!
//! 1. `hew_ed25519_generate_pkcs8_hew()` → `bytes` (83-byte PKCS#8 document)
//! 2. `hew_ed25519_public_key_from_pkcs8_hew(pkcs8)` → `bytes` (32-byte public key)
//!
//! This keeps each FFI call to the `fn(args) -> bytes` shape already used by
//! `hew_sha256_hew` and friends — no novel calling convention is introduced.
//!
//! ## Fail-closed policy
//!
//! - The raw C-ABI variants (`hew_ed25519_*` without `_hew` suffix) treat
//!   null pointers and zero-length inputs as invalid and return `0`/empty
//!   sentinel rather than causing UB.
//! - The `_hew` `HewVec` wrappers use `try_hwvec_to_u8` to validate each
//!   `*mut HewVec` input (null check + shape check) **before** touching its
//!   contents.  On null or malformed `HewVec`:
//!   - `hew_ed25519_verify_hew` returns `0` (fail-closed sentinel).
//!   - `hew_ed25519_sign_hew` and `hew_ed25519_public_key_from_pkcs8_hew`
//!     call `hew_panic_msg` (controlled trap, same pattern as
//!     `hew_encrypt_seal_hew`) — the caller's contract is to pass valid
//!     `bytes` `HewVec` pointers.
//! - `hew_ed25519_sign_hew` also calls `hew_panic_msg` when the private key
//!   bytes are not a valid 83-byte PKCS#8 document.
//! - Secret-key bytes are never written to error messages or logs.

// Force-link hew-runtime so the linker can resolve hew_vec_* symbols
// referenced by hew-cabi's object code.
#[cfg(test)]
extern crate hew_runtime;

use ring::{
    rand::SystemRandom,
    signature::{Ed25519KeyPair, KeyPair, UnparsedPublicKey, ED25519},
};

/// Length (bytes) of an Ed25519 PKCS#8 v2 document as generated by ring 0.17.
///
/// Ring uses a PKCS#8 v2 template (`ed25519_pkcs8_v2_template.der`, 19 bytes)
/// plus the 32-byte private scalar plus the 32-byte public point = 83 bytes.
/// This constant is asserted at runtime in debug builds; if ring's encoding
/// changes a `debug_assert!` in `hew_ed25519_generate_pkcs8` will catch it.
pub const ED25519_PKCS8_LEN: usize = 83;

/// Length (bytes) of a raw Ed25519 public key.
pub const ED25519_PUBLIC_LEN: usize = 32;

/// Length (bytes) of an Ed25519 signature.
pub const ED25519_SIG_LEN: usize = 64;

// ---------------------------------------------------------------------------
// Raw C-ABI layer (no HewVec; usable from native callers)
// ---------------------------------------------------------------------------

/// Generate an Ed25519 PKCS#8 v2 document and write the 83 bytes to `out`.
///
/// Returns `1` on success, `0` if the RNG failed or `out` is null.
///
/// # Safety
///
/// `out` must be valid for writing `ED25519_PKCS8_LEN` (83) bytes.
#[no_mangle]
pub unsafe extern "C" fn hew_ed25519_generate_pkcs8(out: *mut u8) -> i32 {
    if out.is_null() {
        return 0;
    }
    let rng = SystemRandom::new();
    let Ok(pkcs8_doc) = Ed25519KeyPair::generate_pkcs8(&rng) else {
        return 0;
    };
    let bytes = pkcs8_doc.as_ref();
    debug_assert_eq!(
        bytes.len(),
        ED25519_PKCS8_LEN,
        "ring Ed25519 PKCS#8 document length changed"
    );
    // SAFETY: out is valid for ED25519_PKCS8_LEN bytes per caller contract.
    unsafe { std::ptr::copy_nonoverlapping(bytes.as_ptr(), out, bytes.len()) };
    1
}

/// Extract the 32-byte public key from an Ed25519 PKCS#8 document.
///
/// Returns `1` on success, `0` if either pointer is null or the key is invalid.
///
/// # Safety
///
/// - `pkcs8` must be valid for reading `pkcs8_len` bytes.
/// - `out` must be valid for writing `ED25519_PUBLIC_LEN` (32) bytes.
#[no_mangle]
pub unsafe extern "C" fn hew_ed25519_public_key_from_pkcs8(
    pkcs8: *const u8,
    pkcs8_len: usize,
    out: *mut u8,
) -> i32 {
    if pkcs8.is_null() || out.is_null() {
        return 0;
    }
    // SAFETY: pkcs8 is valid for pkcs8_len bytes per caller contract.
    let key_bytes = unsafe { std::slice::from_raw_parts(pkcs8, pkcs8_len) };
    let Ok(key_pair) = Ed25519KeyPair::from_pkcs8(key_bytes) else {
        return 0;
    };
    let pub_bytes = key_pair.public_key().as_ref();
    debug_assert_eq!(pub_bytes.len(), ED25519_PUBLIC_LEN);
    // SAFETY: out is valid for ED25519_PUBLIC_LEN bytes per caller contract.
    unsafe { std::ptr::copy_nonoverlapping(pub_bytes.as_ptr(), out, pub_bytes.len()) };
    1
}

/// Sign `msg` (`msg_len` bytes) with the PKCS#8 private key (`key`, `key_len`
/// bytes) and write the 64-byte signature into `sig_out`.
///
/// Returns `1` on success, `0` if any input is null/invalid.
///
/// # Safety
///
/// - `key` must be valid for reading `key_len` bytes.
/// - `msg` must be valid for reading `msg_len` bytes (may be null when
///   `msg_len == 0`).
/// - `sig_out` must be valid for writing `ED25519_SIG_LEN` (64) bytes.
#[no_mangle]
pub unsafe extern "C" fn hew_ed25519_sign(
    key: *const u8,
    key_len: usize,
    msg: *const u8,
    msg_len: usize,
    sig_out: *mut u8,
) -> i32 {
    if key.is_null() || sig_out.is_null() {
        return 0;
    }
    // SAFETY: key is valid for key_len bytes per caller contract.
    let key_bytes = unsafe { std::slice::from_raw_parts(key, key_len) };
    // SAFETY: msg is valid for msg_len bytes, or empty when msg_len == 0.
    let msg_bytes: &[u8] = if msg.is_null() || msg_len == 0 {
        &[]
    } else {
        // SAFETY: msg is non-null and valid for msg_len bytes.
        unsafe { std::slice::from_raw_parts(msg, msg_len) }
    };

    // Invalid key: fail closed.  Do NOT write anything to sig_out.
    let Ok(key_pair) = Ed25519KeyPair::from_pkcs8(key_bytes) else {
        return 0;
    };

    let sig = key_pair.sign(msg_bytes);
    let sig_bytes = sig.as_ref();
    debug_assert_eq!(sig_bytes.len(), ED25519_SIG_LEN);
    // SAFETY: sig_out is valid for ED25519_SIG_LEN bytes per caller contract.
    unsafe { std::ptr::copy_nonoverlapping(sig_bytes.as_ptr(), sig_out, sig_bytes.len()) };
    1
}

/// Verify that `sig` (`sig_len` bytes) is a valid Ed25519 signature over `msg`
/// (`msg_len` bytes) under `public_key` (`key_len` bytes).
///
/// Returns `1` if valid, `0` otherwise (including any parse or length error).
///
/// # Safety
///
/// - `public_key` must be valid for reading `key_len` bytes.
/// - `msg` must be valid for reading `msg_len` bytes (may be null when
///   `msg_len == 0`).
/// - `sig` must be valid for reading `sig_len` bytes.
#[no_mangle]
pub unsafe extern "C" fn hew_ed25519_verify(
    public_key: *const u8,
    key_len: usize,
    msg: *const u8,
    msg_len: usize,
    sig: *const u8,
    sig_len: usize,
) -> i32 {
    if public_key.is_null() || sig.is_null() {
        return 0;
    }
    // SAFETY: public_key is valid for key_len bytes per caller contract.
    let key_bytes = unsafe { std::slice::from_raw_parts(public_key, key_len) };
    // SAFETY: msg is valid for msg_len bytes, or empty when msg_len == 0.
    let msg_bytes: &[u8] = if msg.is_null() || msg_len == 0 {
        &[]
    } else {
        // SAFETY: msg is non-null and valid for msg_len bytes.
        unsafe { std::slice::from_raw_parts(msg, msg_len) }
    };
    // SAFETY: sig is valid for sig_len bytes per caller contract.
    let sig_bytes = unsafe { std::slice::from_raw_parts(sig, sig_len) };

    let unparsed = UnparsedPublicKey::new(&ED25519, key_bytes);
    match unparsed.verify(msg_bytes, sig_bytes) {
        Ok(()) => 1,
        Err(_) => 0,
    }
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/// Panic with a static NUL-terminated message via the Hew runtime.
///
/// Diverges: `hew_panic_msg` does not return.
fn panic_msg(message: &'static [u8]) -> ! {
    use std::ffi::c_char;
    // SAFETY: message is a valid static NUL-terminated string.
    unsafe { hew_runtime::actor::hew_panic_msg(message.as_ptr().cast::<c_char>()) };
    unreachable!("hew_panic_msg should not return")
}

// ---------------------------------------------------------------------------
// HewVec-ABI wrappers (called from std/crypto/sign/sign.hew)
// ---------------------------------------------------------------------------

/// Generate an Ed25519 PKCS#8 v2 document and return it as an 83-byte
/// `bytes` `HewVec`.
///
/// Calls `hew_panic_msg` on RNG failure (should not occur in practice).
///
/// # Safety
///
/// No inputs; all memory is managed by the runtime allocator.
#[no_mangle]
pub unsafe extern "C" fn hew_ed25519_generate_pkcs8_hew() -> *mut hew_cabi::vec::HewVec {
    let mut buf = [0u8; ED25519_PKCS8_LEN];
    // SAFETY: buf is a valid ED25519_PKCS8_LEN-byte writable buffer.
    let ok = unsafe { hew_ed25519_generate_pkcs8(buf.as_mut_ptr()) };
    if ok == 0 {
        panic_msg(b"sign.keypair failed: Ed25519 key generation error (RNG failure)\0");
    }
    // SAFETY: buf is a valid byte slice.
    unsafe { hew_cabi::vec::u8_to_hwvec(&buf) }
}

/// Extract the 32-byte public key from an Ed25519 PKCS#8 `bytes` `HewVec`
/// and return it as a new 32-byte `bytes` `HewVec`.
///
/// Calls `hew_panic_msg` if `pkcs8` is null, has the wrong `HewVec` shape, or
/// is not a valid 83-byte PKCS#8 document.
///
/// # Safety
///
/// `pkcs8` must be a valid, non-null pointer to a `bytes` `HewVec`.
#[no_mangle]
pub unsafe extern "C" fn hew_ed25519_public_key_from_pkcs8_hew(
    pkcs8: *mut hew_cabi::vec::HewVec,
) -> *mut hew_cabi::vec::HewVec {
    // Validate and copy bytes without panicking on null/malformed HewVec.
    // SAFETY: if pkcs8 is non-null the caller guarantees it points to a live HewVec.
    let Some(pkcs8_bytes) = (unsafe { hew_cabi::vec::try_hwvec_to_u8(pkcs8) }) else {
        panic_msg(
            b"sign.keypair failed: pkcs8 must be a valid bytes HewVec (non-null, plain i32 elements)\0",
        )
    };
    let mut pub_buf = [0u8; ED25519_PUBLIC_LEN];
    // SAFETY: pkcs8_bytes and pub_buf are valid buffers.
    let ok = unsafe {
        hew_ed25519_public_key_from_pkcs8(
            pkcs8_bytes.as_ptr(),
            pkcs8_bytes.len(),
            pub_buf.as_mut_ptr(),
        )
    };
    if ok == 0 {
        panic_msg(b"sign.keypair failed: private_key must be an 83-byte Ed25519 PKCS#8 document\0");
    }
    // SAFETY: pub_buf is a valid byte slice.
    unsafe { hew_cabi::vec::u8_to_hwvec(&pub_buf) }
}

/// Sign `message` (a `bytes` `HewVec`) with `private_key` (an 83-byte PKCS#8
/// `bytes` `HewVec`) and return the 64-byte signature as a `bytes` `HewVec`.
///
/// Calls `hew_panic_msg` if either input is null, has the wrong `HewVec`
/// shape, or `private_key` is not a valid 83-byte PKCS#8 document.
///
/// # Safety
///
/// - `private_key` must be a valid, non-null pointer to a `bytes` `HewVec`.
/// - `message` must be a valid, non-null pointer to a `bytes` `HewVec`.
#[no_mangle]
pub unsafe extern "C" fn hew_ed25519_sign_hew(
    private_key: *mut hew_cabi::vec::HewVec,
    message: *mut hew_cabi::vec::HewVec,
) -> *mut hew_cabi::vec::HewVec {
    // Validate and copy bytes without panicking on null/malformed HewVec.
    // SAFETY: if private_key is non-null the caller guarantees it points to a live HewVec.
    let Some(key_bytes) = (unsafe { hew_cabi::vec::try_hwvec_to_u8(private_key) }) else {
        panic_msg(
            b"sign.sign failed: private_key must be a valid bytes HewVec (non-null, plain i32 elements)\0",
        )
    };
    // SAFETY: if message is non-null the caller guarantees it points to a live HewVec.
    let Some(msg_bytes) = (unsafe { hew_cabi::vec::try_hwvec_to_u8(message) }) else {
        panic_msg(
            b"sign.sign failed: message must be a valid bytes HewVec (non-null, plain i32 elements)\0",
        )
    };

    let mut sig_buf = [0u8; ED25519_SIG_LEN];
    // SAFETY: key_bytes and msg_bytes are valid slices; sig_buf is a 64-byte buffer.
    let ok = unsafe {
        hew_ed25519_sign(
            key_bytes.as_ptr(),
            key_bytes.len(),
            msg_bytes.as_ptr(),
            msg_bytes.len(),
            sig_buf.as_mut_ptr(),
        )
    };
    if ok == 0 {
        panic_msg(b"sign.sign failed: private_key must be an 83-byte Ed25519 PKCS#8 document\0");
    }
    // SAFETY: sig_buf is a valid 64-byte slice.
    unsafe { hew_cabi::vec::u8_to_hwvec(&sig_buf) }
}

/// Verify an Ed25519 `signature` over `message` using `public_key`.
///
/// Returns `1` if the signature is valid, `0` otherwise.  Never panics or
/// aborts — null/malformed `HewVec` inputs, wrong key/signature lengths, and
/// verification failures all return a clean `0`.
///
/// # Safety
///
/// - `public_key`, `message`, and `signature` must each be either null or a
///   valid pointer to a live `bytes` `HewVec`.  Dangling non-null pointers are
///   undefined behaviour.
#[no_mangle]
pub unsafe extern "C" fn hew_ed25519_verify_hew(
    public_key: *mut hew_cabi::vec::HewVec,
    message: *mut hew_cabi::vec::HewVec,
    signature: *mut hew_cabi::vec::HewVec,
) -> i32 {
    // Validate each HewVec without panicking: null or malformed → return 0.
    // SAFETY: if non-null the caller guarantees public_key is a live HewVec.
    let Some(key_bytes) = (unsafe { hew_cabi::vec::try_hwvec_to_u8(public_key) }) else {
        return 0;
    };
    // SAFETY: if non-null the caller guarantees message is a live HewVec.
    let Some(msg_bytes) = (unsafe { hew_cabi::vec::try_hwvec_to_u8(message) }) else {
        return 0;
    };
    // SAFETY: if non-null the caller guarantees signature is a live HewVec.
    let Some(sig_bytes) = (unsafe { hew_cabi::vec::try_hwvec_to_u8(signature) }) else {
        return 0;
    };

    // SAFETY: all slices are valid; raw verify handles length mismatches cleanly.
    unsafe {
        hew_ed25519_verify(
            key_bytes.as_ptr(),
            key_bytes.len(),
            msg_bytes.as_ptr(),
            msg_bytes.len(),
            sig_bytes.as_ptr(),
            sig_bytes.len(),
        )
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    /// Helper: generate a fresh key pair via the raw C-ABI.
    fn gen_pair() -> ([u8; ED25519_PKCS8_LEN], [u8; ED25519_PUBLIC_LEN]) {
        let mut pkcs8 = [0u8; ED25519_PKCS8_LEN];
        let mut public = [0u8; ED25519_PUBLIC_LEN];
        // SAFETY: both buffers are valid for their respective lengths.
        let ok = unsafe { hew_ed25519_generate_pkcs8(pkcs8.as_mut_ptr()) };
        assert_eq!(ok, 1, "key generation must succeed");
        // SAFETY: pkcs8 and public are valid buffers of their respective lengths.
        let ok2 = unsafe {
            hew_ed25519_public_key_from_pkcs8(pkcs8.as_ptr(), pkcs8.len(), public.as_mut_ptr())
        };
        assert_eq!(ok2, 1, "public key extraction must succeed");
        (pkcs8, public)
    }

    // --- sign → verify round-trip ---

    /// A signature produced by `sign` must be accepted by `verify`.
    #[test]
    fn sign_verify_roundtrip_succeeds() {
        let (pkcs8, public) = gen_pair();
        let msg = b"hello hew";
        let mut sig = [0u8; ED25519_SIG_LEN];
        // SAFETY: all buffers are valid.
        let ok = unsafe {
            hew_ed25519_sign(
                pkcs8.as_ptr(),
                pkcs8.len(),
                msg.as_ptr(),
                msg.len(),
                sig.as_mut_ptr(),
            )
        };
        assert_eq!(ok, 1, "signing must succeed");

        // SAFETY: all buffers are valid.
        let verified = unsafe {
            hew_ed25519_verify(
                public.as_ptr(),
                public.len(),
                msg.as_ptr(),
                msg.len(),
                sig.as_ptr(),
                sig.len(),
            )
        };
        assert_eq!(verified, 1, "signature over original message must verify");
    }

    // --- tampered message is rejected ---

    /// Modifying a single byte of the message invalidates the signature.
    #[test]
    fn verify_rejects_tampered_message() {
        let (pkcs8, public) = gen_pair();
        let msg = b"original message";
        let mut sig = [0u8; ED25519_SIG_LEN];
        // SAFETY: all buffers are valid.
        unsafe {
            hew_ed25519_sign(
                pkcs8.as_ptr(),
                pkcs8.len(),
                msg.as_ptr(),
                msg.len(),
                sig.as_mut_ptr(),
            );
        }
        let tampered = b"original XXXXXXX"; // same length, different content
                                            // SAFETY: all buffers are valid.
        let verified = unsafe {
            hew_ed25519_verify(
                public.as_ptr(),
                public.len(),
                tampered.as_ptr(),
                tampered.len(),
                sig.as_ptr(),
                sig.len(),
            )
        };
        assert_eq!(
            verified, 0,
            "signature must be rejected for tampered message"
        );
    }

    // --- wrong public key is rejected ---

    /// A signature verified with the wrong public key must be rejected.
    #[test]
    fn verify_rejects_wrong_public_key() {
        let (pkcs8, _) = gen_pair();
        let (_, wrong_public) = gen_pair();
        let msg = b"test message";
        let mut sig = [0u8; ED25519_SIG_LEN];
        // SAFETY: all buffers are valid.
        unsafe {
            hew_ed25519_sign(
                pkcs8.as_ptr(),
                pkcs8.len(),
                msg.as_ptr(),
                msg.len(),
                sig.as_mut_ptr(),
            );
        }
        // SAFETY: all buffers are valid.
        let verified = unsafe {
            hew_ed25519_verify(
                wrong_public.as_ptr(),
                wrong_public.len(),
                msg.as_ptr(),
                msg.len(),
                sig.as_ptr(),
                sig.len(),
            )
        };
        assert_eq!(
            verified, 0,
            "signature must be rejected for wrong public key"
        );
    }

    // --- malformed signature is rejected ---

    /// A buffer of the right length but wrong content is rejected.
    #[test]
    fn verify_rejects_malformed_signature() {
        let (_, public) = gen_pair();
        let msg = b"test message";
        let bad_sig = [0xAAu8; ED25519_SIG_LEN];
        // SAFETY: all buffers are valid.
        let verified = unsafe {
            hew_ed25519_verify(
                public.as_ptr(),
                public.len(),
                msg.as_ptr(),
                msg.len(),
                bad_sig.as_ptr(),
                bad_sig.len(),
            )
        };
        assert_eq!(verified, 0, "all-0xAA signature must be rejected");
    }

    // --- wrong-length signature is rejected ---

    #[test]
    fn verify_rejects_short_signature() {
        let (_, public) = gen_pair();
        let msg = b"test message";
        let short_sig = [0u8; 32]; // 32, not 64
                                   // SAFETY: all buffers are valid.
        let verified = unsafe {
            hew_ed25519_verify(
                public.as_ptr(),
                public.len(),
                msg.as_ptr(),
                msg.len(),
                short_sig.as_ptr(),
                short_sig.len(),
            )
        };
        assert_eq!(verified, 0, "short signature must be rejected");
    }

    // --- null-pointer guards ---

    #[test]
    fn generate_pkcs8_null_out_returns_zero() {
        // SAFETY: null out is explicitly handled.
        let ok = unsafe { hew_ed25519_generate_pkcs8(std::ptr::null_mut()) };
        assert_eq!(ok, 0);
    }

    #[test]
    fn public_key_from_pkcs8_null_key_returns_zero() {
        let mut out = [0u8; ED25519_PUBLIC_LEN];
        // SAFETY: null pkcs8 is explicitly handled.
        let ok =
            unsafe { hew_ed25519_public_key_from_pkcs8(std::ptr::null(), 0, out.as_mut_ptr()) };
        assert_eq!(ok, 0);
    }

    #[test]
    fn public_key_from_pkcs8_null_out_returns_zero() {
        let (pkcs8, _) = gen_pair();
        // SAFETY: null out is explicitly handled.
        let ok = unsafe {
            hew_ed25519_public_key_from_pkcs8(pkcs8.as_ptr(), pkcs8.len(), std::ptr::null_mut())
        };
        assert_eq!(ok, 0);
    }

    #[test]
    fn sign_null_key_returns_zero() {
        let msg = b"x";
        let mut sig = [0u8; ED25519_SIG_LEN];
        // SAFETY: null key is explicitly handled.
        let ok = unsafe {
            hew_ed25519_sign(
                std::ptr::null(),
                0,
                msg.as_ptr(),
                msg.len(),
                sig.as_mut_ptr(),
            )
        };
        assert_eq!(ok, 0);
    }

    #[test]
    fn sign_null_out_returns_zero() {
        let (pkcs8, _) = gen_pair();
        let msg = b"x";
        // SAFETY: null sig_out is explicitly handled.
        let ok = unsafe {
            hew_ed25519_sign(
                pkcs8.as_ptr(),
                pkcs8.len(),
                msg.as_ptr(),
                msg.len(),
                std::ptr::null_mut(),
            )
        };
        assert_eq!(ok, 0);
    }

    #[test]
    fn verify_null_public_key_returns_zero() {
        let msg = b"x";
        let sig = [0u8; ED25519_SIG_LEN];
        // SAFETY: null public_key is explicitly handled.
        let verified = unsafe {
            hew_ed25519_verify(
                std::ptr::null(),
                0,
                msg.as_ptr(),
                msg.len(),
                sig.as_ptr(),
                sig.len(),
            )
        };
        assert_eq!(verified, 0);
    }

    #[test]
    fn verify_null_sig_returns_zero() {
        let (_, public) = gen_pair();
        let msg = b"x";
        // SAFETY: null sig is explicitly handled.
        let verified = unsafe {
            hew_ed25519_verify(
                public.as_ptr(),
                public.len(),
                msg.as_ptr(),
                msg.len(),
                std::ptr::null(),
                0,
            )
        };
        assert_eq!(verified, 0);
    }

    // --- sign with invalid PKCS#8 key ---

    #[test]
    fn sign_invalid_key_returns_zero() {
        let bad_key = [0u8; ED25519_PKCS8_LEN]; // not a valid PKCS#8 document
        let msg = b"test";
        let mut sig = [0u8; ED25519_SIG_LEN];
        // SAFETY: all buffers are valid; bad_key is the right length but invalid content.
        let ok = unsafe {
            hew_ed25519_sign(
                bad_key.as_ptr(),
                bad_key.len(),
                msg.as_ptr(),
                msg.len(),
                sig.as_mut_ptr(),
            )
        };
        assert_eq!(ok, 0, "signing with an invalid key must return 0");
        // sig_out must remain all-zero (not partially written).
        assert_eq!(
            sig, [0u8; ED25519_SIG_LEN],
            "sig_out must be untouched on failure"
        );
    }

    // --- empty message round-trip ---

    #[test]
    fn sign_verify_empty_message() {
        let (pkcs8, public) = gen_pair();
        let mut sig = [0u8; ED25519_SIG_LEN];
        // SAFETY: null msg with msg_len=0 is the empty-message path.
        let ok = unsafe {
            hew_ed25519_sign(
                pkcs8.as_ptr(),
                pkcs8.len(),
                std::ptr::null(),
                0,
                sig.as_mut_ptr(),
            )
        };
        assert_eq!(ok, 1);
        // SAFETY: all buffers are valid.
        let verified = unsafe {
            hew_ed25519_verify(
                public.as_ptr(),
                public.len(),
                std::ptr::null(),
                0,
                sig.as_ptr(),
                sig.len(),
            )
        };
        assert_eq!(verified, 1, "signature over empty message must verify");
    }

    // --- two fresh key pairs produce different keys ---

    #[test]
    fn generate_produces_distinct_key_pairs() {
        let (pkcs8_a, _) = gen_pair();
        let (pkcs8_b, _) = gen_pair();
        assert_ne!(pkcs8_a, pkcs8_b, "two generated key pairs must differ");
    }

    // --- signing is deterministic for Ed25519 (RFC 8032 deterministic nonce) ---

    #[test]
    fn sign_deterministic_same_key_same_message() {
        let (pkcs8, _) = gen_pair();
        let msg = b"deterministic";
        let mut sig1 = [0u8; ED25519_SIG_LEN];
        let mut sig2 = [0u8; ED25519_SIG_LEN];
        // SAFETY: all buffers are valid.
        unsafe {
            hew_ed25519_sign(
                pkcs8.as_ptr(),
                pkcs8.len(),
                msg.as_ptr(),
                msg.len(),
                sig1.as_mut_ptr(),
            );
            hew_ed25519_sign(
                pkcs8.as_ptr(),
                pkcs8.len(),
                msg.as_ptr(),
                msg.len(),
                sig2.as_mut_ptr(),
            );
        }
        assert_eq!(sig1, sig2, "Ed25519 signing must be deterministic");
    }

    // --- public_key_from_pkcs8 rejects invalid document ---

    #[test]
    fn public_key_from_pkcs8_rejects_invalid_document() {
        let bad = [0u8; ED25519_PKCS8_LEN];
        let mut out = [0u8; ED25519_PUBLIC_LEN];
        // SAFETY: bad is the right length but not a valid PKCS#8 document.
        let ok =
            unsafe { hew_ed25519_public_key_from_pkcs8(bad.as_ptr(), bad.len(), out.as_mut_ptr()) };
        assert_eq!(ok, 0, "invalid PKCS#8 must be rejected");
    }

    // --- _hew wrapper HewVec guards ---
    //
    // These tests exercise the fail-closed path added to the _hew wrappers:
    // null / malformed HewVec inputs must never abort the process.

    /// Helper: build a minimal bytes-shaped `HewVec` on the stack (zero elements).
    ///
    /// Returns the struct and a raw pointer to it.  The pointer is valid for the
    /// lifetime of the struct binding in the caller's stack frame.
    fn make_empty_bytes_vec() -> hew_cabi::vec::HewVec {
        // SAFETY: layout fields are null / zeroed; empty vec so data is never read.
        unsafe {
            hew_cabi::vec::HewVec {
                data: std::ptr::null_mut(),
                len: 0,
                cap: 0,
                elem_size: std::mem::size_of::<i32>(),
                elem_kind: hew_cabi::vec::ElemKind::Plain,
                layout: std::ptr::null(),
                layout_storage: core::mem::zeroed(),
                elem_layout: std::ptr::null(),
                elem_layout_storage: core::mem::zeroed(),
            }
        }
    }

    /// A malformed `HewVec` (wrong `elem_size`, non-Plain kind, etc.).
    fn make_malformed_vec() -> hew_cabi::vec::HewVec {
        // SAFETY: layout fields are null / zeroed.
        unsafe {
            hew_cabi::vec::HewVec {
                data: std::ptr::null_mut(),
                len: 0,
                cap: 0,
                elem_size: std::mem::size_of::<i64>(), // wrong — should be i32
                elem_kind: hew_cabi::vec::ElemKind::Plain,
                layout: std::ptr::null(),
                layout_storage: core::mem::zeroed(),
                elem_layout: std::ptr::null(),
                elem_layout_storage: core::mem::zeroed(),
            }
        }
    }

    #[test]
    fn verify_hew_null_public_key_returns_zero() {
        let mut msg_vec = make_empty_bytes_vec();
        let mut sig_vec = make_empty_bytes_vec();
        // SAFETY: msg_vec and sig_vec are valid live HewVecs; public_key is
        // intentionally null to exercise the fail-closed guard.
        let result = unsafe {
            hew_ed25519_verify_hew(std::ptr::null_mut(), &raw mut msg_vec, &raw mut sig_vec)
        };
        assert_eq!(result, 0, "null public_key must return 0");
    }

    #[test]
    fn verify_hew_null_message_returns_zero() {
        let mut key_vec = make_empty_bytes_vec();
        let mut sig_vec = make_empty_bytes_vec();
        // SAFETY: key_vec and sig_vec are valid live HewVecs; message is
        // intentionally null to exercise the fail-closed guard.
        let result = unsafe {
            hew_ed25519_verify_hew(&raw mut key_vec, std::ptr::null_mut(), &raw mut sig_vec)
        };
        assert_eq!(result, 0, "null message must return 0");
    }

    #[test]
    fn verify_hew_null_signature_returns_zero() {
        let mut key_vec = make_empty_bytes_vec();
        let mut msg_vec = make_empty_bytes_vec();
        // SAFETY: key_vec and msg_vec are valid live HewVecs; signature is
        // intentionally null to exercise the fail-closed guard.
        let result = unsafe {
            hew_ed25519_verify_hew(&raw mut key_vec, &raw mut msg_vec, std::ptr::null_mut())
        };
        assert_eq!(result, 0, "null signature must return 0");
    }

    #[test]
    fn verify_hew_malformed_public_key_returns_zero() {
        let mut bad_key = make_malformed_vec();
        let mut msg_vec = make_empty_bytes_vec();
        let mut sig_vec = make_empty_bytes_vec();
        // SAFETY: all pointers point to live HewVecs on the stack; bad_key
        // has wrong elem_size to exercise the shape-guard path.
        let result =
            unsafe { hew_ed25519_verify_hew(&raw mut bad_key, &raw mut msg_vec, &raw mut sig_vec) };
        assert_eq!(result, 0, "malformed public_key HewVec must return 0");
    }

    #[test]
    fn verify_hew_malformed_signature_returns_zero() {
        let mut key_vec = make_empty_bytes_vec();
        let mut msg_vec = make_empty_bytes_vec();
        let mut bad_sig = make_malformed_vec();
        // SAFETY: all pointers point to live HewVecs on the stack; bad_sig
        // has wrong elem_size to exercise the shape-guard path.
        let result =
            unsafe { hew_ed25519_verify_hew(&raw mut key_vec, &raw mut msg_vec, &raw mut bad_sig) };
        assert_eq!(result, 0, "malformed signature HewVec must return 0");
    }
}
