//! `HewVec` type definition and byte-conversion helpers.
//!
//! This module re-declares the `HewVec` struct and `ElemKind` enum so that
//! native package crates can reference them without depending on the full
//! hew-runtime.  The actual `hew_vec_*` function bodies live in hew-runtime;
//! here we provide `extern "C"` declarations that resolve at link time.

use core::ffi::{c_char, c_void};
use core::mem;

/// Descriptor-level ownership discipline for runtime-managed aggregate values.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum HewTypeOwnershipKind {
    /// Elements can be copied and dropped as raw bytes.
    Plain = 0,
    /// Elements are C string pointers with refcounted retain/release ownership
    /// (`hew_string_clone` / `hew_string_drop`).
    String = 1,
    /// Elements require layout-driven clone/drop semantics not implemented yet.
    LayoutManaged = 2,
    /// Elements are `bytes` values (`BytesTriple` at the ABI). Used by the
    /// channel/stream element witness, where a bytes element travels as its
    /// contents (the queue envelope IS the value, matching what platform
    /// stream backings produce natively). Collection constructors reject this
    /// kind fail-closed — `Vec`/`HashMap` describe bytes elements through
    /// their own dedicated paths, never through this discriminant.
    Bytes = 3,
}

/// Runtime-visible layout descriptor for a plain Hew value type.
///
/// This remains the per-call descriptor for the legacy `BitCopy` `_layout`
/// operations. `HewVec` stores only the thunk-bearing [`HewVecElemLayout`]
/// witness, so clone/drop never depend on this thunk-less shape.
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct HewTypeLayout {
    /// Size of one value in bytes.
    pub size: usize,
    /// Required alignment in bytes.
    pub align: usize,
    /// Ownership discipline used by layout-aware collection operations.
    pub ownership_kind: HewTypeOwnershipKind,
}

/// Discriminator for element ownership semantics.
///
/// Used by clone/truncate/free/clear to decide whether elements need
/// deep-copy (`strdup`) or individual `free`.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ElemKind {
    /// Plain value type (i32, i64, f64, structs, etc.) — no special handling.
    Plain = 0,
    /// String (`*const c_char`) — elements are header-aware, refcounted
    /// buffers. On ingress (`hew_vec_push_str`/`set_str`) the producer's bytes
    /// are **copied in** to a fresh header-bearing allocation (internal
    /// producers hand over headerless buffers that cannot be retained). On
    /// internal propagation (`clone`/`slice`/`append`/`get_str`) an element is
    /// **retained** (refcount bump, same buffer); on removal or drop
    /// (`free`/`truncate`/`pop_str`) it is **released** (refcount decrement,
    /// free at zero). Built only through the typed `hew_vec_new_str` family —
    /// the untyped `hew_vec_new_generic` rejects this kind fail-closed.
    String = 1,
}

/// Dynamic array matching the C `HewVec` layout.
#[repr(C)]
#[derive(Debug)]
pub struct HewVec {
    /// Pointer to the backing buffer.
    pub data: *mut u8,
    /// Number of elements currently stored.
    pub len: usize,
    /// Allocated capacity (in elements).
    pub cap: usize,
    /// Size of each element in bytes.
    pub elem_size: usize,
    /// Element ownership semantics.
    pub elem_kind: ElemKind,
    /// Optional runtime element descriptor. Null preserves the legacy typed path.
    ///
    /// When non-null, always points into `layout_storage` (same allocation).
    /// Callers must not assume this pointer outlives the `HewVec`.
    pub layout: *const HewVecElemLayout,
    /// Inline storage for the descriptor copied in by
    /// `hew_vec_new_with_layout` or `hew_vec_new_with_elem_layout`.
    ///
    /// Keeping the descriptor inside the vec allocation means the pointer above
    /// never dangles. Plain `_layout` constructors widen their thunk-less
    /// `HewTypeLayout` argument into this authoritative shape with null thunks.
    pub layout_storage: HewVecElemLayout,
}

/// Equality callback for layout-backed Vec contains.
///
/// Returns non-zero when the two values are equal. The callback is generated by
/// codegen for the concrete element type, so it must not inspect padding bytes.
pub type HewVecEqThunk = unsafe extern "C" fn(a: *const c_void, b: *const c_void) -> i32;

// `HewVecElemLayout` is the element protocol for descriptor-backed vectors.
// Plain values may omit callbacks; owning values require semantic clone/drop.
// The descriptor is copied into each vector, so its storage outlives the call
// that creates the vector. Callback code must outlive every vector using it.
//
// Copy-in push/set borrow their input and create an independent logical value.
// Move-in push/set transfer the input's cleanup obligation. Pop moves a value
// out. `get_owned` returns an interior borrow valid until mutation or release;
// `get_clone` instead writes an independent value that may outlive the vector.
// Clear, overwrite and release destroy each removed live value exactly once.
//
// Before invoking a clone callback, the runtime copies the complete element
// bytes into the destination. The callback replaces owning fields with their
// semantic copies; scalar fields and tags are already initialized. On failure,
// it releases its partial copies and leaves no live destination obligation.
// A release-only descriptor may omit cloning, but copy operations reject it.

/// Thunk that clones an owned Vec element from `src` to `dst`.
///
/// - `src` — non-null read-only pointer to the source element blob.
/// - `dst` — non-null mutable pointer to the destination slot. The caller MUST
///   have memcpy'd `dst <- src` (size bytes) BEFORE invoking this thunk so that
///   `BitCopy` fields and any enum tag/inactive bytes are already correct; the
///   thunk deep-clones only the owned (heap-owning) fields in place.
/// - Returns 0 on success, non-zero when a partial clone was rolled back.
///
pub type HewVecElemCloneThunk = unsafe extern "C" fn(src: *const c_void, dst: *mut c_void) -> i32;

/// Thunk that drops an owned Vec element in place.
///
/// - `slot` — non-null mutable pointer to the owned element blob. The thunk
///   releases the element's managed values and nested containers, but does
///   not deallocate the slot
///   bytes themselves — the Vec owns the buffer and frees it afterward.
/// - Invoked exactly once per dropped element: at set-overwrite (old element),
///   and at free (every live slot).
///
pub type HewVecElemDropThunk = unsafe extern "C" fn(slot: *mut c_void);

// Rust guarantees fn pointers are non-null, so `Option<fn>` niche-optimises to
// the underlying fn-pointer width — the null value is the `None` discriminant.
// These asserts lock the invariant so a future Rust change breaks loudly here
// rather than silently at the C boundary.
const _: () = assert!(
    size_of::<Option<HewVecElemCloneThunk>>() == size_of::<HewVecElemCloneThunk>(),
    "Option<HewVecElemCloneThunk> must be niche-optimised to the same size as HewVecElemCloneThunk",
);
const _: () = assert!(
    size_of::<Option<HewVecElemDropThunk>>() == size_of::<HewVecElemDropThunk>(),
    "Option<HewVecElemDropThunk> must be niche-optimised to the same size as HewVecElemDropThunk",
);

/// Per-element layout and ownership protocol for a descriptor-backed vector.
///
/// The callbacks implement the concrete element's semantic copy and cleanup.
/// Plain elements may omit both; release-only elements may omit cloning.
///
/// # C layout
///
/// `#[repr(C)]` guarantees field order and alignment match the C struct:
///
/// ```c
/// typedef struct {
///     size_t                  size;
///     size_t                  align;
///     HewTypeOwnershipKind    ownership_kind;
///     /* padding to pointer alignment */
///     HewVecElemCloneThunk    clone_fn;  /* NULL for plain or release-only values */
///     HewVecElemDropThunk     drop_fn;   /* may be NULL only when ownership_kind == Plain */
/// } HewVecElemLayout;
/// ```
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct HewVecElemLayout {
    /// Size of one element in bytes.
    pub size: usize,
    /// Required alignment in bytes (a non-zero power of two).
    pub align: usize,
    /// Ownership discipline of the element type.
    pub ownership_kind: HewTypeOwnershipKind,
    /// Clone thunk invoked on push/set/clone (deep copy in). `None` is valid for
    /// Plain elements and release-only descriptors; clone entry points reject a
    /// missing thunk when semantic cloning is required.
    pub clone_fn: Option<HewVecElemCloneThunk>,
    /// Drop thunk invoked on set-overwrite, truncate/clear, and free. `None` is
    /// valid only for `ownership_kind == Plain`.
    pub drop_fn: Option<HewVecElemDropThunk>,
}

#[cfg(target_pointer_width = "64")]
const _: () = {
    assert!(core::mem::offset_of!(HewVecElemLayout, size) == 0);
    assert!(core::mem::offset_of!(HewVecElemLayout, align) == 8);
    assert!(core::mem::offset_of!(HewVecElemLayout, ownership_kind) == 16);
    assert!(core::mem::offset_of!(HewVecElemLayout, clone_fn) == 24);
    assert!(core::mem::offset_of!(HewVecElemLayout, drop_fn) == 32);
    assert!(core::mem::size_of::<HewVecElemLayout>() == 40);

    assert!(core::mem::offset_of!(HewVec, data) == 0);
    assert!(core::mem::offset_of!(HewVec, len) == 8);
    assert!(core::mem::offset_of!(HewVec, cap) == 16);
    assert!(core::mem::offset_of!(HewVec, elem_size) == 24);
    assert!(core::mem::offset_of!(HewVec, elem_kind) == 32);
    assert!(core::mem::offset_of!(HewVec, layout) == 40);
    assert!(core::mem::offset_of!(HewVec, layout_storage) == 48);
    assert!(core::mem::size_of::<HewVec>() == 88);
};

#[cfg(target_pointer_width = "32")]
const _: () = {
    assert!(core::mem::offset_of!(HewVecElemLayout, size) == 0);
    assert!(core::mem::offset_of!(HewVecElemLayout, align) == 4);
    assert!(core::mem::offset_of!(HewVecElemLayout, ownership_kind) == 8);
    assert!(core::mem::offset_of!(HewVecElemLayout, clone_fn) == 12);
    assert!(core::mem::offset_of!(HewVecElemLayout, drop_fn) == 16);
    assert!(core::mem::size_of::<HewVecElemLayout>() == 20);

    assert!(core::mem::offset_of!(HewVec, data) == 0);
    assert!(core::mem::offset_of!(HewVec, len) == 4);
    assert!(core::mem::offset_of!(HewVec, cap) == 8);
    assert!(core::mem::offset_of!(HewVec, elem_size) == 12);
    assert!(core::mem::offset_of!(HewVec, elem_kind) == 16);
    assert!(core::mem::offset_of!(HewVec, layout) == 20);
    assert!(core::mem::offset_of!(HewVec, layout_storage) == 24);
    assert!(core::mem::size_of::<HewVec>() == 44);
};

// ---------------------------------------------------------------------------
// Extern declarations — resolved at link time against libhew_runtime.a
// ---------------------------------------------------------------------------

extern "C" {
    // Constructors
    pub fn hew_vec_new() -> *mut HewVec;
    pub fn hew_vec_new_bool() -> *mut HewVec;
    pub fn hew_vec_new_i8() -> *mut HewVec;
    pub fn hew_vec_new_u8() -> *mut HewVec;
    pub fn hew_vec_new_i16() -> *mut HewVec;
    pub fn hew_vec_new_u16() -> *mut HewVec;
    pub fn hew_vec_new_i64() -> *mut HewVec;
    pub fn hew_vec_new_f32() -> *mut HewVec;
    pub fn hew_vec_new_f64() -> *mut HewVec;
    pub fn hew_vec_new_str() -> *mut HewVec;
    pub fn hew_vec_new_ptr() -> *mut HewVec;
    pub fn hew_vec_new_with_elem_size(elem_size: i64) -> *mut HewVec;
    pub fn hew_vec_new_generic(elem_size: i64, elem_kind: i64) -> *mut HewVec;
    pub fn hew_vec_new_with_layout(layout: *const HewTypeLayout) -> *mut HewVec;
    // Owned-element constructor (W5.016). Stamps `elem_layout` from the
    // descriptor; the owned ops below read the clone/drop thunks from it.
    pub fn hew_vec_new_with_elem_layout(layout: *const HewVecElemLayout) -> *mut HewVec;

    // Push
    pub fn hew_vec_push_bool(v: *mut HewVec, val: bool);
    pub fn hew_vec_push_i8(v: *mut HewVec, val: i8);
    pub fn hew_vec_push_u8(v: *mut HewVec, val: u8);
    pub fn hew_vec_push_i16(v: *mut HewVec, val: i16);
    pub fn hew_vec_push_u16(v: *mut HewVec, val: u16);
    pub fn hew_vec_push_i32(v: *mut HewVec, val: i32);
    pub fn hew_vec_push_i64(v: *mut HewVec, val: i64);
    pub fn hew_vec_push_f32(v: *mut HewVec, val: f32);
    pub fn hew_vec_push_f64(v: *mut HewVec, val: f64);
    pub fn hew_vec_push_str(v: *mut HewVec, val: *const c_char);
    pub fn hew_vec_push_ptr(v: *mut HewVec, val: *mut c_void);
    pub fn hew_vec_push_generic(v: *mut HewVec, data: *const c_void);
    pub fn hew_vec_push_layout(v: *mut HewVec, data: *const c_void, layout: *const HewTypeLayout);
    // Owned-element push (W5.016): memcpy + clone_fn (deep copy in).
    pub fn hew_vec_push_owned(v: *mut HewVec, data: *const c_void);
    // Owned-element push by MOVE: memcpy only, no clone_fn. For a fresh,
    // single-use element source (the array-literal desugar) whose heap
    // ownership transfers to the Vec; the source is dead after the call.
    pub fn hew_vec_push_owned_move(v: *mut HewVec, data: *const c_void);

    // Get
    pub fn hew_vec_get_bool(v: *mut HewVec, index: i64) -> bool;
    pub fn hew_vec_get_i8(v: *mut HewVec, index: i64) -> i8;
    pub fn hew_vec_get_u8(v: *mut HewVec, index: i64) -> u8;
    pub fn hew_vec_get_i16(v: *mut HewVec, index: i64) -> i16;
    pub fn hew_vec_get_u16(v: *mut HewVec, index: i64) -> u16;
    #[cfg(not(test))]
    pub fn hew_vec_get_i32(v: *mut HewVec, index: i64) -> i32;
    pub fn hew_vec_get_i64(v: *mut HewVec, index: i64) -> i64;
    pub fn hew_vec_get_f32(v: *mut HewVec, index: i64) -> f32;
    pub fn hew_vec_get_f64(v: *mut HewVec, index: i64) -> f64;
    pub fn hew_vec_get_str(v: *mut HewVec, index: i64) -> *const c_char;
    pub fn hew_vec_get_ptr(v: *mut HewVec, index: i64) -> *mut c_void;
    pub fn hew_vec_get_generic(v: *const HewVec, index: i64) -> *const c_void;
    pub fn hew_vec_get_layout(
        v: *const HewVec,
        index: i64,
        layout: *const HewTypeLayout,
    ) -> *const c_void;
    // Owned-element get (W5.016): borrow into the live buffer (no clone/drop).
    pub fn hew_vec_get_owned(v: *const HewVec, index: i64) -> *const c_void;
    // Trait-routed `Vec::get` choke point: fresh-owner `Option<T>` getter.
    // Bounds-checks, writes a freshly retained/cloned owner into `out` and
    // returns `true` on hit; `false` (out untouched) on OOB. The single
    // drop-safe Vec-get site (`by-value-heap-params-are-borrows` P0).
    pub fn hew_vec_get_clone(v: *const HewVec, index: i64, out: *mut c_void) -> bool;

    // Set
    pub fn hew_vec_set_bool(v: *mut HewVec, index: i64, val: bool);
    pub fn hew_vec_set_i8(v: *mut HewVec, index: i64, val: i8);
    pub fn hew_vec_set_u8(v: *mut HewVec, index: i64, val: u8);
    pub fn hew_vec_set_i16(v: *mut HewVec, index: i64, val: i16);
    pub fn hew_vec_set_u16(v: *mut HewVec, index: i64, val: u16);
    pub fn hew_vec_set_i32(v: *mut HewVec, index: i64, val: i32);
    pub fn hew_vec_set_i64(v: *mut HewVec, index: i64, val: i64);
    pub fn hew_vec_set_f32(v: *mut HewVec, index: i64, val: f32);
    pub fn hew_vec_set_f64(v: *mut HewVec, index: i64, val: f64);
    pub fn hew_vec_set_str(v: *mut HewVec, index: i64, val: *const c_char);
    pub fn hew_vec_set_generic(v: *mut HewVec, index: i64, data: *const c_void);
    pub fn hew_vec_set_layout(
        v: *mut HewVec,
        index: i64,
        data: *const c_void,
        layout: *const HewTypeLayout,
    );
    // Owned-element set (W5.016): drop_fn old, then memcpy + clone_fn new.
    pub fn hew_vec_set_owned(v: *mut HewVec, index: i64, data: *const c_void);

    // Pop
    pub fn hew_vec_pop_bool(v: *mut HewVec) -> bool;
    pub fn hew_vec_pop_i8(v: *mut HewVec) -> i8;
    pub fn hew_vec_pop_u8(v: *mut HewVec) -> u8;
    pub fn hew_vec_pop_i16(v: *mut HewVec) -> i16;
    pub fn hew_vec_pop_u16(v: *mut HewVec) -> u16;
    pub fn hew_vec_pop_i32(v: *mut HewVec) -> i32;
    pub fn hew_vec_pop_i64(v: *mut HewVec) -> i64;
    pub fn hew_vec_pop_f32(v: *mut HewVec) -> f32;
    pub fn hew_vec_pop_f64(v: *mut HewVec) -> f64;
    pub fn hew_vec_pop_str(v: *mut HewVec) -> *const c_char;
    pub fn hew_vec_pop_generic(v: *mut HewVec, out: *mut c_void) -> i32;
    pub fn hew_vec_pop_layout(
        v: *mut HewVec,
        out: *mut c_void,
        layout: *const HewTypeLayout,
    ) -> i32;
    // Owned-element pop (W5.016): memcpy to `out` (move out), NO drop.
    pub fn hew_vec_pop_owned(v: *mut HewVec, out: *mut c_void) -> i32;

    // Queries
    #[cfg(not(test))]
    pub fn hew_vec_len(v: *mut HewVec) -> i64;
    pub fn hew_vec_is_empty(v: *mut HewVec) -> bool;

    // Mutation
    pub fn hew_vec_clear(v: *mut HewVec);
    pub fn hew_vec_free(v: *mut HewVec);
    pub fn hew_vec_sort_i32(v: *mut HewVec);
    pub fn hew_vec_sort_i64(v: *mut HewVec);
    pub fn hew_vec_sort_f64(v: *mut HewVec);
    pub fn hew_vec_clone(v: *const HewVec) -> *mut HewVec;
    pub fn hew_vec_clone_layout(v: *const HewVec, layout: *const HewTypeLayout) -> *mut HewVec;
    // Descriptor-driven clone/free pair. Both symbols use the same recursive
    // protocol as `hew_vec_clone`/`hew_vec_free`; the `_owned` names remain for
    // existing owned-element call sites while context-specific managed and
    // closure-pair variants are retired.
    pub fn hew_vec_clone_owned(v: *const HewVec) -> *mut HewVec;
    pub fn hew_vec_free_owned(v: *mut HewVec);
    pub fn hew_vec_append(dst: *mut HewVec, src: *const HewVec);
    pub fn hew_vec_swap(v: *mut HewVec, i: i64, j: i64);
    pub fn hew_vec_truncate(v: *mut HewVec, new_len: i64);
    pub fn hew_vec_reverse_i32(v: *mut HewVec);

    // Contains
    pub fn hew_vec_contains_i32(v: *const HewVec, val: i32) -> i32;
    pub fn hew_vec_contains_i64(v: *const HewVec, val: i64) -> i32;
    pub fn hew_vec_contains_f64(v: *const HewVec, val: f64) -> i32;
    pub fn hew_vec_contains_str(v: *const HewVec, val: *const c_char) -> i32;
    pub fn hew_vec_contains_layout(
        v: *const HewVec,
        data: *const c_void,
        layout: *const HewTypeLayout,
    ) -> i32;
    pub fn hew_vec_contains_thunk(
        v: *const HewVec,
        data: *const c_void,
        eq_fn: Option<HewVecEqThunk>,
    ) -> i32;
    pub fn hew_vec_equals_thunk(
        lhs: *const HewVec,
        rhs: *const HewVec,
        eq_fn: Option<HewVecEqThunk>,
    ) -> i32;
    pub fn hew_vec_contains_owned(
        v: *const HewVec,
        data: *const c_void,
        eq_fn: Option<HewVecEqThunk>,
    ) -> i32;
    pub fn hew_vec_slice_range_layout(
        v: *mut HewVec,
        start: i64,
        end: i64,
        layout: *const HewTypeLayout,
    ) -> *mut HewVec;
    pub fn hew_vec_slice_range_owned(v: *mut HewVec, start: i64, end: i64) -> *mut HewVec;

    // Remove
    pub fn hew_vec_remove_i32(v: *mut HewVec, val: i32);
    pub fn hew_vec_remove_i64(v: *mut HewVec, val: i64);
    pub fn hew_vec_remove_ptr(v: *mut HewVec, val: *mut c_void);
    pub fn hew_vec_remove_at_layout(v: *mut HewVec, index: i64, layout: *const HewTypeLayout);
}

#[cfg(test)]
#[no_mangle]
#[expect(
    clippy::not_unsafe_ptr_arg_deref,
    reason = "test stub mirrors the runtime ABI export"
)]
pub extern "C" fn hew_vec_len(v: *mut HewVec) -> i64 {
    if v.is_null() {
        return 0;
    }
    #[expect(
        clippy::cast_possible_wrap,
        reason = "test stub mirrors platform-sized len in i64 space"
    )]
    // SAFETY: the test stub only dereferences the caller-provided `HewVec`.
    unsafe {
        (*v).len as i64
    }
}

#[cfg(test)]
#[no_mangle]
#[expect(
    clippy::not_unsafe_ptr_arg_deref,
    clippy::cast_ptr_alignment,
    clippy::missing_panics_doc,
    reason = "test stub mirrors the runtime ABI export"
)]
pub extern "C" fn hew_vec_get_i32(v: *mut HewVec, index: i64) -> i32 {
    assert!(!v.is_null(), "test stub requires a non-null HewVec");
    let index: usize = index
        .try_into()
        .expect("test stub index must be non-negative");
    // SAFETY: the null check above ensures `v` is safe to inspect here.
    assert!(index < unsafe { (*v).len }, "test stub index out of bounds");
    // SAFETY: the null check above ensures `v` is safe to inspect here.
    let data = unsafe { (*v).data.cast::<i32>() };
    // SAFETY: the bounds check above ensures `index` addresses initialized data.
    unsafe { *data.add(index) }
}

// ---------------------------------------------------------------------------
// bytes <-> HewVec helpers (used by codec wrappers in native packages)
// ---------------------------------------------------------------------------

/// Extract raw bytes from a `bytes`-typed `HewVec` (i32 elements, one byte per slot).
///
/// Copies the payload bytes into a fresh `Vec<u8>`; does not consume or free
/// the `HewVec` header — ownership stays with the caller.
///
/// # Safety
///
/// `v` must be a valid, non-null pointer to a `HewVec` with i32 element size.
///
/// # Panics
///
/// Panics if `v` is null, has non-plain elements, has the wrong element size,
/// or contains values outside the byte range `0..=255`.
pub unsafe fn hwvec_to_u8(v: *mut HewVec) -> Vec<u8> {
    assert!(!v.is_null(), "hwvec_to_u8: null HewVec pointer");
    // SAFETY: the caller promises `v` points to a valid HewVec.
    let vec = unsafe { &*v };
    assert!(
        vec.elem_kind == ElemKind::Plain,
        "hwvec_to_u8: expected plain elements, got {:?}",
        vec.elem_kind
    );
    assert!(
        vec.elem_size == mem::size_of::<i32>(),
        "hwvec_to_u8: expected elem_size {}, got {}",
        mem::size_of::<i32>(),
        vec.elem_size
    );
    // SAFETY: caller guarantees v is a valid HewVec.
    #[cfg(test)]
    let len = hew_vec_len(v);
    #[cfg(not(test))]
    // SAFETY: caller guarantees `v` points to a valid HewVec.
    let len = unsafe { hew_vec_len(v) };
    (0..len)
        .map(|i| {
            #[cfg(test)]
            let raw = hew_vec_get_i32(v, i);
            #[cfg(not(test))]
            // SAFETY: `i < len`, so the read is in-bounds for the caller-provided HewVec.
            let raw = unsafe { hew_vec_get_i32(v, i) };
            u8::try_from(raw).expect("hwvec_to_u8: element out of byte range")
        })
        .collect()
}

/// Non-panicking variant of [`hwvec_to_u8`].
///
/// Copies the payload bytes into a fresh `Vec<u8>` and returns `Some(Vec<u8>)`
/// on success.  Returns `None` if `v` is null, has the wrong element shape
/// (`elem_kind` != `Plain` or `elem_size` != `size_of::<i32>()`), or contains
/// a value outside the byte range `0..=255`, or reports a negative length.
/// Does not consume or free the `HewVec` header — ownership stays with the
/// caller.
///
/// This is the correct choice for any call site that must be fail-closed rather
/// than abort-on-bad-input (e.g. FFI wrappers that return a sentinel on error).
///
/// # Safety
///
/// If `v` is non-null it must point to a valid, live `HewVec`.  Calling with a
/// dangling (but non-null) pointer is undefined behaviour.
pub unsafe fn try_hwvec_to_u8(v: *mut HewVec) -> Option<Vec<u8>> {
    if v.is_null() {
        return None;
    }
    // SAFETY: the caller promises `v` is a valid, live HewVec when non-null.
    let vec = unsafe { &*v };
    if vec.elem_kind != ElemKind::Plain || vec.elem_size != mem::size_of::<i32>() {
        return None;
    }
    // SAFETY: caller guarantees v is a valid HewVec.
    #[cfg(test)]
    let len = hew_vec_len(v);
    #[cfg(not(test))]
    // SAFETY: caller guarantees `v` points to a valid HewVec.
    let len = unsafe { hew_vec_len(v) };
    if len < 0 {
        return None;
    }
    let len_usize = usize::try_from(len).ok()?;
    let mut out = Vec::with_capacity(len_usize);
    for i in 0..len {
        #[cfg(test)]
        let raw = hew_vec_get_i32(v, i);
        #[cfg(not(test))]
        // SAFETY: `i < len`, so the read is in-bounds for the caller-provided HewVec.
        let raw = unsafe { hew_vec_get_i32(v, i) };
        match u8::try_from(raw) {
            Ok(b) => out.push(b),
            Err(_) => return None,
        }
    }
    Some(out)
}

/// Create a new bytes-typed `HewVec` (i32 elements) from a raw u8 slice.
///
/// # Safety
///
/// None — all memory is managed by the runtime allocator.
#[must_use]
pub unsafe fn u8_to_hwvec(data: &[u8]) -> *mut HewVec {
    // SAFETY: hew_vec_new allocates a valid HewVec.
    let v = unsafe { hew_vec_new() };
    for &b in data {
        // SAFETY: v is non-null (hew_vec_new aborts on OOM).
        unsafe { hew_vec_push_i32(v, i32::from(b)) };
    }
    v
}

// ---------------------------------------------------------------------------
// Tests — struct layout and discriminant values
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    // ── ElemKind discriminant values (ABI contract) ──────────────────────

    #[test]
    fn elem_kind_plain_is_zero() {
        assert_eq!(ElemKind::Plain as u8, 0, "Plain must be 0 for C interop");
    }

    #[test]
    fn elem_kind_string_is_one() {
        assert_eq!(ElemKind::String as u8, 1, "String must be 1 for C interop");
    }

    #[test]
    fn elem_kind_size_is_one_byte() {
        assert_eq!(
            std::mem::size_of::<ElemKind>(),
            1,
            "repr(u8) must be exactly 1 byte"
        );
    }

    // ── HewTypeLayout ABI scaffold ───────────────────────────────────────

    #[test]
    fn ownership_kind_discriminants_are_stable() {
        assert_eq!(HewTypeOwnershipKind::Plain as u8, 0);
        assert_eq!(HewTypeOwnershipKind::String as u8, 1);
        assert_eq!(HewTypeOwnershipKind::LayoutManaged as u8, 2);
        assert_eq!(HewTypeOwnershipKind::Bytes as u8, 3);
    }

    #[test]
    fn ownership_kind_size_is_one_byte() {
        assert_eq!(std::mem::size_of::<HewTypeOwnershipKind>(), 1);
    }

    // ── HewVec layout (must match the C struct) ─────────────────────────

    #[test]
    fn hewvec_is_repr_c() {
        // Verify the struct size is the sum of its fields with C alignment.
        // On 64-bit: data pointer, len/cap/elem_size, elem_kind, layout pointer.
        let size = std::mem::size_of::<HewVec>();
        let align = std::mem::align_of::<HewVec>();
        // Must be pointer-aligned for C interop.
        assert_eq!(align, std::mem::align_of::<*mut u8>());
        assert!(
            size > 5 * std::mem::size_of::<usize>(),
            "HewVec too small: {size}"
        );
    }

    #[test]
    fn hwvec_to_u8_rejects_null_pointer() {
        // SAFETY: this test intentionally exercises the null-pointer panic path.
        let panic = std::panic::catch_unwind(|| unsafe {
            let _ = hwvec_to_u8(std::ptr::null_mut());
        })
        .expect_err("null vectors must panic");
        let message = panic
            .downcast_ref::<String>()
            .map(String::as_str)
            .or_else(|| panic.downcast_ref::<&str>().copied())
            .unwrap_or("<non-string panic>");
        assert!(message.contains("null HewVec pointer"));
    }

    #[test]
    fn hwvec_to_u8_rejects_non_byte_shape() {
        // SAFETY: layout is null so layout_storage is never read.
        let mut vec = unsafe {
            HewVec {
                data: std::ptr::null_mut(),
                len: 0,
                cap: 0,
                elem_size: mem::size_of::<i64>(),
                elem_kind: ElemKind::Plain,
                layout: std::ptr::null(),
                layout_storage: core::mem::zeroed(),
            }
        };
        let vec_ptr = &raw mut vec;
        // SAFETY: this test intentionally exercises the invalid-shape panic path.
        let panic = std::panic::catch_unwind(move || unsafe {
            let _ = hwvec_to_u8(vec_ptr);
        })
        .expect_err("non-byte vectors must panic");
        let message = panic
            .downcast_ref::<String>()
            .map(String::as_str)
            .or_else(|| panic.downcast_ref::<&str>().copied())
            .unwrap_or("<non-string panic>");
        assert!(message.contains("expected elem_size"));
    }

    // ── try_hwvec_to_u8 (non-panicking variant) ─────────────────────────

    #[test]
    fn try_hwvec_to_u8_returns_none_for_null() {
        // SAFETY: null is the explicitly tested path.
        let result = unsafe { try_hwvec_to_u8(std::ptr::null_mut()) };
        assert!(result.is_none(), "null pointer must return None");
    }

    #[test]
    fn try_hwvec_to_u8_returns_none_for_wrong_elem_size() {
        // SAFETY: layout is null so layout_storage is never read.
        let mut vec = unsafe {
            HewVec {
                data: std::ptr::null_mut(),
                len: 0,
                cap: 0,
                elem_size: mem::size_of::<i64>(), // i64, not i32
                elem_kind: ElemKind::Plain,
                layout: std::ptr::null(),
                layout_storage: core::mem::zeroed(),
            }
        };
        let vec_ptr = &raw mut vec;
        // SAFETY: vec is a valid live HewVec on the stack.
        let result = unsafe { try_hwvec_to_u8(vec_ptr) };
        assert!(result.is_none(), "wrong elem_size must return None");
    }

    #[test]
    fn try_hwvec_to_u8_returns_none_for_wrong_elem_kind() {
        // SAFETY: layout is null so layout_storage is never read.
        let mut vec = unsafe {
            HewVec {
                data: std::ptr::null_mut(),
                len: 0,
                cap: 0,
                elem_size: mem::size_of::<i32>(),
                elem_kind: ElemKind::String, // not Plain
                layout: std::ptr::null(),
                layout_storage: core::mem::zeroed(),
            }
        };
        let vec_ptr = &raw mut vec;
        // SAFETY: vec is a valid live HewVec on the stack.
        let result = unsafe { try_hwvec_to_u8(vec_ptr) };
        assert!(result.is_none(), "non-Plain elem_kind must return None");
    }

    #[test]
    fn try_hwvec_to_u8_returns_some_for_empty_valid_vec() {
        // SAFETY: layout is null so layout_storage is never read; empty vec
        // so `data` is never dereferenced.
        let mut vec = unsafe {
            HewVec {
                data: std::ptr::null_mut(),
                len: 0,
                cap: 0,
                elem_size: mem::size_of::<i32>(),
                elem_kind: ElemKind::Plain,
                layout: std::ptr::null(),
                layout_storage: core::mem::zeroed(),
            }
        };
        let vec_ptr = &raw mut vec;
        // SAFETY: vec is a valid live HewVec on the stack.
        let result = unsafe { try_hwvec_to_u8(vec_ptr) };
        assert_eq!(
            result,
            Some(vec![]),
            "empty plain HewVec must return Some([])"
        );
    }

    #[cfg(target_pointer_width = "64")]
    #[test]
    fn try_hwvec_to_u8_returns_none_for_negative_length() {
        // The test-only length export converts the platform-sized `len` to
        // i64, making this malformed header report -1. Rejection happens before
        // the null data pointer can be inspected.
        // SAFETY: layout is null so layout_storage is never read.
        let mut vec = unsafe {
            HewVec {
                data: std::ptr::null_mut(),
                len: usize::MAX,
                cap: usize::MAX,
                elem_size: mem::size_of::<i32>(),
                elem_kind: ElemKind::Plain,
                layout: std::ptr::null(),
                layout_storage: core::mem::zeroed(),
            }
        };
        let vec_ptr = &raw mut vec;
        // SAFETY: the test passes a live header and asserts the malformed
        // signed length is rejected before any element access.
        let result = unsafe { try_hwvec_to_u8(vec_ptr) };
        assert!(result.is_none(), "negative length must return None");
    }
}
