//! Embed the standard library's sources in the browser package.
//!
//! Module resolution reads `.hew` sources through filesystem paths, and the
//! browser has no filesystem, so a program importing a `std` module could not
//! be compiled there. The frontend already accepts a document set that stands
//! in for files the filesystem does not have; this generates that set from the
//! shipped sources so the browser resolves the same standard library the
//! native compiler does.
//!
//! The list is generated rather than written by hand so a new standard-library
//! module cannot silently go missing from the browser.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    let std_root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("the crate has a workspace parent")
        .join("std");
    println!("cargo:rerun-if-changed={}", std_root.display());

    let mut sources = BTreeMap::new();
    collect(&std_root, &std_root, &mut sources);

    let mut out = String::from(
        "// Generated by build.rs from the shipped standard library. Do not edit.\n\
         pub const STD_SOURCES: &[(&str, &str)] = &[\n",
    );
    for (relative, path) in sources {
        println!("cargo:rerun-if-changed={}", path.display());
        writeln!(
            out,
            "    (\"./std/{relative}\", include_str!(r\"{}\")),",
            path.display()
        )
        .expect("writing to a String cannot fail");
    }
    out.push_str("];\n");

    let dest = PathBuf::from(std::env::var_os("OUT_DIR").expect("OUT_DIR")).join("std_sources.rs");
    std::fs::write(&dest, out).expect("write the embedded standard library");
}

fn collect(root: &Path, dir: &Path, sources: &mut BTreeMap<String, PathBuf>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect(root, &path, sources);
        } else if path.extension().is_some_and(|extension| extension == "hew") {
            let relative = path
                .strip_prefix(root)
                .expect("a collected path is under the standard library root")
                .to_string_lossy()
                .replace('\\', "/");
            sources.insert(relative, path);
        }
    }
}
