//===- msgpack_reader_gen.cpp - GENERATED - Deserialize msgpack AST --------===//
//
// AUTO-GENERATED by hew-astgen from hew-parser/src/ast.rs
// DO NOT EDIT - changes will be overwritten.
//
//===----------------------------------------------------------------------===//
// clang-format off

#include "hew/msgpack_reader.h"

#include <msgpack.hpp>

#include <cassert>
#include <stdexcept>
#include <string>
#include <string_view>
#include <type_traits>
#include <utility>

namespace hew {

// ── Error helper ────────────────────────────────────────────────────────────

[[noreturn]] static void fail(const std::string &msg) {
  throw std::runtime_error("msgpack AST parse error: " + msg);
}

// ── msgpack object helpers ──────────────────────────────────────────────────

/// Get a string from a msgpack object.
static std::string getString(const msgpack::object &obj) {
  if (obj.type != msgpack::type::STR)
    fail("expected string, got type " + std::to_string(obj.type));
  return std::string(obj.via.str.ptr, obj.via.str.size);
}

/// Get integer from msgpack object.
static int64_t getInt(const msgpack::object &obj) {
  if (obj.type == msgpack::type::POSITIVE_INTEGER) {
    if (obj.via.u64 > static_cast<uint64_t>(INT64_MAX))
      fail("unsigned value " + std::to_string(obj.via.u64) + " overflows int64_t");
    return static_cast<int64_t>(obj.via.u64);
  }
  if (obj.type == msgpack::type::NEGATIVE_INTEGER)
    return obj.via.i64;
  fail("expected integer, got type " + std::to_string(obj.type));
}

/// Get unsigned integer from msgpack object.
static uint64_t getUint(const msgpack::object &obj) {
  if (obj.type == msgpack::type::POSITIVE_INTEGER)
    return obj.via.u64;
  if (obj.type == msgpack::type::NEGATIVE_INTEGER)
    fail("negative value " + std::to_string(obj.via.i64) + " cannot be converted to uint64_t");
  fail("expected unsigned integer, got type " + std::to_string(obj.type));
}

/// Get float from msgpack object.
static double getFloat(const msgpack::object &obj) {
  if (obj.type == msgpack::type::FLOAT32 || obj.type == msgpack::type::FLOAT64)
    return obj.via.f64;
  if (obj.type == msgpack::type::POSITIVE_INTEGER)
    return static_cast<double>(obj.via.u64);
  if (obj.type == msgpack::type::NEGATIVE_INTEGER)
    return static_cast<double>(obj.via.i64);
  fail("expected float, got type " + std::to_string(obj.type));
}

/// Get bool from msgpack object.
static bool getBool(const msgpack::object &obj) {
  if (obj.type == msgpack::type::BOOLEAN)
    return obj.via.boolean;
  fail("expected bool, got type " + std::to_string(obj.type));
}

/// Parse a Visibility enum from a msgpack object (string variant name).
static ast::Visibility parseVisibility(const msgpack::object &obj) {
  auto s = getString(obj);
  if (s == "Pub")
    return ast::Visibility::Pub;
  if (s == "PubPackage")
    return ast::Visibility::PubPackage;
  if (s == "PubSuper")
    return ast::Visibility::PubSuper;
  if (s == "Private")
    return ast::Visibility::Private;
  fail("unknown Visibility variant: " + s);
}

/// Check if msgpack object is nil.
static bool isNil(const msgpack::object &obj) {
  return obj.type == msgpack::type::NIL;
}

/// Interpret a msgpack object as a map and find a key.
/// Returns nullptr if not found.
static const msgpack::object *mapGet(const msgpack::object &obj, std::string_view key) {
  if (obj.type != msgpack::type::MAP)
    fail("expected map, got type " + std::to_string(obj.type));
  for (uint32_t i = 0; i < obj.via.map.size; ++i) {
    const auto &kv = obj.via.map.ptr[i];
    if (kv.key.type == msgpack::type::STR &&
        std::string_view(kv.key.via.str.ptr, kv.key.via.str.size) == key)
      return &kv.val;
  }
  return nullptr;
}

/// Interpret a msgpack object as a map and get a required key.
static const msgpack::object &mapReq(const msgpack::object &obj, std::string_view key) {
  const auto *v = mapGet(obj, key);
  if (!v)
    fail("missing required key: " + std::string(key));
  return *v;
}

/// Get a map as an array of key-value pairs.
static const msgpack::object_kv *mapEntries(const msgpack::object &obj, uint32_t &size) {
  if (obj.type != msgpack::type::MAP)
    fail("expected map, got type " + std::to_string(obj.type));
  size = obj.via.map.size;
  return obj.via.map.ptr;
}

/// Get an array from a msgpack object.
static const msgpack::object *arrayData(const msgpack::object &obj, uint32_t &size) {
  if (obj.type != msgpack::type::ARRAY)
    fail("expected array, got type " + std::to_string(obj.type));
  size = obj.via.array.size;
  return obj.via.array.ptr;
}

/// Get the variant name from an externally-tagged enum.
/// Returns the variant name and a pointer to the payload.
/// For unit variants (encoded as bare string), payload is nullptr.
static std::pair<std::string, const msgpack::object *> getEnumVariant(const msgpack::object &obj) {
  // Unit variant: encoded as a bare string
  if (obj.type == msgpack::type::STR)
    return {getString(obj), nullptr};
  // Map with single entry: {"VariantName": payload}
  if (obj.type == msgpack::type::MAP && obj.via.map.size == 1) {
    const auto &kv = obj.via.map.ptr[0];
    return {getString(kv.key), &kv.val};
  }
  fail("expected enum variant (string or single-entry map), got type " + std::to_string(obj.type));
}

/// Exact schema version this reader understands. The embedded Rust→C++
/// boundary is internal to the current `hew` binary, so missing or
/// mismatched versions are rejected rather than carrying compatibility
/// fallbacks for older payloads.
constexpr uint32_t CURRENT_SCHEMA_VERSION = 6;

// ── Forward declarations ────────────────────────────────────────────────────

static ast::Expr parseExpr(const msgpack::object &obj);
static ast::Stmt parseStmt(const msgpack::object &obj);
static ast::Block parseBlock(const msgpack::object &obj);
static ast::TypeExpr parseTypeExpr(const msgpack::object &obj);
static ast::Pattern parsePattern(const msgpack::object &obj);
static ast::FnDecl parseFnDecl(const msgpack::object &obj);


// ── Forward declarations for special-cased parsers ──────────────────────────

static ast::AttributeArg parseAttributeArg(const msgpack::object &obj);
static ast::Attribute parseAttribute(const msgpack::object &obj);
static ast::TypeDecl parseTypeDecl(const msgpack::object &obj);
static ast::ModuleId parseModuleId(const msgpack::object &obj);
static ast::ModuleImport parseModuleImport(const msgpack::object &obj);
static ast::Module parseModule(const msgpack::object &obj);
static ast::VariantDecl parseVariantDecl(const msgpack::object &obj);
static ast::TraitItem parseTraitItem(const msgpack::object &obj);
static ast::MatchArm parseMatchArm(const msgpack::object &obj);
static ast::SelectArm parseSelectArm(const msgpack::object &obj);
static ast::ElseBlock parseElseBlock(const msgpack::object &obj);
static ast::MachineTransition parseMachineTransition(const msgpack::object &obj);
static ast::ChildSpec parseChildSpec(const msgpack::object &obj);
static ast::ReceiveFnDecl parseReceiveFnDecl(const msgpack::object &obj);
static ast::TypeParam parseTypeParam(const msgpack::object &obj);
static ast::NamingCase parseNamingCase(const msgpack::object &obj);
static ast::WireMetadata parseWireMetadata(const msgpack::object &obj);


// ── Span / Spanned ──────────────────────────────────────────────────────────

static ast::Span parseSpan(const msgpack::object &obj) {
  // Rust Range<usize> serializes as {"start": N, "end": N}
  return {getUint(mapReq(obj, "start")), getUint(mapReq(obj, "end"))};
}

template <typename T, typename ParseFn>
static ast::Spanned<T> parseSpanned(const msgpack::object &obj, ParseFn parseFn) {
  // Spanned<T> = (T, Span) → [T_value, span_map]
  uint32_t size;
  const auto *arr = arrayData(obj, size);
  if (size != 2)
    fail("Spanned tuple should have 2 elements");
  ast::Spanned<T> result{parseFn(arr[0]), parseSpan(arr[1])};
  // Copy span into inner type for codegen convenience (Expr/Stmt have span field)
  if constexpr (std::is_same_v<T, ast::Expr> || std::is_same_v<T, ast::Stmt>) {
    result.value.span = result.span;
  }
  return result;
}

/// Parse a Spanned<T> and wrap in unique_ptr (for forward-declared T).
template <typename T, typename ParseFn>
static std::unique_ptr<ast::Spanned<T>> parseSpannedPtr(const msgpack::object &obj,
                                                        ParseFn parseFn) {
  return std::make_unique<ast::Spanned<T>>(parseSpanned<T>(obj, parseFn));
}

// ── Optional helpers ────────────────────────────────────────────────────────

template <typename T, typename ParseFn>
static std::optional<T> parseOptional(const msgpack::object &obj, ParseFn parseFn) {
  if (isNil(obj))
    return std::nullopt;
  return parseFn(obj);
}

template <typename T, typename ParseFn>
static std::vector<T> parseVec(const msgpack::object &obj, ParseFn parseFn) {
  uint32_t size;
  const auto *arr = arrayData(obj, size);
  std::vector<T> result;
  result.reserve(size);
  for (uint32_t i = 0; i < size; ++i)
    result.push_back(parseFn(arr[i]));
  return result;
}

template <typename T, typename ParseFn>
static std::vector<T> parseOptVec(const msgpack::object &obj, ParseFn parseFn) {
  if (isNil(obj))
    return {};
  return parseVec<T>(obj, parseFn);
}

/// Parse a vector of unique_ptr<T> from a msgpack array.
template <typename T, typename ParseFn>
static std::vector<std::unique_ptr<T>> parseVecPtr(const msgpack::object &obj, ParseFn parseFn) {
  uint32_t size;
  const auto *arr = arrayData(obj, size);
  std::vector<std::unique_ptr<T>> result;
  result.reserve(size);
  for (uint32_t i = 0; i < size; ++i)
    result.push_back(std::make_unique<T>(parseFn(arr[i])));
  return result;
}

// ── Literals ────────────────────────────────────────────────────────────────

static ast::Literal parseLiteral(const msgpack::object &obj) {
  auto [name, payload] = getEnumVariant(obj);
  if (name == "Integer")
    return ast::LitInteger{getInt(*payload)};
  if (name == "Float")
    return ast::LitFloat{getFloat(*payload)};
  if (name == "String")
    return ast::LitString{getString(*payload)};
  if (name == "Bool")
    return ast::LitBool{getBool(*payload)};
  if (name == "Char") {
    // Rust char serializes as a UTF-8 string — decode full codepoint
    auto s = getString(*payload);
    if (s.empty())
      return ast::LitChar{0};
    auto c = static_cast<unsigned char>(s[0]);
    char32_t cp;
    if (c < 0x80) {
      cp = c;
    } else if ((c >> 5) == 0x6 && s.size() >= 2) {
      cp = (char32_t(c & 0x1F) << 6) | (s[1] & 0x3F);
    } else if ((c >> 4) == 0xE && s.size() >= 3) {
      cp = (char32_t(c & 0x0F) << 12) | (char32_t(s[1] & 0x3F) << 6) | (s[2] & 0x3F);
    } else if ((c >> 3) == 0x1E && s.size() >= 4) {
      cp = (char32_t(c & 0x07) << 18) | (char32_t(s[1] & 0x3F) << 12) |
           (char32_t(s[2] & 0x3F) << 6) | (s[3] & 0x3F);
    } else {
      cp = c; // fallback to raw byte
    }
    return ast::LitChar{cp};
  }
  if (name == "Duration")
    return ast::LitDuration{getInt(*payload)};
  fail("unknown Literal variant: " + name);
}

static ast::Param parseParam(const msgpack::object &obj) {
  ast::Param result;
  result.name = getString(mapReq(obj, "name"));
  result.ty = parseSpanned<ast::TypeExpr>(mapReq(obj, "ty"), parseTypeExpr);
  result.is_mutable = getBool(mapReq(obj, "is_mutable"));
  return result;
}

static ast::ActorInit parseActorInit(const msgpack::object &obj) {
  ast::ActorInit result;
  result.params = parseVec<ast::Param>(mapReq(obj, "params"), parseParam);
  result.body = parseBlock(mapReq(obj, "body"));
  return result;
}

static ast::ActorTerminate parseActorTerminate(const msgpack::object &obj) {
  ast::ActorTerminate result;
  result.body = parseBlock(mapReq(obj, "body"));
  return result;
}

static ast::FieldDecl parseFieldDecl(const msgpack::object &obj) {
  ast::FieldDecl result;
  result.name = getString(mapReq(obj, "name"));
  result.ty = parseSpanned<ast::TypeExpr>(mapReq(obj, "ty"), parseTypeExpr);
  return result;
}

static ast::OverflowFallback parseOverflowFallback(const msgpack::object &obj) {
  auto s = getString(obj);
  if (s == "DropNew") return ast::OverflowFallback::DropNew;
  if (s == "DropOld") return ast::OverflowFallback::DropOld;
  if (s == "Block") return ast::OverflowFallback::Block;
  if (s == "Fail") return ast::OverflowFallback::Fail;
  fail("unknown OverflowFallback: " + s);
}

static ast::OverflowPolicy parseOverflowPolicy(const msgpack::object &obj) {
  auto [name, payload] = getEnumVariant(obj);

  if (name == "DropNew") return ast::OverflowPolicy{ast::OverflowDropNew{}};
  if (name == "DropOld") return ast::OverflowPolicy{ast::OverflowDropOld{}};
  if (name == "Block") return ast::OverflowPolicy{ast::OverflowBlock{}};
  if (name == "Fail") return ast::OverflowPolicy{ast::OverflowFail{}};
  if (name == "Coalesce") {
    ast::OverflowCoalesce e;
    e.key_field = getString(mapReq(*payload, "key_field"));
    const auto *fallback = mapGet(*payload, "fallback");
    if (fallback && !isNil(*fallback))
      e.fallback = parseOverflowFallback(*fallback);
    return ast::OverflowPolicy{std::move(e)};
  }
  fail("unknown OverflowPolicy variant: " + name);
}

static ast::TraitBound parseTraitBound(const msgpack::object &obj) {
  ast::TraitBound result;
  result.name = getString(mapReq(obj, "name"));
  const auto *type_args = mapGet(obj, "type_args");
  if (type_args && !isNil(*type_args))
    result.type_args = parseVec<ast::Spanned<ast::TypeExpr>>(*type_args, [](const msgpack::object &o) { return parseSpanned<ast::TypeExpr>(o, parseTypeExpr); });
  return result;
}

static ast::TypeParam parseTypeParam(const msgpack::object &obj) {
  ast::TypeParam result;
  result.name = getString(mapReq(obj, "name"));
  result.bounds = parseVec<ast::TraitBound>(mapReq(obj, "bounds"), parseTraitBound);
  return result;
}

static ast::WherePredicate parseWherePredicate(const msgpack::object &obj) {
  ast::WherePredicate result;
  result.ty = parseSpanned<ast::TypeExpr>(mapReq(obj, "ty"), parseTypeExpr);
  result.bounds = parseVec<ast::TraitBound>(mapReq(obj, "bounds"), parseTraitBound);
  return result;
}

static ast::WhereClause parseWhereClause(const msgpack::object &obj) {
  ast::WhereClause result;
  result.predicates = parseVec<ast::WherePredicate>(mapReq(obj, "predicates"), parseWherePredicate);
  return result;
}

static ast::ActorDecl parseActorDecl(const msgpack::object &obj) {
  ast::ActorDecl result;
  const auto *visibility_ = mapGet(obj, "visibility");
  if (visibility_ && !isNil(*visibility_))
    result.visibility = parseVisibility(*visibility_);
  result.name = getString(mapReq(obj, "name"));
  const auto *super_traits = mapGet(obj, "super_traits");
  if (super_traits && !isNil(*super_traits))
    result.super_traits = parseVec<ast::TraitBound>(*super_traits, parseTraitBound);
  const auto *init = mapGet(obj, "init");
  if (init && !isNil(*init))
    result.init = parseActorInit(*init);
  const auto *terminate = mapGet(obj, "terminate");
  if (terminate && !isNil(*terminate))
    result.terminate = parseActorTerminate(*terminate);
  result.fields = parseVec<ast::FieldDecl>(mapReq(obj, "fields"), parseFieldDecl);
  result.receive_fns = parseVec<ast::ReceiveFnDecl>(mapReq(obj, "receive_fns"), parseReceiveFnDecl);
  result.methods = parseVec<ast::FnDecl>(mapReq(obj, "methods"), parseFnDecl);
  const auto *mailbox_capacity = mapGet(obj, "mailbox_capacity");
  if (mailbox_capacity && !isNil(*mailbox_capacity))
    result.mailbox_capacity = static_cast<uint32_t>(getUint(*mailbox_capacity));
  const auto *overflow_policy = mapGet(obj, "overflow_policy");
  if (overflow_policy && !isNil(*overflow_policy))
    result.overflow_policy = parseOverflowPolicy(*overflow_policy);
  result.is_isolated = getBool(mapReq(obj, "is_isolated"));
  const auto *doc_comment = mapGet(obj, "doc_comment");
  if (doc_comment && !isNil(*doc_comment))
    result.doc_comment = getString(*doc_comment);
  return result;
}

static ast::ConstDecl parseConstDecl(const msgpack::object &obj) {
  ast::ConstDecl result;
  const auto *visibility_ = mapGet(obj, "visibility");
  if (visibility_ && !isNil(*visibility_))
    result.visibility = parseVisibility(*visibility_);
  result.name = getString(mapReq(obj, "name"));
  result.ty = parseSpanned<ast::TypeExpr>(mapReq(obj, "ty"), parseTypeExpr);
  result.value = parseSpanned<ast::Expr>(mapReq(obj, "value"), parseExpr);
  return result;
}

static ast::ExternFnDecl parseExternFnDecl(const msgpack::object &obj) {
  ast::ExternFnDecl result;
  result.name = getString(mapReq(obj, "name"));
  result.params = parseVec<ast::Param>(mapReq(obj, "params"), parseParam);
  const auto *return_type = mapGet(obj, "return_type");
  if (return_type && !isNil(*return_type))
    result.return_type = parseSpanned<ast::TypeExpr>(*return_type, parseTypeExpr);
  result.is_variadic = getBool(mapReq(obj, "is_variadic"));
  return result;
}

static ast::ExternBlock parseExternBlock(const msgpack::object &obj) {
  ast::ExternBlock result;
  result.abi = getString(mapReq(obj, "abi"));
  result.functions = parseVec<ast::ExternFnDecl>(mapReq(obj, "functions"), parseExternFnDecl);
  return result;
}

static ast::ImplTypeAlias parseImplTypeAlias(const msgpack::object &obj) {
  ast::ImplTypeAlias result;
  result.name = getString(mapReq(obj, "name"));
  result.ty = parseSpanned<ast::TypeExpr>(mapReq(obj, "ty"), parseTypeExpr);
  return result;
}

static ast::ImplDecl parseImplDecl(const msgpack::object &obj) {
  ast::ImplDecl result;
  const auto *type_params = mapGet(obj, "type_params");
  if (type_params && !isNil(*type_params))
    result.type_params = parseVec<ast::TypeParam>(*type_params, parseTypeParam);
  const auto *trait_bound = mapGet(obj, "trait_bound");
  if (trait_bound && !isNil(*trait_bound))
    result.trait_bound = parseTraitBound(*trait_bound);
  result.target_type = parseSpanned<ast::TypeExpr>(mapReq(obj, "target_type"), parseTypeExpr);
  const auto *where_clause = mapGet(obj, "where_clause");
  if (where_clause && !isNil(*where_clause))
    result.where_clause = parseWhereClause(*where_clause);
  const auto *type_aliases_ = mapGet(obj, "type_aliases");
  if (type_aliases_ && !isNil(*type_aliases_))
    result.type_aliases = parseVec<ast::ImplTypeAlias>(*type_aliases_, parseImplTypeAlias);
  result.methods = parseVec<ast::FnDecl>(mapReq(obj, "methods"), parseFnDecl);
  return result;
}

static ast::ImportName parseImportName(const msgpack::object &obj) {
  ast::ImportName result;
  result.name = getString(mapReq(obj, "name"));
  const auto *alias = mapGet(obj, "alias");
  if (alias && !isNil(*alias))
    result.alias = getString(*alias);
  return result;
}

static ast::ImportSpec parseImportSpec(const msgpack::object &obj) {
  auto [name, payload] = getEnumVariant(obj);

  if (name == "Glob") return ast::ImportSpec{ast::ImportSpecGlob{}};
  if (name == "Names") return ast::ImportSpec{ast::ImportSpecNames{parseVec<ast::ImportName>(*payload, parseImportName)}};
  fail("unknown ImportSpec variant: " + name);
}

static ast::ImportDecl parseImportDecl(const msgpack::object &obj) {
  ast::ImportDecl result;
  result.path = parseVec<std::string>(mapReq(obj, "path"), [](const msgpack::object &o) { return getString(o); });
  const auto *spec = mapGet(obj, "spec");
  if (spec && !isNil(*spec))
    result.spec = parseImportSpec(*spec);
  const auto *file_path = mapGet(obj, "file_path");
  if (file_path && !isNil(*file_path))
    result.file_path = getString(*file_path);
  return result;
}

static ast::MachineEvent parseMachineEvent(const msgpack::object &obj) {
  ast::MachineEvent result;
  result.name = getString(mapReq(obj, "name"));
  result.fields = parseVec<std::pair<std::string, ast::Spanned<ast::TypeExpr>>>(mapReq(obj, "fields"), [](const msgpack::object &o) { uint32_t sz; const auto *arr = arrayData(o, sz); if (sz != 2) fail("tuple should have 2 elements"); return std::make_pair(getString(arr[0]), parseSpanned<ast::TypeExpr>(arr[1], parseTypeExpr)); });
  return result;
}

static ast::MachineState parseMachineState(const msgpack::object &obj) {
  ast::MachineState result;
  result.name = getString(mapReq(obj, "name"));
  result.fields = parseVec<std::pair<std::string, ast::Spanned<ast::TypeExpr>>>(mapReq(obj, "fields"), [](const msgpack::object &o) { uint32_t sz; const auto *arr = arrayData(o, sz); if (sz != 2) fail("tuple should have 2 elements"); return std::make_pair(getString(arr[0]), parseSpanned<ast::TypeExpr>(arr[1], parseTypeExpr)); });
  return result;
}

static ast::MachineDecl parseMachineDecl(const msgpack::object &obj) {
  ast::MachineDecl result;
  const auto *visibility_ = mapGet(obj, "visibility");
  if (visibility_ && !isNil(*visibility_))
    result.visibility = parseVisibility(*visibility_);
  result.name = getString(mapReq(obj, "name"));
  result.states = parseVec<ast::MachineState>(mapReq(obj, "states"), parseMachineState);
  result.events = parseVec<ast::MachineEvent>(mapReq(obj, "events"), parseMachineEvent);
  result.transitions = parseVec<ast::MachineTransition>(mapReq(obj, "transitions"), parseMachineTransition);
  const auto *has_default_ = mapGet(obj, "has_default");
  if (has_default_ && !isNil(*has_default_))
    result.has_default = getBool(*has_default_);
  return result;
}

static ast::RestartPolicy parseRestartPolicy(const msgpack::object &obj) {
  auto s = getString(obj);
  if (s == "Permanent") return ast::RestartPolicy::Permanent;
  if (s == "Transient") return ast::RestartPolicy::Transient;
  if (s == "Temporary") return ast::RestartPolicy::Temporary;
  fail("unknown RestartPolicy: " + s);
}

static ast::SupervisorStrategy parseSupervisorStrategy(const msgpack::object &obj) {
  auto s = getString(obj);
  if (s == "OneForOne") return ast::SupervisorStrategy::OneForOne;
  if (s == "OneForAll") return ast::SupervisorStrategy::OneForAll;
  if (s == "RestForOne") return ast::SupervisorStrategy::RestForOne;
  fail("unknown SupervisorStrategy: " + s);
}

static ast::SupervisorDecl parseSupervisorDecl(const msgpack::object &obj) {
  ast::SupervisorDecl result;
  const auto *visibility_ = mapGet(obj, "visibility");
  if (visibility_ && !isNil(*visibility_))
    result.visibility = parseVisibility(*visibility_);
  result.name = getString(mapReq(obj, "name"));
  const auto *strategy = mapGet(obj, "strategy");
  if (strategy && !isNil(*strategy))
    result.strategy = parseSupervisorStrategy(*strategy);
  const auto *max_restarts = mapGet(obj, "max_restarts");
  if (max_restarts && !isNil(*max_restarts))
    result.max_restarts = getInt(*max_restarts);
  const auto *window = mapGet(obj, "window");
  if (window && !isNil(*window))
    result.window = getString(*window);
  result.children = parseVec<ast::ChildSpec>(mapReq(obj, "children"), parseChildSpec);
  return result;
}

static ast::TraitMethod parseTraitMethod(const msgpack::object &obj) {
  ast::TraitMethod result;
  result.name = getString(mapReq(obj, "name"));
  result.is_pure = getBool(mapReq(obj, "is_pure"));
  const auto *type_params = mapGet(obj, "type_params");
  if (type_params && !isNil(*type_params))
    result.type_params = parseVec<ast::TypeParam>(*type_params, parseTypeParam);
  result.params = parseVec<ast::Param>(mapReq(obj, "params"), parseParam);
  const auto *return_type = mapGet(obj, "return_type");
  if (return_type && !isNil(*return_type))
    result.return_type = parseSpanned<ast::TypeExpr>(*return_type, parseTypeExpr);
  const auto *where_clause = mapGet(obj, "where_clause");
  if (where_clause && !isNil(*where_clause))
    result.where_clause = parseWhereClause(*where_clause);
  const auto *body = mapGet(obj, "body");
  if (body && !isNil(*body))
    result.body = parseBlock(*body);
  return result;
}

static ast::TraitDecl parseTraitDecl(const msgpack::object &obj) {
  ast::TraitDecl result;
  const auto *visibility_ = mapGet(obj, "visibility");
  if (visibility_ && !isNil(*visibility_))
    result.visibility = parseVisibility(*visibility_);
  result.name = getString(mapReq(obj, "name"));
  const auto *type_params = mapGet(obj, "type_params");
  if (type_params && !isNil(*type_params))
    result.type_params = parseVec<ast::TypeParam>(*type_params, parseTypeParam);
  const auto *super_traits = mapGet(obj, "super_traits");
  if (super_traits && !isNil(*super_traits))
    result.super_traits = parseVec<ast::TraitBound>(*super_traits, parseTraitBound);
  result.items = parseVec<ast::TraitItem>(mapReq(obj, "items"), parseTraitItem);
  const auto *doc_comment = mapGet(obj, "doc_comment");
  if (doc_comment && !isNil(*doc_comment))
    result.doc_comment = getString(*doc_comment);
  return result;
}

static ast::TypeAliasDecl parseTypeAliasDecl(const msgpack::object &obj) {
  ast::TypeAliasDecl result;
  const auto *visibility_ = mapGet(obj, "visibility");
  if (visibility_ && !isNil(*visibility_))
    result.visibility = parseVisibility(*visibility_);
  result.name = getString(mapReq(obj, "name"));
  result.ty = parseSpanned<ast::TypeExpr>(mapReq(obj, "ty"), parseTypeExpr);
  return result;
}

static ast::TypeDeclKind parseTypeDeclKind(const msgpack::object &obj) {
  auto s = getString(obj);
  if (s == "Struct") return ast::TypeDeclKind::Struct;
  if (s == "Enum") return ast::TypeDeclKind::Enum;
  fail("unknown TypeDeclKind: " + s);
}

static ast::NamingCase parseNamingCase(const msgpack::object &obj) {
  auto s = getString(obj);
  if (s == "CamelCase") return ast::NamingCase::CamelCase;
  if (s == "PascalCase") return ast::NamingCase::PascalCase;
  if (s == "SnakeCase") return ast::NamingCase::SnakeCase;
  if (s == "ScreamingSnake") return ast::NamingCase::ScreamingSnake;
  if (s == "KebabCase") return ast::NamingCase::KebabCase;
  fail("unknown NamingCase: " + s);
}

static ast::WireFieldMeta parseWireFieldMeta(const msgpack::object &obj) {
  ast::WireFieldMeta result;
  result.field_name = getString(mapReq(obj, "field_name"));
  result.field_number = static_cast<uint32_t>(getUint(mapReq(obj, "field_number")));
  result.is_optional = getBool(mapReq(obj, "is_optional"));
  result.is_deprecated = getBool(mapReq(obj, "is_deprecated"));
  result.is_repeated = getBool(mapReq(obj, "is_repeated"));
  const auto *json_name = mapGet(obj, "json_name");
  if (json_name && !isNil(*json_name))
    result.json_name = getString(*json_name);
  const auto *yaml_name = mapGet(obj, "yaml_name");
  if (yaml_name && !isNil(*yaml_name))
    result.yaml_name = getString(*yaml_name);
  const auto *since = mapGet(obj, "since");
  if (since && !isNil(*since))
    result.since = static_cast<uint32_t>(getUint(*since));
  return result;
}

static ast::WireMetadata parseWireMetadata(const msgpack::object &obj) {
  ast::WireMetadata result;
  result.field_meta = parseVec<ast::WireFieldMeta>(mapReq(obj, "field_meta"), parseWireFieldMeta);
  result.reserved_numbers = parseVec<uint32_t>(mapReq(obj, "reserved_numbers"), [](const msgpack::object &o) { return static_cast<uint32_t>(getUint(o)); });
  const auto *json_case = mapGet(obj, "json_case");
  if (json_case && !isNil(*json_case))
    result.json_case = parseNamingCase(*json_case);
  const auto *yaml_case = mapGet(obj, "yaml_case");
  if (yaml_case && !isNil(*yaml_case))
    result.yaml_case = parseNamingCase(*yaml_case);
  const auto *version = mapGet(obj, "version");
  if (version && !isNil(*version))
    result.version = static_cast<uint32_t>(getUint(*version));
  const auto *min_version = mapGet(obj, "min_version");
  if (min_version && !isNil(*min_version))
    result.min_version = static_cast<uint32_t>(getUint(*min_version));
  return result;
}

static ast::WireDeclKind parseWireDeclKind(const msgpack::object &obj) {
  auto s = getString(obj);
  if (s == "Struct") return ast::WireDeclKind::Struct;
  if (s == "Enum") return ast::WireDeclKind::Enum;
  fail("unknown WireDeclKind: " + s);
}

static ast::WireFieldDecl parseWireFieldDecl(const msgpack::object &obj) {
  ast::WireFieldDecl result;
  result.name = getString(mapReq(obj, "name"));
  result.ty = getString(mapReq(obj, "ty"));
  result.field_number = static_cast<uint32_t>(getUint(mapReq(obj, "field_number")));
  result.is_optional = getBool(mapReq(obj, "is_optional"));
  result.is_repeated = getBool(mapReq(obj, "is_repeated"));
  result.is_reserved = getBool(mapReq(obj, "is_reserved"));
  result.is_deprecated = getBool(mapReq(obj, "is_deprecated"));
  const auto *json_name = mapGet(obj, "json_name");
  if (json_name && !isNil(*json_name))
    result.json_name = getString(*json_name);
  const auto *yaml_name = mapGet(obj, "yaml_name");
  if (yaml_name && !isNil(*yaml_name))
    result.yaml_name = getString(*yaml_name);
  const auto *since = mapGet(obj, "since");
  if (since && !isNil(*since))
    result.since = static_cast<uint32_t>(getUint(*since));
  return result;
}

static ast::WireDecl parseWireDecl(const msgpack::object &obj) {
  ast::WireDecl result;
  const auto *visibility_ = mapGet(obj, "visibility");
  if (visibility_ && !isNil(*visibility_))
    result.visibility = parseVisibility(*visibility_);
  result.kind = parseWireDeclKind(mapReq(obj, "kind"));
  result.name = getString(mapReq(obj, "name"));
  result.fields = parseVec<ast::WireFieldDecl>(mapReq(obj, "fields"), parseWireFieldDecl);
  result.variants = parseVec<ast::VariantDecl>(mapReq(obj, "variants"), parseVariantDecl);
  const auto *json_case = mapGet(obj, "json_case");
  if (json_case && !isNil(*json_case))
    result.json_case = parseNamingCase(*json_case);
  const auto *yaml_case = mapGet(obj, "yaml_case");
  if (yaml_case && !isNil(*yaml_case))
    result.yaml_case = parseNamingCase(*yaml_case);
  return result;
}

static ast::Item parseItem(const msgpack::object &obj) {
  auto [name, payload] = getEnumVariant(obj);

  if (name == "Import") return ast::Item{parseImportDecl(*payload)};
  if (name == "Const") return ast::Item{parseConstDecl(*payload)};
  if (name == "TypeDecl") return ast::Item{parseTypeDecl(*payload)};
  if (name == "TypeAlias") return ast::Item{parseTypeAliasDecl(*payload)};
  if (name == "Trait") return ast::Item{parseTraitDecl(*payload)};
  if (name == "Impl") return ast::Item{parseImplDecl(*payload)};
  if (name == "Wire") return ast::Item{parseWireDecl(*payload)};
  if (name == "Function") return ast::Item{parseFnDecl(*payload)};
  if (name == "ExternBlock") return ast::Item{parseExternBlock(*payload)};
  if (name == "Actor") return ast::Item{parseActorDecl(*payload)};
  if (name == "Supervisor") return ast::Item{parseSupervisorDecl(*payload)};
  if (name == "Machine") return ast::Item{parseMachineDecl(*payload)};
  fail("unknown Item variant: " + name);
}

static ast::StringPart parseStringPart(const msgpack::object &obj) {
  auto [name, payload] = getEnumVariant(obj);

  if (name == "Literal") return ast::StringPart{ast::StringPartLiteral{getString(*payload)}};
  if (name == "Expr") return ast::StringPart{ast::StringPartExpr{parseSpannedPtr<ast::Expr>(*payload, parseExpr)}};
  fail("unknown StringPart variant: " + name);
}

static ast::CallArg parseCallArg(const msgpack::object &obj) {
  auto [name, payload] = getEnumVariant(obj);

  if (name == "Positional") return ast::CallArg{ast::CallArgPositional{parseSpannedPtr<ast::Expr>(*payload, parseExpr)}};
  if (name == "Named") {
    ast::CallArgNamed e;
    e.name = getString(mapReq(*payload, "name"));
    e.value = parseSpannedPtr<ast::Expr>(mapReq(*payload, "value"), parseExpr);
    return ast::CallArg{std::move(e)};
  }
  fail("unknown CallArg variant: " + name);
}

static ast::BinaryOp parseBinaryOp(const msgpack::object &obj) {
  auto s = getString(obj);
  if (s == "Add") return ast::BinaryOp::Add;
  if (s == "Subtract") return ast::BinaryOp::Subtract;
  if (s == "Multiply") return ast::BinaryOp::Multiply;
  if (s == "Divide") return ast::BinaryOp::Divide;
  if (s == "Modulo") return ast::BinaryOp::Modulo;
  if (s == "Equal") return ast::BinaryOp::Equal;
  if (s == "NotEqual") return ast::BinaryOp::NotEqual;
  if (s == "Less") return ast::BinaryOp::Less;
  if (s == "LessEqual") return ast::BinaryOp::LessEqual;
  if (s == "Greater") return ast::BinaryOp::Greater;
  if (s == "GreaterEqual") return ast::BinaryOp::GreaterEqual;
  if (s == "And") return ast::BinaryOp::And;
  if (s == "Or") return ast::BinaryOp::Or;
  if (s == "BitAnd") return ast::BinaryOp::BitAnd;
  if (s == "BitOr") return ast::BinaryOp::BitOr;
  if (s == "BitXor") return ast::BinaryOp::BitXor;
  if (s == "Shl") return ast::BinaryOp::Shl;
  if (s == "Shr") return ast::BinaryOp::Shr;
  if (s == "Range") return ast::BinaryOp::Range;
  if (s == "RangeInclusive") return ast::BinaryOp::RangeInclusive;
  if (s == "Send") return ast::BinaryOp::Send;
  if (s == "RegexMatch") return ast::BinaryOp::RegexMatch;
  if (s == "RegexNotMatch") return ast::BinaryOp::RegexNotMatch;
  fail("unknown BinaryOp: " + s);
}

static ast::LambdaParam parseLambdaParam(const msgpack::object &obj) {
  ast::LambdaParam result;
  result.name = getString(mapReq(obj, "name"));
  const auto *ty = mapGet(obj, "ty");
  if (ty && !isNil(*ty))
    result.ty = parseSpanned<ast::TypeExpr>(*ty, parseTypeExpr);
  return result;
}

static ast::TimeoutClause parseTimeoutClause(const msgpack::object &obj) {
  ast::TimeoutClause result;
  result.duration = parseSpannedPtr<ast::Expr>(mapReq(obj, "duration"), parseExpr);
  result.body = parseSpannedPtr<ast::Expr>(mapReq(obj, "body"), parseExpr);
  return result;
}

static ast::UnaryOp parseUnaryOp(const msgpack::object &obj) {
  auto s = getString(obj);
  if (s == "Not") return ast::UnaryOp::Not;
  if (s == "Negate") return ast::UnaryOp::Negate;
  if (s == "BitNot") return ast::UnaryOp::BitNot;
  fail("unknown UnaryOp: " + s);
}

static ast::CompoundAssignOp parseCompoundAssignOp(const msgpack::object &obj) {
  auto s = getString(obj);
  if (s == "Add") return ast::CompoundAssignOp::Add;
  if (s == "Subtract") return ast::CompoundAssignOp::Subtract;
  if (s == "Multiply") return ast::CompoundAssignOp::Multiply;
  if (s == "Divide") return ast::CompoundAssignOp::Divide;
  if (s == "Modulo") return ast::CompoundAssignOp::Modulo;
  if (s == "BitAnd") return ast::CompoundAssignOp::BitAnd;
  if (s == "BitOr") return ast::CompoundAssignOp::BitOr;
  if (s == "BitXor") return ast::CompoundAssignOp::BitXor;
  if (s == "Shl") return ast::CompoundAssignOp::Shl;
  if (s == "Shr") return ast::CompoundAssignOp::Shr;
  fail("unknown CompoundAssignOp: " + s);
}

static ast::TypeExpr parseTypeExpr(const msgpack::object &obj) {
  auto [name, payload] = getEnumVariant(obj);

  if (name == "Named") {
    ast::TypeNamed e;
    e.name = getString(mapReq(*payload, "name"));
    const auto *type_args = mapGet(*payload, "type_args");
    if (type_args && !isNil(*type_args))
      e.type_args = parseVec<ast::Spanned<ast::TypeExpr>>(*type_args, [](const msgpack::object &o) { return parseSpanned<ast::TypeExpr>(o, parseTypeExpr); });
    return ast::TypeExpr{std::move(e)};
  }
  if (name == "Result") {
    ast::TypeResult e;
    e.ok = parseSpannedPtr<ast::TypeExpr>(mapReq(*payload, "ok"), parseTypeExpr);
    e.err = parseSpannedPtr<ast::TypeExpr>(mapReq(*payload, "err"), parseTypeExpr);
    return ast::TypeExpr{std::move(e)};
  }
  if (name == "Option") return ast::TypeExpr{ast::TypeOption{parseSpannedPtr<ast::TypeExpr>(*payload, parseTypeExpr)}};
  if (name == "Tuple") return ast::TypeExpr{ast::TypeTuple{parseVec<ast::Spanned<ast::TypeExpr>>(*payload, [](const msgpack::object &o) { return parseSpanned<ast::TypeExpr>(o, parseTypeExpr); })}};
  if (name == "Array") {
    ast::TypeArray e;
    e.element = parseSpannedPtr<ast::TypeExpr>(mapReq(*payload, "element"), parseTypeExpr);
    e.size = getUint(mapReq(*payload, "size"));
    return ast::TypeExpr{std::move(e)};
  }
  if (name == "Slice") return ast::TypeExpr{ast::TypeSlice{parseSpannedPtr<ast::TypeExpr>(*payload, parseTypeExpr)}};
  if (name == "Function") {
    ast::TypeFunction e;
    e.params = parseVec<ast::Spanned<ast::TypeExpr>>(mapReq(*payload, "params"), [](const msgpack::object &o) { return parseSpanned<ast::TypeExpr>(o, parseTypeExpr); });
    e.return_type = parseSpannedPtr<ast::TypeExpr>(mapReq(*payload, "return_type"), parseTypeExpr);
    return ast::TypeExpr{std::move(e)};
  }
  if (name == "Pointer") {
    ast::TypePointer e;
    e.is_mutable = getBool(mapReq(*payload, "is_mutable"));
    e.pointee = parseSpannedPtr<ast::TypeExpr>(mapReq(*payload, "pointee"), parseTypeExpr);
    return ast::TypeExpr{std::move(e)};
  }
  if (name == "TraitObject") return ast::TypeExpr{ast::TypeTraitObject{parseVec<ast::TraitBound>(*payload, parseTraitBound)}};
  if (name == "Infer") fail("TypeInfer (`_`) reached the wire: inference must be complete before serialization");
  fail("unknown TypeExpr variant: " + name);
}

static ast::PatternField parsePatternField(const msgpack::object &obj) {
  ast::PatternField result;
  result.name = getString(mapReq(obj, "name"));
  const auto *pattern = mapGet(obj, "pattern");
  if (pattern && !isNil(*pattern))
    result.pattern = parseSpannedPtr<ast::Pattern>(*pattern, parsePattern);
  return result;
}

static ast::Pattern parsePattern(const msgpack::object &obj) {
  auto [name, payload] = getEnumVariant(obj);

  if (name == "Wildcard") return ast::Pattern{ast::PatWildcard{}};
  if (name == "Literal") return ast::Pattern{ast::PatLiteral{parseLiteral(*payload)}};
  if (name == "Identifier") return ast::Pattern{ast::PatIdentifier{getString(*payload)}};
  if (name == "Constructor") {
    ast::PatConstructor e;
    e.name = getString(mapReq(*payload, "name"));
    e.patterns = parseVecPtr<ast::Spanned<ast::Pattern>>(mapReq(*payload, "patterns"), [](const msgpack::object &o) { return parseSpanned<ast::Pattern>(o, parsePattern); });
    return ast::Pattern{std::move(e)};
  }
  if (name == "Struct") {
    ast::PatStruct e;
    e.name = getString(mapReq(*payload, "name"));
    e.fields = parseVec<ast::PatternField>(mapReq(*payload, "fields"), parsePatternField);
    return ast::Pattern{std::move(e)};
  }
  if (name == "Tuple") return ast::Pattern{ast::PatTuple{parseVecPtr<ast::Spanned<ast::Pattern>>(*payload, [](const msgpack::object &o) { return parseSpanned<ast::Pattern>(o, parsePattern); })}};
  if (name == "Or") {
    uint32_t sz;
    const auto *arr = arrayData(*payload, sz);
    if (sz != 2) fail("Or expects 2 elements");
    ast::PatOr e;
    e.left = parseSpannedPtr<ast::Pattern>(arr[0], parsePattern);
    e.right = parseSpannedPtr<ast::Pattern>(arr[1], parsePattern);
    return ast::Pattern{std::move(e)};
  }
  fail("unknown Pattern variant: " + name);
}

static ast::Block parseBlock(const msgpack::object &obj) {
  ast::Block result;
  result.stmts = parseVecPtr<ast::Spanned<ast::Stmt>>(mapReq(obj, "stmts"), [](const msgpack::object &o) { return parseSpanned<ast::Stmt>(o, parseStmt); });
  const auto *trailing_expr = mapGet(obj, "trailing_expr");
  if (trailing_expr && !isNil(*trailing_expr))
    result.trailing_expr = parseSpannedPtr<ast::Expr>(*trailing_expr, parseExpr);
  return result;
}

static ast::FnDecl parseFnDecl(const msgpack::object &obj) {
  ast::FnDecl result;
  result.attributes = parseVec<ast::Attribute>(mapReq(obj, "attributes"), parseAttribute);
  result.is_async = getBool(mapReq(obj, "is_async"));
  result.is_generator = getBool(mapReq(obj, "is_generator"));
  const auto *visibility_ = mapGet(obj, "visibility");
  if (visibility_ && !isNil(*visibility_))
    result.visibility = parseVisibility(*visibility_);
  result.is_pure = getBool(mapReq(obj, "is_pure"));
  result.name = getString(mapReq(obj, "name"));
  const auto *type_params = mapGet(obj, "type_params");
  if (type_params && !isNil(*type_params))
    result.type_params = parseVec<ast::TypeParam>(*type_params, parseTypeParam);
  result.params = parseVec<ast::Param>(mapReq(obj, "params"), parseParam);
  const auto *return_type = mapGet(obj, "return_type");
  if (return_type && !isNil(*return_type))
    result.return_type = parseSpanned<ast::TypeExpr>(*return_type, parseTypeExpr);
  const auto *where_clause = mapGet(obj, "where_clause");
  if (where_clause && !isNil(*where_clause))
    result.where_clause = parseWhereClause(*where_clause);
  result.body = parseBlock(mapReq(obj, "body"));
  const auto *doc_comment = mapGet(obj, "doc_comment");
  if (doc_comment && !isNil(*doc_comment))
    result.doc_comment = getString(*doc_comment);
  const auto *decl_span_ = mapGet(obj, "decl_span");
  if (decl_span_ && !isNil(*decl_span_))
    result.decl_span = parseSpan(*decl_span_);
  return result;
}

// ── AttributeArg / Attribute ───────────────────────────────────────────────

static ast::AttributeArg parseAttributeArg(const msgpack::object &obj) {
  auto [variant, payload] = getEnumVariant(obj);
  if (variant == "Positional" && payload) {
    return ast::AttributeArg{ast::AttributeArgPositional{getString(*payload)}};
  }
  if (variant == "KeyValue" && payload) {
    ast::AttributeArgKeyValue kv;
    kv.key = getString(mapReq(*payload, "key"));
    kv.value = getString(mapReq(*payload, "value"));
    return ast::AttributeArg{std::move(kv)};
  }
  fail("unknown AttributeArg variant: " + variant);
}

static ast::Attribute parseAttribute(const msgpack::object &obj) {
  ast::Attribute attr;
  attr.name = getString(mapReq(obj, "name"));
  attr.args = parseVec<ast::AttributeArg>(mapReq(obj, "args"), parseAttributeArg);
  attr.span = parseSpan(mapReq(obj, "span"));
  return attr;
}

// ── TypeDecl ────────────────────────────────────────────────────────────────

static ast::TypeDecl parseTypeDecl(const msgpack::object &obj) {
  ast::TypeDecl td;
  const auto *vis = mapGet(obj, "visibility");
  if (vis && !isNil(*vis))
    td.visibility = parseVisibility(*vis);
  auto kindStr = getString(mapReq(obj, "kind"));
  if (kindStr == "Enum")
    td.kind = ast::TypeDeclKind::Enum;
  else if (kindStr == "Struct")
    td.kind = ast::TypeDeclKind::Struct;
  else
    fail("unknown TypeDeclKind: " + kindStr);
  td.name = getString(mapReq(obj, "name"));
  const auto *tp = mapGet(obj, "type_params");
  if (tp && !isNil(*tp))
    td.type_params = parseVec<ast::TypeParam>(*tp, parseTypeParam);
  const auto *wc = mapGet(obj, "where_clause");
  if (wc && !isNil(*wc))
    td.where_clause = parseWhereClause(*wc);
  td.body = parseVec<ast::TypeBodyItem>(mapReq(obj, "body"), [&td](const msgpack::object &o) {
    auto [name, payload] = getEnumVariant(o);
    if (name == "Field") {
      ast::TypeBodyItemField f;
      f.name = getString(mapReq(*payload, "name"));
      f.ty = parseSpanned<ast::TypeExpr>(mapReq(*payload, "ty"), parseTypeExpr);
      return ast::TypeBodyItem{std::move(f)};
    }
    if (name == "Variant") {
      return ast::TypeBodyItem{ast::TypeBodyVariant{parseVariantDecl(*payload)}};
    }
    if (name == "Method") {
      auto fn = std::make_unique<ast::FnDecl>(parseFnDecl(*payload));
      ast::TypeBodyMethod m;
      m.fn = fn.get();
      td.method_storage.push_back(std::move(fn));
      return ast::TypeBodyItem{std::move(m)};
    }
    fail("unknown TypeBodyItem variant: " + name);
  });
  const auto *dc = mapGet(obj, "doc_comment");
  if (dc && !isNil(*dc))
    td.doc_comment = getString(*dc);
  const auto *w = mapGet(obj, "wire");
  if (w && !isNil(*w))
    td.wire = parseWireMetadata(*w);
  const auto *ind = mapGet(obj, "is_indirect");
  if (ind && !isNil(*ind))
    td.is_indirect = getBool(*ind);
  return td;
}

// ── VariantDecl ─────────────────────────────────────────────────────────────

static ast::VariantDecl parseVariantDecl(const msgpack::object &obj) {
  ast::VariantDecl result;
  result.name = getString(mapReq(obj, "name"));

  const auto &kindObj = mapReq(obj, "kind");
  auto [name, payload] = getEnumVariant(kindObj);
  if (name == "Unit") {
    result.kind = ast::VariantDecl::VariantUnit{};
    return result;
  }
  if (name == "Tuple") {
    ast::VariantDecl::VariantTuple tuple;
    tuple.fields = parseVec<ast::Spanned<ast::TypeExpr>>(
        *payload, [](const msgpack::object &o) { return parseSpanned<ast::TypeExpr>(o, parseTypeExpr); });
    result.kind = std::move(tuple);
    return result;
  }
  if (name == "Struct") {
    ast::VariantDecl::VariantStruct s;
    s.fields = parseVec<ast::VariantDecl::VariantStructField>(
        *payload, [](const msgpack::object &o) {
          uint32_t sz;
          const auto *arr = arrayData(o, sz);
          if (sz != 2)
            fail("tuple should have 2 elements");
          ast::VariantDecl::VariantStructField field;
          field.name = getString(arr[0]);
          field.ty = parseSpanned<ast::TypeExpr>(arr[1], parseTypeExpr);
          return field;
        });
    result.kind = std::move(s);
    return result;
  }
  fail("unknown VariantKind variant: " + name);
}

// ── TraitItem ───────────────────────────────────────────────────────────────

static ast::TraitItem parseTraitItem(const msgpack::object &obj) {
  auto [name, payload] = getEnumVariant(obj);

  if (name == "Method")
    return ast::TraitItem{ast::TraitItemMethod{parseTraitMethod(*payload)}};
  if (name == "AssociatedType") {
    ast::TraitItemAssociatedType e;
    e.name = getString(mapReq(*payload, "name"));
    e.bounds = parseVec<ast::TraitBound>(mapReq(*payload, "bounds"), parseTraitBound);
    const auto *default_value = mapGet(*payload, "default");
    if (default_value && !isNil(*default_value))
      e.default_value = parseSpanned<ast::TypeExpr>(*default_value, parseTypeExpr);
    return ast::TraitItem{std::move(e)};
  }
  fail("unknown TraitItem variant: " + name);
}

// ── MatchArm / SelectArm ──────────────────────────────────────────────────

static ast::MatchArm parseMatchArm(const msgpack::object &obj) {
  ast::MatchArm arm;
  arm.pattern = parseSpanned<ast::Pattern>(mapReq(obj, "pattern"), parsePattern);
  const auto *g = mapGet(obj, "guard");
  if (g && !isNil(*g))
    arm.guard = parseSpannedPtr<ast::Expr>(*g, parseExpr);
  arm.body = parseSpannedPtr<ast::Expr>(mapReq(obj, "body"), parseExpr);
  return arm;
}

static ast::SelectArm parseSelectArm(const msgpack::object &obj) {
  ast::SelectArm arm;
  arm.binding = parseSpanned<ast::Pattern>(mapReq(obj, "binding"), parsePattern);
  arm.source = parseSpannedPtr<ast::Expr>(mapReq(obj, "source"), parseExpr);
  arm.body = parseSpannedPtr<ast::Expr>(mapReq(obj, "body"), parseExpr);
  return arm;
}

// ── Expr ───────────────────────────────────────────────────────────────────

static ast::Expr parseExpr(const msgpack::object &obj) {
  auto [name, payload] = getEnumVariant(obj);

  if (name == "Binary") {
    ast::ExprBinary e;
    e.left = std::make_unique<ast::Spanned<ast::Expr>>(
        parseSpanned<ast::Expr>(mapReq(*payload, "left"), parseExpr));
    e.op = parseBinaryOp(mapReq(*payload, "op"));
    e.right = std::make_unique<ast::Spanned<ast::Expr>>(
        parseSpanned<ast::Expr>(mapReq(*payload, "right"), parseExpr));
    return ast::Expr{std::move(e), {}};
  }
  if (name == "Unary") {
    ast::ExprUnary e;
    e.op = parseUnaryOp(mapReq(*payload, "op"));
    e.operand = std::make_unique<ast::Spanned<ast::Expr>>(
        parseSpanned<ast::Expr>(mapReq(*payload, "operand"), parseExpr));
    return ast::Expr{std::move(e), {}};
  }
  if (name == "Literal")
    return ast::Expr{ast::ExprLiteral{parseLiteral(*payload)}, {}};
  if (name == "Identifier")
    return ast::Expr{ast::ExprIdentifier{getString(*payload)}, {}};
  if (name == "Tuple") {
    ast::ExprTuple e;
    e.elements = parseVecPtr<ast::Spanned<ast::Expr>>(
        *payload, [](const msgpack::object &o) { return parseSpanned<ast::Expr>(o, parseExpr); });
    return ast::Expr{std::move(e), {}};
  }
  if (name == "Array") {
    ast::ExprArray e;
    e.elements = parseVecPtr<ast::Spanned<ast::Expr>>(
        *payload, [](const msgpack::object &o) { return parseSpanned<ast::Expr>(o, parseExpr); });
    return ast::Expr{std::move(e), {}};
  }
  if (name == "MapLiteral") {
    ast::ExprMapLiteral e;
    if (payload) {
      auto entriesArr = mapReq(*payload, "entries");
      if (entriesArr.type == msgpack::type::ARRAY) {
        for (uint32_t i = 0; i < entriesArr.via.array.size; ++i) {
          auto &pairObj = entriesArr.via.array.ptr[i];
          // Each entry is a 2-element array: [key, value]
          if (pairObj.type != msgpack::type::ARRAY || pairObj.via.array.size != 2)
            fail("MapLiteral entry must be a 2-element array, got size " +
                 std::to_string(pairObj.type == msgpack::type::ARRAY ? pairObj.via.array.size : 0));
          ast::ExprMapEntry entry;
          entry.key = std::make_unique<ast::Spanned<ast::Expr>>(
              parseSpanned<ast::Expr>(pairObj.via.array.ptr[0], parseExpr));
          entry.value = std::make_unique<ast::Spanned<ast::Expr>>(
              parseSpanned<ast::Expr>(pairObj.via.array.ptr[1], parseExpr));
          e.entries.emplace_back(std::move(entry));
        }
      }
    }
    return ast::Expr{std::move(e), {}};
  }
  if (name == "ArrayRepeat") {
    ast::ExprArrayRepeat e;
    e.value = std::make_unique<ast::Spanned<ast::Expr>>(
        parseSpanned<ast::Expr>(mapReq(*payload, "value"), parseExpr));
    e.count = std::make_unique<ast::Spanned<ast::Expr>>(
        parseSpanned<ast::Expr>(mapReq(*payload, "count"), parseExpr));
    return ast::Expr{std::move(e), {}};
  }
  if (name == "Block")
    return ast::Expr{ast::ExprBlock{parseBlock(*payload)}, {}};
  if (name == "If") {
    ast::ExprIf e;
    e.condition = std::make_unique<ast::Spanned<ast::Expr>>(
        parseSpanned<ast::Expr>(mapReq(*payload, "condition"), parseExpr));
    e.then_block = std::make_unique<ast::Spanned<ast::Expr>>(
        parseSpanned<ast::Expr>(mapReq(*payload, "then_block"), parseExpr));
    const auto *eb = mapGet(*payload, "else_block");
    if (eb && !isNil(*eb)) {
      e.else_block =
          std::make_unique<ast::Spanned<ast::Expr>>(parseSpanned<ast::Expr>(*eb, parseExpr));
    }
    return ast::Expr{std::move(e), {}};
  }
  if (name == "IfLet") {
    ast::ExprIfLet e;
    e.pattern = parseSpanned<ast::Pattern>(mapReq(*payload, "pattern"), parsePattern);
    e.expr = std::make_unique<ast::Spanned<ast::Expr>>(
        parseSpanned<ast::Expr>(mapReq(*payload, "expr"), parseExpr));
    e.body = parseBlock(mapReq(*payload, "body"));
    const auto *eb = mapGet(*payload, "else_body");
    if (eb && !isNil(*eb))
      e.else_body = parseBlock(*eb);
    return ast::Expr{std::move(e), {}};
  }
  if (name == "Match") {
    ast::ExprMatch e;
    e.scrutinee = std::make_unique<ast::Spanned<ast::Expr>>(
        parseSpanned<ast::Expr>(mapReq(*payload, "scrutinee"), parseExpr));
    e.arms = parseVec<ast::MatchArm>(mapReq(*payload, "arms"), parseMatchArm);
    return ast::Expr{std::move(e), {}};
  }
  if (name == "Lambda") {
    ast::ExprLambda e;
    e.is_move = getBool(mapReq(*payload, "is_move"));
    const auto *tp = mapGet(*payload, "type_params");
    if (tp && !isNil(*tp))
      e.type_params = parseVec<ast::TypeParam>(*tp, parseTypeParam);
    e.params = parseVec<ast::LambdaParam>(mapReq(*payload, "params"), parseLambdaParam);
    const auto *rt = mapGet(*payload, "return_type");
    if (rt && !isNil(*rt))
      e.return_type = parseSpanned<ast::TypeExpr>(*rt, parseTypeExpr);
    e.body = std::make_unique<ast::Spanned<ast::Expr>>(
        parseSpanned<ast::Expr>(mapReq(*payload, "body"), parseExpr));
    return ast::Expr{std::move(e), {}};
  }
  if (name == "Spawn") {
    ast::ExprSpawn e;
    e.target = std::make_unique<ast::Spanned<ast::Expr>>(
        parseSpanned<ast::Expr>(mapReq(*payload, "target"), parseExpr));
    e.args = parseVec<std::pair<std::string, std::unique_ptr<ast::Spanned<ast::Expr>>>>(
        mapReq(*payload, "args"), [](const msgpack::object &o) {
          // (String, Spanned<Expr>) = [name_str, spanned_expr]
          uint32_t sz;
          const auto *arr = arrayData(o, sz);
          if (sz != 2)
            fail("Spawn arg tuple should have 2 elements");
          return std::make_pair(getString(arr[0]), parseSpannedPtr<ast::Expr>(arr[1], parseExpr));
        });
    return ast::Expr{std::move(e), {}};
  }
  if (name == "SpawnLambdaActor") {
    ast::ExprSpawnLambdaActor e;
    e.is_move = getBool(mapReq(*payload, "is_move"));
    e.params = parseVec<ast::LambdaParam>(mapReq(*payload, "params"), parseLambdaParam);
    const auto *rt = mapGet(*payload, "return_type");
    if (rt && !isNil(*rt))
      e.return_type = parseSpanned<ast::TypeExpr>(*rt, parseTypeExpr);
    e.body = std::make_unique<ast::Spanned<ast::Expr>>(
        parseSpanned<ast::Expr>(mapReq(*payload, "body"), parseExpr));
    return ast::Expr{std::move(e), {}};
  }
  if (name == "Scope") {
    ast::ExprScope e;
    const auto *bind = mapGet(*payload, "binding");
    if (bind && !isNil(*bind))
      e.binding = getString(*bind);
    e.block = parseBlock(mapReq(*payload, "body"));
    return ast::Expr{std::move(e), {}};
  }
  if (name == "InterpolatedString") {
    ast::ExprInterpolatedString e;
    e.parts = parseVec<ast::StringPart>(*payload, parseStringPart);
    return ast::Expr{std::move(e), {}};
  }
  if (name == "Call") {
    ast::ExprCall e;
    e.function = std::make_unique<ast::Spanned<ast::Expr>>(
        parseSpanned<ast::Expr>(mapReq(*payload, "function"), parseExpr));
    const auto *ta = mapGet(*payload, "type_args");
    if (ta && !isNil(*ta)) {
      e.type_args = parseVec<ast::Spanned<ast::TypeExpr>>(*ta, [](const msgpack::object &o) {
        return parseSpanned<ast::TypeExpr>(o, parseTypeExpr);
      });
    }
    {
      auto &argsArr = mapReq(*payload, "args");
      if (argsArr.type == msgpack::type::ARRAY) {
        auto &arrData = argsArr.via.array;
        for (uint32_t j = 0; j < arrData.size; j++) {
          e.args.push_back(parseCallArg(arrData.ptr[j]));
        }
      }
    }
    e.is_tail_call = getBool(mapReq(*payload, "is_tail_call"));
    return ast::Expr{std::move(e), {}};
  }
  if (name == "MethodCall") {
    ast::ExprMethodCall e;
    e.receiver = std::make_unique<ast::Spanned<ast::Expr>>(
        parseSpanned<ast::Expr>(mapReq(*payload, "receiver"), parseExpr));
    e.method = getString(mapReq(*payload, "method"));
    {
      auto &argsArr = mapReq(*payload, "args");
      if (argsArr.type == msgpack::type::ARRAY) {
        auto &arrData = argsArr.via.array;
        for (uint32_t j = 0; j < arrData.size; j++) {
          e.args.push_back(parseCallArg(arrData.ptr[j]));
        }
      }
    }
    return ast::Expr{std::move(e), {}};
  }
  if (name == "StructInit") {
    ast::ExprStructInit e;
    e.name = getString(mapReq(*payload, "name"));
    e.fields = parseVec<std::pair<std::string, std::unique_ptr<ast::Spanned<ast::Expr>>>>(
        mapReq(*payload, "fields"), [](const msgpack::object &o) {
          // (String, Spanned<Expr>) = [name_str, spanned_expr]
          uint32_t sz;
          const auto *arr = arrayData(o, sz);
          if (sz != 2)
            fail("StructInit field tuple should have 2 elements");
          return std::make_pair(getString(arr[0]), parseSpannedPtr<ast::Expr>(arr[1], parseExpr));
        });
    return ast::Expr{std::move(e), {}};
  }
  if (name == "Send") {
    ast::ExprSend e;
    e.target = std::make_unique<ast::Spanned<ast::Expr>>(
        parseSpanned<ast::Expr>(mapReq(*payload, "target"), parseExpr));
    e.message = std::make_unique<ast::Spanned<ast::Expr>>(
        parseSpanned<ast::Expr>(mapReq(*payload, "message"), parseExpr));
    return ast::Expr{std::move(e), {}};
  }
  if (name == "Select") {
    ast::ExprSelect e;
    e.arms = parseVec<ast::SelectArm>(mapReq(*payload, "arms"), parseSelectArm);
    const auto *to = mapGet(*payload, "timeout");
    if (to && !isNil(*to)) {
      e.timeout = std::make_unique<ast::TimeoutClause>(parseTimeoutClause(*to));
    }
    return ast::Expr{std::move(e), {}};
  }
  if (name == "Join") {
    ast::ExprJoin e;
    e.exprs = parseVecPtr<ast::Spanned<ast::Expr>>(
        *payload, [](const msgpack::object &o) { return parseSpanned<ast::Expr>(o, parseExpr); });
    return ast::Expr{std::move(e), {}};
  }
  if (name == "Timeout") {
    ast::ExprTimeout e;
    e.expr = std::make_unique<ast::Spanned<ast::Expr>>(
        parseSpanned<ast::Expr>(mapReq(*payload, "expr"), parseExpr));
    e.duration = std::make_unique<ast::Spanned<ast::Expr>>(
        parseSpanned<ast::Expr>(mapReq(*payload, "duration"), parseExpr));
    return ast::Expr{std::move(e), {}};
  }
  if (name == "Unsafe")
    return ast::Expr{ast::ExprUnsafe{parseBlock(*payload)}, {}};
  if (name == "Yield") {
    ast::ExprYield e;
    if (payload && !isNil(*payload)) {
      e.value =
          std::make_unique<ast::Spanned<ast::Expr>>(parseSpanned<ast::Expr>(*payload, parseExpr));
    }
    return ast::Expr{std::move(e), {}};
  }
  if (name == "Cooperate")
    return ast::Expr{ast::ExprCooperate{}, {}};
  if (name == "This")
    return ast::Expr{ast::ExprThis{}, {}};
  if (name == "FieldAccess") {
    ast::ExprFieldAccess e;
    e.object = std::make_unique<ast::Spanned<ast::Expr>>(
        parseSpanned<ast::Expr>(mapReq(*payload, "object"), parseExpr));
    e.field = getString(mapReq(*payload, "field"));
    return ast::Expr{std::move(e), {}};
  }
  if (name == "Index") {
    ast::ExprIndex e;
    e.object = std::make_unique<ast::Spanned<ast::Expr>>(
        parseSpanned<ast::Expr>(mapReq(*payload, "object"), parseExpr));
    e.index = std::make_unique<ast::Spanned<ast::Expr>>(
        parseSpanned<ast::Expr>(mapReq(*payload, "index"), parseExpr));
    return ast::Expr{std::move(e), {}};
  }
  if (name == "Cast") {
    ast::ExprCast e;
    e.expr = std::make_unique<ast::Spanned<ast::Expr>>(
        parseSpanned<ast::Expr>(mapReq(*payload, "expr"), parseExpr));
    e.ty = parseSpanned<ast::TypeExpr>(mapReq(*payload, "ty"), parseTypeExpr);
    return ast::Expr{std::move(e), {}};
  }
  if (name == "PostfixTry") {
    ast::ExprPostfixTry e;
    e.inner =
        std::make_unique<ast::Spanned<ast::Expr>>(parseSpanned<ast::Expr>(*payload, parseExpr));
    return ast::Expr{std::move(e), {}};
  }
  if (name == "Range") {
    ast::ExprRange e;
    const auto *s = mapGet(*payload, "start");
    if (s && !isNil(*s)) {
      e.start = std::make_unique<ast::Spanned<ast::Expr>>(parseSpanned<ast::Expr>(*s, parseExpr));
    }
    const auto *en = mapGet(*payload, "end");
    if (en && !isNil(*en)) {
      e.end = std::make_unique<ast::Spanned<ast::Expr>>(parseSpanned<ast::Expr>(*en, parseExpr));
    }
    e.inclusive = getBool(mapReq(*payload, "inclusive"));
    return ast::Expr{std::move(e), {}};
  }
  if (name == "Await") {
    ast::ExprAwait e;
    e.inner =
        std::make_unique<ast::Spanned<ast::Expr>>(parseSpanned<ast::Expr>(*payload, parseExpr));
    return ast::Expr{std::move(e), {}};
  }
  if (name == "ScopeLaunch")
    return ast::Expr{ast::ExprScopeLaunch{parseBlock(*payload)}, {}};
  if (name == "ScopeSpawn")
    return ast::Expr{ast::ExprScopeSpawn{parseBlock(*payload)}, {}};
  if (name == "ScopeCancel")
    return ast::Expr{ast::ExprScopeCancel{}, {}};

  if (name == "RegexLiteral")
    return ast::Expr{ast::ExprRegexLiteral{getString(*payload)}, {}};
  if (name == "ByteStringLiteral")
    return ast::Expr{
        ast::ExprByteStringLiteral{parseVec<uint8_t>(
            *payload, [](const msgpack::object &o) { return static_cast<uint8_t>(getInt(o)); })},
        {}};
  if (name == "ByteArrayLiteral")
    return ast::Expr{
        ast::ExprByteArrayLiteral{parseVec<uint8_t>(
            *payload, [](const msgpack::object &o) { return static_cast<uint8_t>(getInt(o)); })},
        {}};
  fail("unknown Expr variant: " + name);
}

// ── ElseBlock / Stmt / MachineTransition ─────────────────────────────────

static ast::ElseBlock parseElseBlock(const msgpack::object &obj) {
  ast::ElseBlock eb;
  eb.is_if = getBool(mapReq(obj, "is_if"));
  const auto *ifs = mapGet(obj, "if_stmt");
  if (ifs && !isNil(*ifs)) {
    eb.if_stmt = parseSpannedPtr<ast::Stmt>(*ifs, parseStmt);
  }
  const auto *blk = mapGet(obj, "block");
  if (blk && !isNil(*blk))
    eb.block = parseBlock(*blk);
  return eb;
}

static ast::Stmt parseStmt(const msgpack::object &obj) {
  auto [name, payload] = getEnumVariant(obj);

  if (name == "Let") {
    ast::StmtLet s;
    s.pattern = parseSpanned<ast::Pattern>(mapReq(*payload, "pattern"), parsePattern);
    const auto *ty = mapGet(*payload, "ty");
    if (ty && !isNil(*ty))
      s.ty = parseSpanned<ast::TypeExpr>(*ty, parseTypeExpr);
    const auto *val = mapGet(*payload, "value");
    if (val && !isNil(*val))
      s.value = parseSpanned<ast::Expr>(*val, parseExpr);
    return ast::Stmt{std::move(s), {}};
  }
  if (name == "Var") {
    ast::StmtVar s;
    s.name = getString(mapReq(*payload, "name"));
    const auto *ty = mapGet(*payload, "ty");
    if (ty && !isNil(*ty))
      s.ty = parseSpanned<ast::TypeExpr>(*ty, parseTypeExpr);
    const auto *val = mapGet(*payload, "value");
    if (val && !isNil(*val))
      s.value = parseSpanned<ast::Expr>(*val, parseExpr);
    return ast::Stmt{std::move(s), {}};
  }
  if (name == "Assign") {
    ast::StmtAssign s;
    s.target = parseSpanned<ast::Expr>(mapReq(*payload, "target"), parseExpr);
    const auto *op = mapGet(*payload, "op");
    if (op && !isNil(*op))
      s.op = parseCompoundAssignOp(*op);
    s.value = parseSpanned<ast::Expr>(mapReq(*payload, "value"), parseExpr);
    return ast::Stmt{std::move(s), {}};
  }
  if (name == "If") {
    ast::StmtIf s;
    s.condition = parseSpanned<ast::Expr>(mapReq(*payload, "condition"), parseExpr);
    s.then_block = parseBlock(mapReq(*payload, "then_block"));
    const auto *eb = mapGet(*payload, "else_block");
    if (eb && !isNil(*eb))
      s.else_block = parseElseBlock(*eb);
    return ast::Stmt{std::move(s), {}};
  }
  if (name == "IfLet") {
    ast::StmtIfLet s;
    s.pattern = parseSpanned<ast::Pattern>(mapReq(*payload, "pattern"), parsePattern);
    s.expr = std::make_unique<ast::Spanned<ast::Expr>>(
        parseSpanned<ast::Expr>(mapReq(*payload, "expr"), parseExpr));
    s.body = parseBlock(mapReq(*payload, "body"));
    const auto *eb = mapGet(*payload, "else_body");
    if (eb && !isNil(*eb))
      s.else_body = parseBlock(*eb);
    return ast::Stmt{std::move(s), {}};
  }
  if (name == "Match") {
    ast::StmtMatch s;
    s.scrutinee = parseSpanned<ast::Expr>(mapReq(*payload, "scrutinee"), parseExpr);
    s.arms = parseVec<ast::MatchArm>(mapReq(*payload, "arms"), parseMatchArm);
    return ast::Stmt{std::move(s), {}};
  }
  if (name == "Loop") {
    ast::StmtLoop s;
    const auto *lbl = mapGet(*payload, "label");
    if (lbl && !isNil(*lbl))
      s.label = getString(*lbl);
    s.body = parseBlock(mapReq(*payload, "body"));
    return ast::Stmt{std::move(s), {}};
  }
  if (name == "For") {
    ast::StmtFor s;
    const auto *lbl = mapGet(*payload, "label");
    if (lbl && !isNil(*lbl))
      s.label = getString(*lbl);
    s.is_await = getBool(mapReq(*payload, "is_await"));
    s.pattern = parseSpanned<ast::Pattern>(mapReq(*payload, "pattern"), parsePattern);
    s.iterable = parseSpanned<ast::Expr>(mapReq(*payload, "iterable"), parseExpr);
    s.body = parseBlock(mapReq(*payload, "body"));
    return ast::Stmt{std::move(s), {}};
  }
  if (name == "While") {
    ast::StmtWhile s;
    const auto *lbl = mapGet(*payload, "label");
    if (lbl && !isNil(*lbl))
      s.label = getString(*lbl);
    s.condition = parseSpanned<ast::Expr>(mapReq(*payload, "condition"), parseExpr);
    s.body = parseBlock(mapReq(*payload, "body"));
    return ast::Stmt{std::move(s), {}};
  }
  if (name == "WhileLet") {
    ast::StmtWhileLet s;
    const auto *lbl = mapGet(*payload, "label");
    if (lbl && !isNil(*lbl))
      s.label = getString(*lbl);
    s.pattern = parseSpanned<ast::Pattern>(mapReq(*payload, "pattern"), parsePattern);
    s.expr = std::make_unique<ast::Spanned<ast::Expr>>(
        parseSpanned<ast::Expr>(mapReq(*payload, "expr"), parseExpr));
    s.body = parseBlock(mapReq(*payload, "body"));
    return ast::Stmt{std::move(s), {}};
  }
  if (name == "Break") {
    ast::StmtBreak s;
    const auto *lbl = mapGet(*payload, "label");
    if (lbl && !isNil(*lbl))
      s.label = getString(*lbl);
    const auto *val = mapGet(*payload, "value");
    if (val && !isNil(*val))
      s.value = parseSpanned<ast::Expr>(*val, parseExpr);
    return ast::Stmt{std::move(s), {}};
  }
  if (name == "Continue") {
    ast::StmtContinue s;
    const auto *lbl = mapGet(*payload, "label");
    if (lbl && !isNil(*lbl))
      s.label = getString(*lbl);
    return ast::Stmt{std::move(s), {}};
  }
  if (name == "Return") {
    ast::StmtReturn s;
    if (payload && !isNil(*payload))
      s.value = parseSpanned<ast::Expr>(*payload, parseExpr);
    return ast::Stmt{std::move(s), {}};
  }
  if (name == "Defer") {
    ast::StmtDefer s;
    s.expr =
        std::make_unique<ast::Spanned<ast::Expr>>(parseSpanned<ast::Expr>(*payload, parseExpr));
    return ast::Stmt{std::move(s), {}};
  }
  if (name == "Expression") {
    ast::StmtExpression s;
    s.expr = parseSpanned<ast::Expr>(*payload, parseExpr);
    return ast::Stmt{std::move(s), {}};
  }
  fail("unknown Stmt variant: " + name);
}

static ast::MachineTransition parseMachineTransition(const msgpack::object &obj) {
  ast::MachineTransition mt;
  mt.event_name = getString(mapReq(obj, "event_name"));
  mt.source_state = getString(mapReq(obj, "source_state"));
  mt.target_state = getString(mapReq(obj, "target_state"));
  const auto *g = mapGet(obj, "guard");
  if (g && !isNil(*g))
    mt.guard = parseSpannedPtr<ast::Expr>(*g, parseExpr);
  mt.body = parseSpanned<ast::Expr>(mapReq(obj, "body"), parseExpr);
  return mt;
}

// ── ChildSpec ──────────────────────────────────────────────────────────────

static ast::ChildSpec parseChildSpec(const msgpack::object &obj) {
  ast::ChildSpec cs;
  cs.name = getString(mapReq(obj, "name"));
  cs.actor_type = getString(mapReq(obj, "actor_type"));
  cs.args = parseVec<ast::Spanned<ast::Expr>>(mapReq(obj, "args"), [](const msgpack::object &o) {
    return parseSpanned<ast::Expr>(o, parseExpr);
  });
  const auto *r = mapGet(obj, "restart");
  if (r && !isNil(*r)) {
    auto s = getString(*r);
    if (s == "Permanent")
      cs.restart = ast::RestartPolicy::Permanent;
    else if (s == "Transient")
      cs.restart = ast::RestartPolicy::Transient;
    else if (s == "Temporary")
      cs.restart = ast::RestartPolicy::Temporary;
    else
      fail("unknown RestartPolicy: " + s);
  }
  return cs;
}

// ── ReceiveFnDecl ──────────────────────────────────────────────────────────

static ast::ReceiveFnDecl parseReceiveFnDecl(const msgpack::object &obj) {
  ast::ReceiveFnDecl rf;
  rf.is_generator = getBool(mapReq(obj, "is_generator"));
  rf.is_pure = getBool(mapReq(obj, "is_pure"));
  rf.name = getString(mapReq(obj, "name"));
  const auto *tp = mapGet(obj, "type_params");
  if (tp && !isNil(*tp))
    rf.type_params = parseVec<ast::TypeParam>(*tp, parseTypeParam);
  rf.params = parseVec<ast::Param>(mapReq(obj, "params"), parseParam);
  const auto *rt = mapGet(obj, "return_type");
  if (rt && !isNil(*rt))
    rf.return_type = parseSpanned<ast::TypeExpr>(*rt, parseTypeExpr);
  const auto *wc = mapGet(obj, "where_clause");
  if (wc && !isNil(*wc))
    rf.where_clause = parseWhereClause(*wc);
  rf.body = parseBlock(mapReq(obj, "body"));
  rf.span = parseSpan(mapReq(obj, "span"));

  const auto *attrs = mapGet(obj, "attributes");
  if (attrs && !isNil(*attrs) && attrs->type == msgpack::type::ARRAY) {
    for (uint32_t i = 0; i < attrs->via.array.size; ++i) {
      const auto &attrObj = attrs->via.array.ptr[i];
      auto attrName = getString(mapReq(attrObj, "name"));
      if (attrName != "every")
        continue;
      const auto *argsArr = mapGet(attrObj, "args");
      if (!argsArr || isNil(*argsArr) || argsArr->type != msgpack::type::ARRAY ||
          argsArr->via.array.size != 1)
        continue;

      const auto &argObj = argsArr->via.array.ptr[0];
      auto [variantName, payload] = getEnumVariant(argObj);
      if (variantName == "Duration" && payload)
        rf.periodic_interval_ns = getInt(*payload);
    }
  }

  return rf;
}

// ── ModuleId / ModuleImport / Module ──────────────────────────────────────

static ast::ModuleId parseModuleId(const msgpack::object &obj) {
  ast::ModuleId id;
  // JSON input: module IDs are serialized as flat strings (e.g., "std::misc::log")
  // because JSON objects require string keys. Split on "::" to recover path segments.
  if (obj.type == msgpack::type::STR) {
    auto s = getString(obj);
    if (s == "(root)") {
      // Root module has an empty path.
      return id;
    }
    // Split on "::"
    size_t pos = 0;
    while (pos < s.size()) {
      auto next = s.find("::", pos);
      if (next == std::string::npos) {
        id.path.push_back(s.substr(pos));
        break;
      }
      id.path.push_back(s.substr(pos, next - pos));
      pos = next + 2;
    }
    return id;
  }
  // Msgpack input: module IDs are serialized as {"path": ["seg1", "seg2", ...]}.
  id.path = parseVec<std::string>(mapReq(obj, "path"),
                                  [](const msgpack::object &o) { return getString(o); });
  return id;
}

static ast::ModuleImport parseModuleImport(const msgpack::object &obj) {
  ast::ModuleImport mi;
  mi.target = parseModuleId(mapReq(obj, "target"));
  const auto *spec = mapGet(obj, "spec");
  if (spec && !isNil(*spec)) {
    auto [name, payload] = getEnumVariant(*spec);
    if (name == "Glob") {
      mi.spec = ast::ImportSpecGlob{};
    } else if (name == "Names") {
      mi.spec =
          ast::ImportSpecNames{parseVec<ast::ImportName>(*payload, [](const msgpack::object &o) {
            ast::ImportName n;
            n.name = getString(mapReq(o, "name"));
            const auto *alias = mapGet(o, "alias");
            if (alias && !isNil(*alias))
              n.alias = getString(*alias);
            return n;
          })};
    }
  }
  mi.span = parseSpan(mapReq(obj, "span"));
  return mi;
}

static ast::Module parseModule(const msgpack::object &obj) {
  ast::Module m;
  m.id = parseModuleId(mapReq(obj, "id"));
  m.items = parseVec<ast::Spanned<ast::Item>>(mapReq(obj, "items"), [](const msgpack::object &o) {
    return parseSpanned<ast::Item>(o, parseItem);
  });
  m.imports = parseVec<ast::ModuleImport>(mapReq(obj, "imports"), parseModuleImport);
  const auto *sp = mapGet(obj, "source_paths");
  if (sp && !isNil(*sp)) {
    m.source_paths =
        parseVec<std::string>(*sp, [](const msgpack::object &o) { return getString(o); });
  }
  const auto *doc = mapGet(obj, "doc");
  if (doc && !isNil(*doc))
    m.doc = getString(*doc);
  return m;
}

// ── ModuleGraph ─────────────────────────────────────────────────────────────

static ast::ModuleGraph parseModuleGraph(const msgpack::object &obj) {
  ast::ModuleGraph mg;
  mg.root = parseModuleId(mapReq(obj, "root"));
  mg.topo_order = parseVec<ast::ModuleId>(mapReq(obj, "topo_order"), parseModuleId);

  const auto &modulesObj = mapReq(obj, "modules");
  if (modulesObj.type == msgpack::type::ARRAY) {
    for (uint32_t i = 0; i < modulesObj.via.array.size; ++i) {
      const auto &pair = modulesObj.via.array.ptr[i];
      if (pair.type == msgpack::type::ARRAY && pair.via.array.size == 2) {
        auto id = parseModuleId(pair.via.array.ptr[0]);
        auto mod = parseModule(pair.via.array.ptr[1]);
        mg.modules.emplace(std::move(id), std::move(mod));
      }
    }
  } else if (modulesObj.type == msgpack::type::MAP) {
    for (uint32_t i = 0; i < modulesObj.via.map.size; ++i) {
      auto id = parseModuleId(modulesObj.via.map.ptr[i].key);
      auto mod = parseModule(modulesObj.via.map.ptr[i].val);
      mg.modules.emplace(std::move(id), std::move(mod));
    }
  }
  return mg;
}

// ── Program (top-level) ─────────────────────────────────────────────────────

static ast::AssignTargetKindData parseAssignTargetKindData(const msgpack::object &obj) {
  auto kind = getString(obj);
  if (kind == "local_var")
    return ast::AssignTargetKindLocalVar{};
  if (kind == "actor_field")
    return ast::AssignTargetKindActorField{};
  if (kind == "field_access")
    return ast::AssignTargetKindFieldAccess{};
  if (kind == "index")
    return ast::AssignTargetKindIndex{};
  fail("unknown AssignTargetKindData variant: " + kind);
}

static ast::AssignTargetKindEntry parseAssignTargetKindEntry(const msgpack::object &obj) {
  ast::AssignTargetKindEntry entry;
  entry.start = getUint(mapReq(obj, "start"));
  entry.end = getUint(mapReq(obj, "end"));
  entry.kind = parseAssignTargetKindData(mapReq(obj, "kind"));
  return entry;
}

static ast::AssignTargetShapeEntry parseAssignTargetShapeEntry(const msgpack::object &obj) {
  ast::AssignTargetShapeEntry entry;
  entry.start = getUint(mapReq(obj, "start"));
  entry.end = getUint(mapReq(obj, "end"));
  entry.is_unsigned = getBool(mapReq(obj, "is_unsigned"));
  return entry;
}

static ast::LoweringKind parseLoweringKind(const msgpack::object &obj) {
  auto kind = getString(obj);
  if (kind == "hash_set")
    return ast::LoweringKind::HashSet;
  fail("unknown lowering kind '" + kind + "'");
}

static ast::HashSetElementType parseHashSetElementType(const msgpack::object &obj) {
  auto kind = getString(obj);
  if (kind == "i64")
    return ast::HashSetElementType::I64;
  if (kind == "u64")
    return ast::HashSetElementType::U64;
  if (kind == "str")
    return ast::HashSetElementType::Str;
  fail("unknown HashSet element type '" + kind + "'");
}

static ast::HashSetAbi parseHashSetAbi(const msgpack::object &obj) {
  auto abi = getString(obj);
  if (abi == "int64")
    return ast::HashSetAbi::Int64;
  if (abi == "string")
    return ast::HashSetAbi::String;
  fail("unknown HashSet ABI '" + abi + "'");
}

static ast::DropKind parseDropKind(const msgpack::object &obj) {
  auto drop = getString(obj);
  if (drop == "hash_set_free")
    return ast::DropKind::HashSetFree;
  fail("unknown drop kind '" + drop + "'");
}

static ast::LoweringFactEntry parseLoweringFactEntry(const msgpack::object &obj) {
  ast::LoweringFactEntry entry;
  entry.start = getUint(mapReq(obj, "start"));
  entry.end = getUint(mapReq(obj, "end"));
  entry.kind = parseLoweringKind(mapReq(obj, "kind"));
  entry.element_type = parseHashSetElementType(mapReq(obj, "element_type"));
  entry.abi_variant = parseHashSetAbi(mapReq(obj, "abi_variant"));
  entry.drop_kind = parseDropKind(mapReq(obj, "drop_kind"));
  return entry;
}

static ast::ExprTypeEntry parseExprTypeEntry(const msgpack::object &obj) {
  ast::ExprTypeEntry entry;
  entry.start = getUint(mapReq(obj, "start"));
  entry.end = getUint(mapReq(obj, "end"));
  entry.ty = parseSpanned<ast::TypeExpr>(mapReq(obj, "ty"), parseTypeExpr);
  return entry;
}

static ast::MethodCallReceiverKindEntry
parseMethodCallReceiverKindEntry(const msgpack::object &obj) {
  ast::MethodCallReceiverKindEntry entry;
  entry.start = getUint(mapReq(obj, "start"));
  entry.end = getUint(mapReq(obj, "end"));
  auto kind = getString(mapReq(obj, "kind"));
  if (kind == "named_type_instance") {
    ast::MethodCallReceiverKindNamedTypeInstance data;
    data.type_name = getString(mapReq(obj, "type_name"));
    entry.kind = std::move(data);
    return entry;
  }
  if (kind == "trait_object") {
    ast::MethodCallReceiverKindTraitObject data;
    data.trait_name = getString(mapReq(obj, "trait_name"));
    entry.kind = std::move(data);
    return entry;
  }
  fail("unknown method_call_receiver_kinds kind '" + kind + "'");
}

static ast::Program parseProgram(const msgpack::object &obj) {
  ast::Program prog;

  // The embedded msgpack boundary is internal to the current `hew` binary, so
  // require an explicit, exact schema version instead of carrying fallback
  // decoding for older payloads.
  prog.schema_version = static_cast<uint32_t>(getUint(mapReq(obj, "schema_version")));
  if (prog.schema_version != CURRENT_SCHEMA_VERSION) {
    fail("unsupported schema version " + std::to_string(prog.schema_version) +
         " (expected: " + std::to_string(CURRENT_SCHEMA_VERSION) + ")");
  }

  prog.items =
      parseVec<ast::Spanned<ast::Item>>(mapReq(obj, "items"), [](const msgpack::object &o) {
        return parseSpanned<ast::Item>(o, parseItem);
      });
  const auto *md = mapGet(obj, "module_doc");
  if (md && !isNil(*md))
    prog.module_doc = getString(*md);
  prog.expr_types = parseVec<ast::ExprTypeEntry>(mapReq(obj, "expr_types"), parseExprTypeEntry);
  prog.method_call_receiver_kinds = parseVec<ast::MethodCallReceiverKindEntry>(
      mapReq(obj, "method_call_receiver_kinds"), parseMethodCallReceiverKindEntry);
  prog.assign_target_kinds = parseVec<ast::AssignTargetKindEntry>(
      mapReq(obj, "assign_target_kinds"), parseAssignTargetKindEntry);
  prog.assign_target_shapes = parseVec<ast::AssignTargetShapeEntry>(
      mapReq(obj, "assign_target_shapes"), parseAssignTargetShapeEntry);
  prog.lowering_facts =
      parseVec<ast::LoweringFactEntry>(mapReq(obj, "lowering_facts"), parseLoweringFactEntry);

  // Handle type metadata: list of known handle type names
  prog.handle_types =
      parseVec<std::string>(mapReq(obj, "handle_types"), [](const msgpack::object &o) {
        return getString(o);
      });

  // Handle type representations: map of type name → repr string ("i32", etc.)
  const auto &hr = mapReq(obj, "handle_type_repr");
  if (hr.type != msgpack::type::MAP)
    fail("expected map, got type " + std::to_string(hr.type));
  for (uint32_t i = 0; i < hr.via.map.size; ++i) {
    auto &kv = hr.via.map.ptr[i];
    std::string key = getString(kv.key);
    std::string val = getString(kv.val);
    prog.handle_type_repr[key] = val;
  }
  const auto *mg = mapGet(obj, "module_graph");
  if (mg && !isNil(*mg))
    prog.module_graph = parseModuleGraph(*mg);

  // Source path for debug info (optional — some frontend flows do not provide it)
  const auto *sp = mapGet(obj, "source_path");
  if (sp && !isNil(*sp))
    prog.source_path = getString(*sp);

  // Line map: byte offset of each line start (optional)
  const auto *lm = mapGet(obj, "line_map");
  if (lm && !isNil(*lm))
    prog.line_map = parseVec<size_t>(
        *lm, [](const msgpack::object &o) { return static_cast<size_t>(getUint(o)); });

  // Drop function metadata: maps qualified handle type name → C drop function.
  // Populated from `impl Drop` blocks in stdlib .hew files.
  // Fail closed: if the key is present it must be a map of string pairs.
  const auto *df = mapGet(obj, "drop_funcs");
  if (df && !isNil(*df)) {
    if (df->type != msgpack::type::ARRAY)
      fail("expected array for drop_funcs, got type " + std::to_string(df->type));
    for (uint32_t i = 0; i < df->via.array.size; ++i) {
      const auto &pair = df->via.array.ptr[i];
      if (pair.type != msgpack::type::ARRAY || pair.via.array.size != 2)
        fail("drop_funcs entry must be a 2-element array");
      std::string ty = getString(pair.via.array.ptr[0]);
      std::string func = getString(pair.via.array.ptr[1]);
      prog.drop_funcs[ty] = func;
    }
  }

  return prog;
}

// ── Public API ──────────────────────────────────────────────────────────────

ast::Program parseMsgpackAST(const uint8_t *data, size_t size) {
  msgpack::object_handle oh = msgpack::unpack(reinterpret_cast<const char *>(data), size);
  return parseProgram(oh.get());
}

} // namespace hew
