//! Hew runtime: `sign` module.
//!
//! Provides Ed25519 key-pair generation, signing, and verification for
//! compiled Hew programs.  All key and signature material is carried as
//! raw byte buffers; there are no opaque handle types.
//!
//! ## Size constants (Ed25519 / ring 0.17)
//!
//! | Constant              | Bytes | Source                                      |
//! |-----------------------|-------|---------------------------------------------|
//! | `ED25519_PKCS8_LEN`   |   83  | `ring` PKCS#8 v2 document (private + public)|
//! | `ED25519_PUBLIC_LEN`  |   32  | raw 32-byte Curve25519 public point         |
//! | `ED25519_SIG_LEN`     |   64  | raw 64-byte signature (r ‖ s)               |
//!
//! ## Ownership / ABI contract (for the reviewer)
//!
//! Every `_hew`-suffixed function follows the `BytesTriple` ABI established by
//! `std/crypto/crypto` (commit d2bd9ba8) and `hew-runtime/src/file_io.rs`
//! (commit d4e7f4c7):
//!
//! - **Input** `bytes` values arrive as `*const BytesTriple` (by-pointer
//!   consumer convention; `is_bytes_by_pointer_consumer` in codegen).
//!   Each callee reads `{ ptr, offset, len }` from the pointer without taking
//!   ownership; the caller retains the allocation.
//! - **Output** `bytes` values are returned as `BytesTriple` by value.
//!   Codegen uses the `_raw` out-pointer variant on all platforms to avoid
//!   the Windows x64 MSVC sret mismatch.  `is_bytes_triple_return_producer`
//!   in codegen controls which functions use this path.
//! - `hew_ed25519_verify_hew` returns `i32` (0/1); its inputs still use the
//!   by-pointer consumer convention.
//! - The raw C-ABI variants (`hew_ed25519_*` without `_hew` suffix) are
//!   provided for direct use from other native Rust code or future FFI callers;
//!   they do not touch `BytesTriple` at all.
//!
//! ## Hew surface mapping
//!
//! The Hew `keypair()` function calls two `_hew` functions in sequence:
//!
//! 1. `hew_ed25519_generate_pkcs8_hew()` → `bytes` (83-byte PKCS#8 document)
//! 2. `hew_ed25519_public_key_from_pkcs8_hew(*const BytesTriple)` → `bytes`
//!    (32-byte public key)
//!
//! This keeps each FFI call to the `fn(args) -> bytes` shape already used by
//! `hew_sha256_hew` and friends — no novel calling convention is introduced.
//!
//! ## Fail-closed policy
//!
//! - The raw C-ABI variants (`hew_ed25519_*` without `_hew` suffix) treat
//!   null pointers and zero-length inputs as invalid and return `0`/empty
//!   sentinel rather than causing UB.
//! - The `_hew` `BytesTriple` wrappers treat null `BytesTriple` pointers and
//!   zero-length inputs as invalid.  On bad inputs:
//!   - `hew_ed25519_verify_hew` returns `0` (fail-closed sentinel).
//!   - `hew_ed25519_sign_hew` and `hew_ed25519_public_key_from_pkcs8_hew`
//!     call `hew_panic_msg` (controlled trap) — the caller's contract is to
//!     pass non-null `*const BytesTriple` values.
//! - `hew_ed25519_sign_hew` also calls `hew_panic_msg` when the private key
//!   bytes are not a valid 83-byte PKCS#8 document.
//! - Secret-key bytes are never written to error messages or logs.
use ring::{
    rand::SystemRandom,
    signature::{Ed25519KeyPair, KeyPair, UnparsedPublicKey, ED25519},
};

type BytesTriple = hew_runtime::bytes::BytesTriple;

/// Length (bytes) of an Ed25519 PKCS#8 v2 document as generated by ring 0.17.
///
/// Ring uses a PKCS#8 v2 template (`ed25519_pkcs8_v2_template.der`, 19 bytes)
/// plus the 32-byte private scalar plus the 32-byte public point = 83 bytes.
/// This length is checked at runtime in all build profiles before any
/// fixed-size buffer copy; if ring's encoding ever changes, the generating
/// function fails closed (returns `0`) rather than overflowing the buffer.
pub const ED25519_PKCS8_LEN: usize = 83;

/// Length (bytes) of a raw Ed25519 public key.
pub const ED25519_PUBLIC_LEN: usize = 32;

/// Length (bytes) of an Ed25519 signature.
pub const ED25519_SIG_LEN: usize = 64;

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/// Panic with a static NUL-terminated message via the Hew runtime.
///
/// Diverges: `hew_panic_msg` does not return.
fn panic_msg(message: &'static [u8]) -> ! {
    use std::ffi::c_char;
    // SAFETY: message is a valid static NUL-terminated string.
    unsafe { hew_runtime::actor::hew_panic_msg(message.as_ptr().cast::<c_char>()) };
    unreachable!("hew_panic_msg should not return")
}

/// Abort the process with no fabricated crypto output.
fn abort_sign_failure() -> ! {
    // SAFETY: abort terminates fail-closed; no fabricated crypto bytes escape.
    unsafe { libc::abort() }
}

/// Allocate a `BytesTriple` from a fixed-size byte slice.
fn bytes_from_slice(bytes: &[u8]) -> BytesTriple {
    let len = u32::try_from(bytes.len()).unwrap_or_else(|_| abort_sign_failure());
    // SAFETY: `bytes` is valid for `len` bytes; `hew_bytes_from_static` copies it
    // into a fresh, refcount-1 bytes allocation owned by the Hew caller.
    unsafe { hew_runtime::bytes::hew_bytes_from_static(bytes.as_ptr(), len) }
}

/// Extract a `Vec<u8>` from a by-pointer `BytesTriple`.
///
/// Returns `None` if the pointer is null, treating that as an empty/absent input.
/// A null pointer with zero len returns `Some(Vec::new())`.
///
/// # Safety
///
/// `triple` must be either null or a valid pointer to a `BytesTriple` whose
/// `ptr + offset` region is valid for `len` bytes.
unsafe fn bytes_from_triple(triple: *const BytesTriple) -> Option<Vec<u8>> {
    if triple.is_null() {
        return None;
    }
    // SAFETY: caller guarantees triple is non-null and valid.
    let t = unsafe { &*triple };
    if t.len == 0 {
        return Some(Vec::new());
    }
    if t.ptr.is_null() {
        return None;
    }
    let offset = t.offset as usize;
    let len = t.len as usize;
    // SAFETY: triple.ptr + offset is valid for len bytes per BytesTriple invariant.
    Some(unsafe { std::slice::from_raw_parts(t.ptr.add(offset), len) }.to_vec())
}

/// Copy `src` into the fixed-size buffer `out` only when `src.len() == N`.
///
/// This is the single checked seam in front of every fixed-buffer
/// `copy_nonoverlapping` in this module.  `out` is a caller-owned buffer valid
/// for exactly `N` bytes; the length equality is the guard that keeps a copy
/// from running past it if ring's encoded length ever diverges from the
/// documented constant.
///
/// Returns `1` and writes all `N` bytes on a length match; returns `0` and
/// writes **nothing** on a mismatch.  The check is an ordinary `if` so it holds
/// in every build profile — a `debug_assert!` here would be stripped in release
/// and reintroduce the overflow risk this seam exists to remove.
///
/// # Safety
///
/// `out` must be valid for writing `N` bytes.  `src` must be a valid slice.
unsafe fn fill_fixed<const N: usize>(out: *mut u8, src: &[u8]) -> i32 {
    // Fail closed: refuse to write when the source length does not match the
    // fixed buffer.  Not a release-stripped `debug_assert!` — this is the guard
    // that prevents a fixed-buffer overflow in all profiles.
    if src.len() != N {
        return 0;
    }
    // SAFETY: out is valid for N bytes per caller contract, and src.len() is
    // verified to equal N above.
    unsafe { std::ptr::copy_nonoverlapping(src.as_ptr(), out, N) };
    1
}

// ---------------------------------------------------------------------------
// Raw C-ABI layer (no BytesTriple; usable from native callers)
// ---------------------------------------------------------------------------

/// Generate an Ed25519 PKCS#8 v2 document and write the 83 bytes to `out`.
///
/// Returns `1` on success, `0` if the RNG failed or `out` is null.
///
/// # Safety
///
/// `out` must be valid for writing `ED25519_PKCS8_LEN` (83) bytes.
#[no_mangle]
pub unsafe extern "C" fn hew_ed25519_generate_pkcs8(out: *mut u8) -> i32 {
    if out.is_null() {
        return 0;
    }
    let rng = SystemRandom::new();
    let Ok(pkcs8_doc) = Ed25519KeyPair::generate_pkcs8(&rng) else {
        return 0;
    };
    let bytes = pkcs8_doc.as_ref();
    // Fail closed via the checked seam: copy only if ring's PKCS#8 document is
    // exactly ED25519_PKCS8_LEN bytes, never overflowing `out` if the encoded
    // length ever changes.  Returns 0 without writing on a mismatch.
    // SAFETY: out is valid for ED25519_PKCS8_LEN bytes per caller contract.
    unsafe { fill_fixed::<ED25519_PKCS8_LEN>(out, bytes) }
}

/// Extract the 32-byte public key from an Ed25519 PKCS#8 document.
///
/// Returns `1` on success, `0` if either pointer is null or the key is invalid.
///
/// # Safety
///
/// - `pkcs8` must be valid for reading `pkcs8_len` bytes.
/// - `out` must be valid for writing `ED25519_PUBLIC_LEN` (32) bytes.
#[no_mangle]
pub unsafe extern "C" fn hew_ed25519_public_key_from_pkcs8(
    pkcs8: *const u8,
    pkcs8_len: usize,
    out: *mut u8,
) -> i32 {
    if pkcs8.is_null() || out.is_null() {
        return 0;
    }
    // SAFETY: pkcs8 is valid for pkcs8_len bytes per caller contract.
    let key_bytes = unsafe { std::slice::from_raw_parts(pkcs8, pkcs8_len) };
    let Ok(key_pair) = Ed25519KeyPair::from_pkcs8(key_bytes) else {
        return 0;
    };
    let pub_bytes = key_pair.public_key().as_ref();
    // Fail closed via the checked seam: copy only if the public key is exactly
    // ED25519_PUBLIC_LEN bytes, preventing an overflow if the length ever
    // diverges from 32.  Returns 0 without writing on a mismatch.
    // SAFETY: out is valid for ED25519_PUBLIC_LEN bytes per caller contract.
    unsafe { fill_fixed::<ED25519_PUBLIC_LEN>(out, pub_bytes) }
}

/// Sign `msg` (`msg_len` bytes) with the PKCS#8 private key (`key`, `key_len`
/// bytes) and write the 64-byte signature into `sig_out`.
///
/// Returns `1` on success, `0` if any input is null/invalid.
///
/// # Safety
///
/// - `key` must be valid for reading `key_len` bytes.
/// - `msg` must be valid for reading `msg_len` bytes (may be null when
///   `msg_len == 0`).
/// - `sig_out` must be valid for writing `ED25519_SIG_LEN` (64) bytes.
#[no_mangle]
pub unsafe extern "C" fn hew_ed25519_sign(
    key: *const u8,
    key_len: usize,
    msg: *const u8,
    msg_len: usize,
    sig_out: *mut u8,
) -> i32 {
    if key.is_null() || sig_out.is_null() {
        return 0;
    }
    // SAFETY: key is valid for key_len bytes per caller contract.
    let key_bytes = unsafe { std::slice::from_raw_parts(key, key_len) };
    // SAFETY: msg is valid for msg_len bytes, or empty when msg_len == 0.
    let msg_bytes: &[u8] = if msg.is_null() || msg_len == 0 {
        &[]
    } else {
        // SAFETY: msg is non-null and valid for msg_len bytes.
        unsafe { std::slice::from_raw_parts(msg, msg_len) }
    };

    // Invalid key: fail closed.  Do NOT write anything to sig_out.
    let Ok(key_pair) = Ed25519KeyPair::from_pkcs8(key_bytes) else {
        return 0;
    };

    let sig = key_pair.sign(msg_bytes);
    let sig_bytes = sig.as_ref();
    // Fail closed via the checked seam: copy only if the signature is exactly
    // ED25519_SIG_LEN bytes, preventing an overflow if the length ever diverges
    // from 64.  Returns 0 without writing on a mismatch.
    // SAFETY: sig_out is valid for ED25519_SIG_LEN bytes per caller contract.
    unsafe { fill_fixed::<ED25519_SIG_LEN>(sig_out, sig_bytes) }
}

/// Verify that `sig` (`sig_len` bytes) is a valid Ed25519 signature over `msg`
/// (`msg_len` bytes) under `public_key` (`key_len` bytes).
///
/// Returns `1` if valid, `0` otherwise (including any parse or length error).
///
/// # Safety
///
/// - `public_key` must be valid for reading `key_len` bytes.
/// - `msg` must be valid for reading `msg_len` bytes (may be null when
///   `msg_len == 0`).
/// - `sig` must be valid for reading `sig_len` bytes.
#[no_mangle]
pub unsafe extern "C" fn hew_ed25519_verify(
    public_key: *const u8,
    key_len: usize,
    msg: *const u8,
    msg_len: usize,
    sig: *const u8,
    sig_len: usize,
) -> i32 {
    if public_key.is_null() || sig.is_null() {
        return 0;
    }
    // SAFETY: public_key is valid for key_len bytes per caller contract.
    let key_bytes = unsafe { std::slice::from_raw_parts(public_key, key_len) };
    // SAFETY: msg is valid for msg_len bytes, or empty when msg_len == 0.
    let msg_bytes: &[u8] = if msg.is_null() || msg_len == 0 {
        &[]
    } else {
        // SAFETY: msg is non-null and valid for msg_len bytes.
        unsafe { std::slice::from_raw_parts(msg, msg_len) }
    };
    // SAFETY: sig is valid for sig_len bytes per caller contract.
    let sig_bytes = unsafe { std::slice::from_raw_parts(sig, sig_len) };

    let unparsed = UnparsedPublicKey::new(&ED25519, key_bytes);
    match unparsed.verify(msg_bytes, sig_bytes) {
        Ok(()) => 1,
        Err(_) => 0,
    }
}

// ---------------------------------------------------------------------------
// BytesTriple-ABI wrappers (called from std/crypto/sign/sign.hew)
// ---------------------------------------------------------------------------
//
// Each `_hew` wrapper follows the same ABI as the sibling crypto module
// (d2bd9ba8) and the file I/O fix (d4e7f4c7):
//
//   - `bytes` inputs: `*const BytesTriple` (by-pointer consumer convention).
//     Codegen passes the address of the caller's BytesTriple alloca.
//     `is_bytes_by_pointer_consumer` in `hew-codegen-rs/src/llvm.rs` must
//     list every function that receives bytes this way.
//   - `bytes` outputs: `BytesTriple` by value.  Codegen uses the `_raw`
//     out-pointer sibling on all platforms to avoid the Windows x64 MSVC sret
//     mismatch.  `is_bytes_triple_return_producer` in codegen must list every
//     function that returns bytes this way.

/// Generate an Ed25519 PKCS#8 v2 document and return it as an 83-byte
/// `bytes` value (`BytesTriple`).
///
/// Calls `abort()` on RNG failure (should not occur in practice).
///
/// # Safety
///
/// No inputs; all memory is managed by the runtime allocator.
#[no_mangle]
pub unsafe extern "C" fn hew_ed25519_generate_pkcs8_hew() -> BytesTriple {
    let mut buf = [0u8; ED25519_PKCS8_LEN];
    // SAFETY: buf is a valid ED25519_PKCS8_LEN-byte writable buffer.
    let ok = unsafe { hew_ed25519_generate_pkcs8(buf.as_mut_ptr()) };
    if ok == 0 {
        abort_sign_failure();
    }
    bytes_from_slice(&buf)
}

/// Out-pointer variant of [`hew_ed25519_generate_pkcs8_hew`] for Windows x64
/// MSVC sret compatibility.
///
/// Writes the result into `*out` and returns void.  Every bytes-triple producer
/// exports a `_raw` sibling so that codegen can use the out-pointer calling
/// convention on all platforms.
///
/// # Safety
///
/// `out` must be a valid, writable pointer to a `BytesTriple` slot.
#[no_mangle]
pub unsafe extern "C" fn hew_ed25519_generate_pkcs8_hew_raw(out: *mut BytesTriple) {
    // SAFETY: preconditions forwarded from caller contract above.
    let triple = unsafe { hew_ed25519_generate_pkcs8_hew() };
    // SAFETY: caller guarantees `out` is a valid BytesTriple slot.
    unsafe { out.write(triple) };
}

/// Extract the 32-byte public key from an Ed25519 PKCS#8 `bytes` value and
/// return it as a new 32-byte `bytes` value (`BytesTriple`).
///
/// Calls `hew_panic_msg` if `pkcs8` is null or is not a valid 83-byte PKCS#8
/// document.
///
/// # Safety
///
/// `pkcs8` must be a valid, non-null pointer to a `BytesTriple` whose payload
/// is an 83-byte Ed25519 PKCS#8 v2 document.
#[no_mangle]
pub unsafe extern "C" fn hew_ed25519_public_key_from_pkcs8_hew(
    pkcs8: *const BytesTriple,
) -> BytesTriple {
    // SAFETY: caller guarantees pkcs8 is non-null and valid.
    let Some(pkcs8_bytes) = (unsafe { bytes_from_triple(pkcs8) }) else {
        panic_msg(b"sign.keypair failed: pkcs8 must be a valid non-null bytes value\0")
    };
    let mut pub_buf = [0u8; ED25519_PUBLIC_LEN];
    // SAFETY: pkcs8_bytes and pub_buf are valid buffers.
    let ok = unsafe {
        hew_ed25519_public_key_from_pkcs8(
            pkcs8_bytes.as_ptr(),
            pkcs8_bytes.len(),
            pub_buf.as_mut_ptr(),
        )
    };
    if ok == 0 {
        panic_msg(b"sign.keypair failed: private_key must be an 83-byte Ed25519 PKCS#8 document\0");
    }
    bytes_from_slice(&pub_buf)
}

/// Out-pointer variant of [`hew_ed25519_public_key_from_pkcs8_hew`] for Windows
/// x64 MSVC sret compatibility.
///
/// # Safety
///
/// - `pkcs8` must be a valid, non-null pointer to a `BytesTriple`.
/// - `out` must be a valid, writable pointer to a `BytesTriple` slot.
#[no_mangle]
pub unsafe extern "C" fn hew_ed25519_public_key_from_pkcs8_hew_raw(
    pkcs8: *const BytesTriple,
    out: *mut BytesTriple,
) {
    // SAFETY: preconditions forwarded from caller contract above.
    let triple = unsafe { hew_ed25519_public_key_from_pkcs8_hew(pkcs8) };
    // SAFETY: caller guarantees `out` is a valid BytesTriple slot.
    unsafe { out.write(triple) };
}

/// Sign `message` (a `bytes` value) with `private_key` (an 83-byte PKCS#8
/// `bytes` value) and return the 64-byte signature as a `bytes` value
/// (`BytesTriple`).
///
/// Calls `hew_panic_msg` if either input is null or `private_key` is not a
/// valid 83-byte PKCS#8 document.
///
/// # Safety
///
/// - `message` must be a valid, non-null pointer to a `BytesTriple` (may be
///   zero-length).
/// - `private_key` must be a valid, non-null pointer to a `BytesTriple`.
#[no_mangle]
pub unsafe extern "C" fn hew_ed25519_sign_hew(
    message: *const BytesTriple,
    private_key: *const BytesTriple,
) -> BytesTriple {
    // SAFETY: caller guarantees private_key is non-null and valid.
    let Some(key_bytes) = (unsafe { bytes_from_triple(private_key) }) else {
        panic_msg(b"sign.sign failed: private_key must be a valid non-null bytes value\0")
    };
    // SAFETY: caller guarantees message is non-null and valid.
    let msg_bytes = unsafe { bytes_from_triple(message) }.unwrap_or_default();

    let mut sig_buf = [0u8; ED25519_SIG_LEN];
    // SAFETY: key_bytes and msg_bytes are valid slices; sig_buf is a 64-byte buffer.
    let ok = unsafe {
        hew_ed25519_sign(
            key_bytes.as_ptr(),
            key_bytes.len(),
            msg_bytes.as_ptr(),
            msg_bytes.len(),
            sig_buf.as_mut_ptr(),
        )
    };
    if ok == 0 {
        panic_msg(b"sign.sign failed: private_key must be an 83-byte Ed25519 PKCS#8 document\0");
    }
    bytes_from_slice(&sig_buf)
}

/// Out-pointer variant of [`hew_ed25519_sign_hew`] for Windows x64 MSVC sret
/// compatibility.
///
/// # Safety
///
/// - `message` must be a valid, non-null pointer to a `BytesTriple`.
/// - `private_key` must be a valid, non-null pointer to a `BytesTriple`.
/// - `out` must be a valid, writable pointer to a `BytesTriple` slot.
#[no_mangle]
pub unsafe extern "C" fn hew_ed25519_sign_hew_raw(
    message: *const BytesTriple,
    private_key: *const BytesTriple,
    out: *mut BytesTriple,
) {
    // SAFETY: preconditions forwarded from caller contract above.
    let triple = unsafe { hew_ed25519_sign_hew(message, private_key) };
    // SAFETY: caller guarantees `out` is a valid BytesTriple slot.
    unsafe { out.write(triple) };
}

/// Verify an Ed25519 `signature` over `message` using `public_key`.
///
/// Returns `1` if the signature is valid, `0` otherwise.  Never panics or
/// aborts — null pointer inputs and verification failures all return a clean `0`.
///
/// # Safety
///
/// - `message`, `signature`, and `public_key` must each be either null or a
///   valid pointer to a live `BytesTriple`.  Dangling non-null pointers are
///   undefined behaviour.
#[no_mangle]
pub unsafe extern "C" fn hew_ed25519_verify_hew(
    message: *const BytesTriple,
    signature: *const BytesTriple,
    public_key: *const BytesTriple,
) -> i32 {
    // Treat null inputs as empty/missing → return 0 (fail-closed).
    // SAFETY: each pointer is either null or a valid BytesTriple per caller contract.
    let Some(key_bytes) = (unsafe { bytes_from_triple(public_key) }) else {
        return 0;
    };
    // SAFETY: pointer is either null or a valid BytesTriple per caller contract.
    let msg_bytes = unsafe { bytes_from_triple(message) }.unwrap_or_default();
    // SAFETY: pointer is either null or a valid BytesTriple per caller contract.
    let Some(sig_bytes) = (unsafe { bytes_from_triple(signature) }) else {
        return 0;
    };

    // SAFETY: all slices are valid; raw verify handles length mismatches cleanly.
    unsafe {
        hew_ed25519_verify(
            key_bytes.as_ptr(),
            key_bytes.len(),
            msg_bytes.as_ptr(),
            msg_bytes.len(),
            sig_bytes.as_ptr(),
            sig_bytes.len(),
        )
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
// SAFETY: test module calls unsafe FFI extensively. Each unsafe block is
// documented at the call site or covered by the surrounding test's contract
// (null-safety, allocation-owner, or raw-ABI shape). Suppress the lint at
// module level to avoid annotating every one-line test helper individually.
#[allow(
    clippy::undocumented_unsafe_blocks,
    reason = "test module calls unsafe FFI; each block's contract is captured in the surrounding test"
)]
mod tests {
    use super::*;

    /// Helper: generate a fresh key pair via the raw C-ABI.
    fn gen_pair() -> ([u8; ED25519_PKCS8_LEN], [u8; ED25519_PUBLIC_LEN]) {
        let mut pkcs8 = [0u8; ED25519_PKCS8_LEN];
        let mut public = [0u8; ED25519_PUBLIC_LEN];
        // SAFETY: both buffers are valid for their respective lengths.
        let ok = unsafe { hew_ed25519_generate_pkcs8(pkcs8.as_mut_ptr()) };
        assert_eq!(ok, 1, "key generation must succeed");
        // SAFETY: pkcs8 and public are valid buffers of their respective lengths.
        let ok2 = unsafe {
            hew_ed25519_public_key_from_pkcs8(pkcs8.as_ptr(), pkcs8.len(), public.as_mut_ptr())
        };
        assert_eq!(ok2, 1, "public key extraction must succeed");
        (pkcs8, public)
    }

    // --- raw C-ABI: sign → verify round-trip ---

    /// A signature produced by `sign` must be accepted by `verify`.
    #[test]
    fn sign_verify_roundtrip_succeeds() {
        let (pkcs8, public) = gen_pair();
        let msg = b"hello hew";
        let mut sig = [0u8; ED25519_SIG_LEN];
        // SAFETY: all buffers are valid.
        let ok = unsafe {
            hew_ed25519_sign(
                pkcs8.as_ptr(),
                pkcs8.len(),
                msg.as_ptr(),
                msg.len(),
                sig.as_mut_ptr(),
            )
        };
        assert_eq!(ok, 1, "signing must succeed");

        // SAFETY: all buffers are valid.
        let verified = unsafe {
            hew_ed25519_verify(
                public.as_ptr(),
                public.len(),
                msg.as_ptr(),
                msg.len(),
                sig.as_ptr(),
                sig.len(),
            )
        };
        assert_eq!(verified, 1, "signature over original message must verify");
    }

    // --- tampered message is rejected ---

    /// Modifying a single byte of the message invalidates the signature.
    #[test]
    fn verify_rejects_tampered_message() {
        let (pkcs8, public) = gen_pair();
        let msg = b"original message";
        let mut sig = [0u8; ED25519_SIG_LEN];
        // SAFETY: all buffers are valid.
        unsafe {
            hew_ed25519_sign(
                pkcs8.as_ptr(),
                pkcs8.len(),
                msg.as_ptr(),
                msg.len(),
                sig.as_mut_ptr(),
            );
        }
        let tampered = b"original XXXXXXX"; // same length, different content
                                            // SAFETY: all buffers are valid.
        let verified = unsafe {
            hew_ed25519_verify(
                public.as_ptr(),
                public.len(),
                tampered.as_ptr(),
                tampered.len(),
                sig.as_ptr(),
                sig.len(),
            )
        };
        assert_eq!(
            verified, 0,
            "signature must be rejected for tampered message"
        );
    }

    // --- wrong public key is rejected ---

    /// A signature verified with the wrong public key must be rejected.
    #[test]
    fn verify_rejects_wrong_public_key() {
        let (pkcs8, _) = gen_pair();
        let (_, wrong_public) = gen_pair();
        let msg = b"test message";
        let mut sig = [0u8; ED25519_SIG_LEN];
        // SAFETY: all buffers are valid.
        unsafe {
            hew_ed25519_sign(
                pkcs8.as_ptr(),
                pkcs8.len(),
                msg.as_ptr(),
                msg.len(),
                sig.as_mut_ptr(),
            );
        }
        // SAFETY: all buffers are valid.
        let verified = unsafe {
            hew_ed25519_verify(
                wrong_public.as_ptr(),
                wrong_public.len(),
                msg.as_ptr(),
                msg.len(),
                sig.as_ptr(),
                sig.len(),
            )
        };
        assert_eq!(
            verified, 0,
            "signature must be rejected for wrong public key"
        );
    }

    // --- malformed signature is rejected ---

    /// A buffer of the right length but wrong content is rejected.
    #[test]
    fn verify_rejects_malformed_signature() {
        let (_, public) = gen_pair();
        let msg = b"test message";
        let bad_sig = [0xAAu8; ED25519_SIG_LEN];
        // SAFETY: all buffers are valid.
        let verified = unsafe {
            hew_ed25519_verify(
                public.as_ptr(),
                public.len(),
                msg.as_ptr(),
                msg.len(),
                bad_sig.as_ptr(),
                bad_sig.len(),
            )
        };
        assert_eq!(verified, 0, "all-0xAA signature must be rejected");
    }

    // --- wrong-length signature is rejected ---

    #[test]
    fn verify_rejects_short_signature() {
        let (_, public) = gen_pair();
        let msg = b"test message";
        let short_sig = [0u8; 32]; // 32, not 64
                                   // SAFETY: all buffers are valid.
        let verified = unsafe {
            hew_ed25519_verify(
                public.as_ptr(),
                public.len(),
                msg.as_ptr(),
                msg.len(),
                short_sig.as_ptr(),
                short_sig.len(),
            )
        };
        assert_eq!(verified, 0, "short signature must be rejected");
    }

    // --- null-pointer guards (raw ABI) ---

    #[test]
    fn generate_pkcs8_null_out_returns_zero() {
        // SAFETY: null out is explicitly handled.
        let ok = unsafe { hew_ed25519_generate_pkcs8(std::ptr::null_mut()) };
        assert_eq!(ok, 0);
    }

    #[test]
    fn public_key_from_pkcs8_null_key_returns_zero() {
        let mut out = [0u8; ED25519_PUBLIC_LEN];
        // SAFETY: null pkcs8 is explicitly handled.
        let ok =
            unsafe { hew_ed25519_public_key_from_pkcs8(std::ptr::null(), 0, out.as_mut_ptr()) };
        assert_eq!(ok, 0);
    }

    #[test]
    fn public_key_from_pkcs8_null_out_returns_zero() {
        let (pkcs8, _) = gen_pair();
        // SAFETY: null out is explicitly handled.
        let ok = unsafe {
            hew_ed25519_public_key_from_pkcs8(pkcs8.as_ptr(), pkcs8.len(), std::ptr::null_mut())
        };
        assert_eq!(ok, 0);
    }

    #[test]
    fn sign_null_key_returns_zero() {
        let msg = b"x";
        let mut sig = [0u8; ED25519_SIG_LEN];
        // SAFETY: null key is explicitly handled.
        let ok = unsafe {
            hew_ed25519_sign(
                std::ptr::null(),
                0,
                msg.as_ptr(),
                msg.len(),
                sig.as_mut_ptr(),
            )
        };
        assert_eq!(ok, 0);
    }

    #[test]
    fn sign_null_out_returns_zero() {
        let (pkcs8, _) = gen_pair();
        let msg = b"x";
        // SAFETY: null sig_out is explicitly handled.
        let ok = unsafe {
            hew_ed25519_sign(
                pkcs8.as_ptr(),
                pkcs8.len(),
                msg.as_ptr(),
                msg.len(),
                std::ptr::null_mut(),
            )
        };
        assert_eq!(ok, 0);
    }

    #[test]
    fn verify_null_public_key_returns_zero() {
        let msg = b"x";
        let sig = [0u8; ED25519_SIG_LEN];
        // SAFETY: null public_key is explicitly handled.
        let verified = unsafe {
            hew_ed25519_verify(
                std::ptr::null(),
                0,
                msg.as_ptr(),
                msg.len(),
                sig.as_ptr(),
                sig.len(),
            )
        };
        assert_eq!(verified, 0);
    }

    #[test]
    fn verify_null_sig_returns_zero() {
        let (_, public) = gen_pair();
        let msg = b"x";
        // SAFETY: null sig is explicitly handled.
        let verified = unsafe {
            hew_ed25519_verify(
                public.as_ptr(),
                public.len(),
                msg.as_ptr(),
                msg.len(),
                std::ptr::null(),
                0,
            )
        };
        assert_eq!(verified, 0);
    }

    // --- sign with invalid PKCS#8 key ---

    #[test]
    fn sign_invalid_key_returns_zero() {
        let bad_key = [0u8; ED25519_PKCS8_LEN]; // not a valid PKCS#8 document
        let msg = b"test";
        let mut sig = [0u8; ED25519_SIG_LEN];
        // SAFETY: all buffers are valid; bad_key is the right length but invalid content.
        let ok = unsafe {
            hew_ed25519_sign(
                bad_key.as_ptr(),
                bad_key.len(),
                msg.as_ptr(),
                msg.len(),
                sig.as_mut_ptr(),
            )
        };
        assert_eq!(ok, 0, "signing with an invalid key must return 0");
        // sig_out must remain all-zero (not partially written).
        assert_eq!(
            sig, [0u8; ED25519_SIG_LEN],
            "sig_out must be untouched on failure"
        );
    }

    // --- empty message round-trip ---

    #[test]
    fn sign_verify_empty_message() {
        let (pkcs8, public) = gen_pair();
        let mut sig = [0u8; ED25519_SIG_LEN];
        // SAFETY: null msg with msg_len=0 is the empty-message path.
        let ok = unsafe {
            hew_ed25519_sign(
                pkcs8.as_ptr(),
                pkcs8.len(),
                std::ptr::null(),
                0,
                sig.as_mut_ptr(),
            )
        };
        assert_eq!(ok, 1);
        // SAFETY: all buffers are valid.
        let verified = unsafe {
            hew_ed25519_verify(
                public.as_ptr(),
                public.len(),
                std::ptr::null(),
                0,
                sig.as_ptr(),
                sig.len(),
            )
        };
        assert_eq!(verified, 1, "signature over empty message must verify");
    }

    // --- two fresh key pairs produce different keys ---

    #[test]
    fn generate_produces_distinct_key_pairs() {
        let (pkcs8_a, _) = gen_pair();
        let (pkcs8_b, _) = gen_pair();
        assert_ne!(pkcs8_a, pkcs8_b, "two generated key pairs must differ");
    }

    // --- signing is deterministic for Ed25519 (RFC 8032 deterministic nonce) ---

    #[test]
    fn sign_deterministic_same_key_same_message() {
        let (pkcs8, _) = gen_pair();
        let msg = b"deterministic";
        let mut sig1 = [0u8; ED25519_SIG_LEN];
        let mut sig2 = [0u8; ED25519_SIG_LEN];
        // SAFETY: all buffers are valid.
        unsafe {
            hew_ed25519_sign(
                pkcs8.as_ptr(),
                pkcs8.len(),
                msg.as_ptr(),
                msg.len(),
                sig1.as_mut_ptr(),
            );
            hew_ed25519_sign(
                pkcs8.as_ptr(),
                pkcs8.len(),
                msg.as_ptr(),
                msg.len(),
                sig2.as_mut_ptr(),
            );
        }
        assert_eq!(sig1, sig2, "Ed25519 signing must be deterministic");
    }

    // --- public_key_from_pkcs8 rejects invalid document ---

    #[test]
    fn public_key_from_pkcs8_rejects_invalid_document() {
        let bad = [0u8; ED25519_PKCS8_LEN];
        let mut out = [0u8; ED25519_PUBLIC_LEN];
        // SAFETY: bad is the right length but not a valid PKCS#8 document.
        let ok =
            unsafe { hew_ed25519_public_key_from_pkcs8(bad.as_ptr(), bad.len(), out.as_mut_ptr()) };
        assert_eq!(ok, 0, "invalid PKCS#8 must be rejected");
    }

    // --- SIGN-1: wrong-length inputs fail closed without touching the output ---
    //
    // The fixed-size output buffers are only valid for their documented length.
    // A wrong-length input must return 0 and leave the output buffer untouched
    // (no partial write, no overflow) — the hard length checks promoted from
    // `debug_assert!` guarantee this in release builds, not just debug.

    /// A PKCS#8 input that is too short must be rejected, leaving `out` untouched.
    #[test]
    fn public_key_from_pkcs8_rejects_short_input_without_writing_out() {
        let short = [0u8; ED25519_PKCS8_LEN - 1]; // wrong length
        let mut out = [0xCDu8; ED25519_PUBLIC_LEN]; // sentinel fill
                                                    // SAFETY: short is a valid slice of its own length; out is a valid buffer.
        let ok = unsafe {
            hew_ed25519_public_key_from_pkcs8(short.as_ptr(), short.len(), out.as_mut_ptr())
        };
        assert_eq!(ok, 0, "short PKCS#8 input must fail closed");
        assert_eq!(
            out, [0xCDu8; ED25519_PUBLIC_LEN],
            "output buffer must be untouched on a rejected input"
        );
    }

    /// A PKCS#8 input that is too long must be rejected, leaving `out` untouched.
    #[test]
    fn public_key_from_pkcs8_rejects_long_input_without_writing_out() {
        let long = [0u8; ED25519_PKCS8_LEN + 16]; // wrong length
        let mut out = [0xCDu8; ED25519_PUBLIC_LEN]; // sentinel fill
                                                    // SAFETY: long is a valid slice of its own length; out is a valid buffer.
        let ok = unsafe {
            hew_ed25519_public_key_from_pkcs8(long.as_ptr(), long.len(), out.as_mut_ptr())
        };
        assert_eq!(ok, 0, "over-long PKCS#8 input must fail closed");
        assert_eq!(
            out, [0xCDu8; ED25519_PUBLIC_LEN],
            "output buffer must be untouched on a rejected input"
        );
    }

    /// A wrong-length private key must be rejected by `sign`, leaving `sig_out`
    /// untouched — no partial write into the fixed 64-byte buffer.
    #[test]
    fn sign_rejects_wrong_length_key_without_writing_sig() {
        let wrong_len_key = [0u8; ED25519_PKCS8_LEN + 8]; // wrong length, invalid doc
        let msg = b"test";
        let mut sig = [0xCDu8; ED25519_SIG_LEN]; // sentinel fill
                                                 // SAFETY: all buffers are valid for their own lengths.
        let ok = unsafe {
            hew_ed25519_sign(
                wrong_len_key.as_ptr(),
                wrong_len_key.len(),
                msg.as_ptr(),
                msg.len(),
                sig.as_mut_ptr(),
            )
        };
        assert_eq!(ok, 0, "wrong-length key must fail closed");
        assert_eq!(
            sig, [0xCDu8; ED25519_SIG_LEN],
            "signature buffer must be untouched on a rejected key"
        );
    }

    // --- SIGN-1: the output-copy seam guards the fixed buffer in ALL profiles ---
    //
    // The public `hew_ed25519_*` functions reject malformed *input* inside ring's
    // `from_pkcs8` before the output-length guard is ever reached, so an
    // input-only test cannot prove the guard that stands in front of the fixed
    // stack buffer.  These tests exercise `fill_fixed` — the single checked seam
    // every `copy_nonoverlapping` routes through — directly with a wrong-length
    // source.  They run identically under debug and `--release`; the release run
    // is the point: a `debug_assert!` here would be stripped and let an
    // over-length source overflow the buffer.  If the seam regressed to a
    // debug-only assertion, the release run of these tests would write past the
    // sentinel buffer (UB / corruption) instead of returning 0.

    /// A source shorter than `N` must be refused with a `0` return and no write.
    #[test]
    fn fill_fixed_rejects_short_source_without_writing_out() {
        let mut out = [0xCDu8; ED25519_PUBLIC_LEN]; // sentinel fill
        let short = [0xAAu8; ED25519_PUBLIC_LEN - 1]; // one byte too short
                                                      // SAFETY: out is valid for ED25519_PUBLIC_LEN bytes; short is a valid slice.
        let ok = unsafe { fill_fixed::<ED25519_PUBLIC_LEN>(out.as_mut_ptr(), &short) };
        assert_eq!(ok, 0, "short source must fail closed");
        assert_eq!(
            out, [0xCDu8; ED25519_PUBLIC_LEN],
            "output buffer must be untouched when the source is too short"
        );
    }

    /// A source longer than `N` must be refused *before* any copy — proving the
    /// guard is a real runtime check, not a release-stripped `debug_assert!`.
    /// An over-length copy is the exact overflow this seam prevents.
    #[test]
    fn fill_fixed_rejects_long_source_without_writing_out() {
        let mut out = [0xCDu8; ED25519_SIG_LEN]; // sentinel fill
        let long = [0xAAu8; ED25519_SIG_LEN + 32]; // longer than the buffer
                                                   // SAFETY: out is valid for ED25519_SIG_LEN bytes; long is a valid slice.
        let ok = unsafe { fill_fixed::<ED25519_SIG_LEN>(out.as_mut_ptr(), &long) };
        assert_eq!(ok, 0, "over-length source must fail closed");
        assert_eq!(
            out, [0xCDu8; ED25519_SIG_LEN],
            "output buffer must be untouched when the source is too long"
        );
    }

    /// The PKCS#8-length guard behind `hew_ed25519_generate_pkcs8` has no
    /// observable wrong-length path at the public function (ring always emits 83
    /// bytes), so it is proven here directly: a non-83-byte source is refused
    /// without writing the fixed PKCS#8 buffer.
    #[test]
    fn fill_fixed_pkcs8_length_guard_rejects_wrong_length() {
        let mut out = [0xCDu8; ED25519_PKCS8_LEN]; // sentinel fill
        let wrong = [0xAAu8; ED25519_PKCS8_LEN + 1]; // not an 83-byte document
                                                     // SAFETY: out is valid for ED25519_PKCS8_LEN bytes; wrong is a valid slice.
        let ok = unsafe { fill_fixed::<ED25519_PKCS8_LEN>(out.as_mut_ptr(), &wrong) };
        assert_eq!(ok, 0, "wrong-length PKCS#8 source must fail closed");
        assert_eq!(
            out, [0xCDu8; ED25519_PKCS8_LEN],
            "PKCS#8 output buffer must be untouched on a wrong-length source"
        );
    }

    /// An exact-length source is copied in full and reports success — the seam
    /// must not become a no-op that rejects everything.
    #[test]
    fn fill_fixed_copies_exact_length_source() {
        let mut out = [0u8; ED25519_PUBLIC_LEN];
        let src = [0x5Au8; ED25519_PUBLIC_LEN];
        // SAFETY: out is valid for ED25519_PUBLIC_LEN bytes; src is a valid slice.
        let ok = unsafe { fill_fixed::<ED25519_PUBLIC_LEN>(out.as_mut_ptr(), &src) };
        assert_eq!(ok, 1, "exact-length source must be copied");
        assert_eq!(out, src, "all N bytes must be written on a length match");
    }

    // ── BytesTriple-ABI wrapper tests ─────────────────────────────────────────
    //
    // These tests exercise the migrated `_hew` wrappers directly at the
    // BytesTriple ABI level, confirming that the new calling convention is
    // correct before the Hew-level sign_test goes green (which requires L33
    // bytes-literal support).

    /// Helper: allocate a `BytesTriple` from a slice using the runtime allocator.
    fn make_bytes_triple(data: &[u8]) -> BytesTriple {
        bytes_from_slice(data)
    }

    /// Helper: free a `BytesTriple` allocated by the runtime.
    ///
    /// # Safety
    ///
    /// `triple.ptr` must have been allocated by `hew_bytes_from_static` or
    /// another `alloc_buf`-based allocator.
    unsafe fn free_bytes_triple(triple: &BytesTriple) {
        if !triple.ptr.is_null() {
            // SAFETY: caller guarantees ptr was allocated by the runtime allocator.
            unsafe { hew_runtime::bytes::hew_bytes_drop(triple.ptr) };
        }
    }

    /// Helper: extract bytes from a `BytesTriple` into a `Vec`.
    fn triple_to_vec(triple: &BytesTriple) -> Vec<u8> {
        if triple.ptr.is_null() || triple.len == 0 {
            return Vec::new();
        }
        // SAFETY: triple.ptr + offset is valid for len bytes per BytesTriple invariant.
        unsafe {
            std::slice::from_raw_parts(triple.ptr.add(triple.offset as usize), triple.len as usize)
        }
        .to_vec()
    }

    /// `generate_pkcs8_hew` returns an 83-byte PKCS#8 document.
    #[test]
    fn generate_pkcs8_hew_returns_83_bytes() {
        // SAFETY: no inputs; all memory managed by runtime.
        let triple = unsafe { hew_ed25519_generate_pkcs8_hew() };
        assert_eq!(
            triple.len,
            u32::try_from(ED25519_PKCS8_LEN).unwrap(),
            "generate_pkcs8_hew must return {ED25519_PKCS8_LEN} bytes"
        );
        assert!(
            !triple.ptr.is_null(),
            "generate_pkcs8_hew ptr must be non-null"
        );
        // SAFETY: triple was allocated by generate_pkcs8_hew.
        unsafe { free_bytes_triple(&triple) };
    }

    /// `generate_pkcs8_hew_raw` writes an 83-byte PKCS#8 document via out-pointer.
    #[test]
    fn generate_pkcs8_hew_raw_matches_by_value() {
        let mut out = std::mem::MaybeUninit::<BytesTriple>::uninit();
        // SAFETY: out is a valid writable BytesTriple slot.
        unsafe { hew_ed25519_generate_pkcs8_hew_raw(out.as_mut_ptr()) };
        // SAFETY: generate_pkcs8_hew_raw always initialises out.
        let triple = unsafe { out.assume_init() };
        assert_eq!(
            triple.len,
            u32::try_from(ED25519_PKCS8_LEN).unwrap(),
            "_raw variant must also return {ED25519_PKCS8_LEN} bytes"
        );
        // SAFETY: triple was allocated by generate_pkcs8_hew_raw.
        unsafe { free_bytes_triple(&triple) };
    }

    /// `public_key_from_pkcs8_hew` extracts a 32-byte public key.
    #[test]
    fn public_key_from_pkcs8_hew_returns_32_bytes() {
        let pkcs8_triple = unsafe { hew_ed25519_generate_pkcs8_hew() };
        // SAFETY: pkcs8_triple is a valid BytesTriple.
        let pub_triple = unsafe { hew_ed25519_public_key_from_pkcs8_hew(&raw const pkcs8_triple) };
        assert_eq!(
            pub_triple.len,
            u32::try_from(ED25519_PUBLIC_LEN).unwrap(),
            "public_key_from_pkcs8_hew must return {ED25519_PUBLIC_LEN} bytes"
        );
        assert!(!pub_triple.ptr.is_null(), "public key ptr must be non-null");
        // SAFETY: triples were allocated by the _hew functions.
        unsafe { free_bytes_triple(&pkcs8_triple) };
        unsafe { free_bytes_triple(&pub_triple) };
    }

    /// `sign_hew` returns a 64-byte signature.
    #[test]
    fn sign_hew_returns_64_bytes() {
        let pkcs8_triple = unsafe { hew_ed25519_generate_pkcs8_hew() };
        let msg_triple = make_bytes_triple(b"test message");
        // SAFETY: both triples are valid BytesTriples.
        let sig_triple =
            unsafe { hew_ed25519_sign_hew(&raw const msg_triple, &raw const pkcs8_triple) };
        assert_eq!(
            sig_triple.len,
            u32::try_from(ED25519_SIG_LEN).unwrap(),
            "sign_hew must return {ED25519_SIG_LEN} bytes"
        );
        assert!(!sig_triple.ptr.is_null(), "signature ptr must be non-null");
        // SAFETY: triples were allocated by the _hew functions or make_bytes_triple.
        unsafe { free_bytes_triple(&pkcs8_triple) };
        unsafe { free_bytes_triple(&msg_triple) };
        unsafe { free_bytes_triple(&sig_triple) };
    }

    /// `sign_hew` + `verify_hew` round-trip via `BytesTriple` ABI.
    #[test]
    fn sign_verify_hew_roundtrip() {
        let pkcs8_triple = unsafe { hew_ed25519_generate_pkcs8_hew() };
        let pub_triple = unsafe { hew_ed25519_public_key_from_pkcs8_hew(&raw const pkcs8_triple) };
        let msg_triple = make_bytes_triple(b"hew sign roundtrip");
        let sig_triple =
            unsafe { hew_ed25519_sign_hew(&raw const msg_triple, &raw const pkcs8_triple) };

        // verify with correct key and message
        let verified = unsafe {
            hew_ed25519_verify_hew(
                &raw const msg_triple,
                &raw const sig_triple,
                &raw const pub_triple,
            )
        };
        assert_eq!(verified, 1, "signature must verify");

        // tamper with the message — verification must fail
        let tampered = make_bytes_triple(b"hew sign roundtrip!");
        let rejected = unsafe {
            hew_ed25519_verify_hew(
                &raw const tampered,
                &raw const sig_triple,
                &raw const pub_triple,
            )
        };
        assert_eq!(rejected, 0, "tampered message must not verify");

        // SAFETY: all triples allocated by _hew / make_bytes_triple.
        unsafe { free_bytes_triple(&pkcs8_triple) };
        unsafe { free_bytes_triple(&pub_triple) };
        unsafe { free_bytes_triple(&msg_triple) };
        unsafe { free_bytes_triple(&sig_triple) };
        unsafe { free_bytes_triple(&tampered) };
    }

    /// `verify_hew` returns 0 for null `public_key`.
    #[test]
    fn verify_hew_null_public_key_returns_zero() {
        let msg_triple = make_bytes_triple(b"x");
        let sig_triple = make_bytes_triple(&[0u8; ED25519_SIG_LEN]);
        // SAFETY: msg_triple and sig_triple are valid; public_key is intentionally null.
        let result = unsafe {
            hew_ed25519_verify_hew(
                &raw const msg_triple,
                &raw const sig_triple,
                std::ptr::null(),
            )
        };
        assert_eq!(result, 0, "null public_key must return 0");
        unsafe { free_bytes_triple(&msg_triple) };
        unsafe { free_bytes_triple(&sig_triple) };
    }

    /// `verify_hew` returns 0 for null signature.
    #[test]
    fn verify_hew_null_signature_returns_zero() {
        let (_, public) = gen_pair();
        let pub_triple = make_bytes_triple(&public);
        let msg_triple = make_bytes_triple(b"x");
        // SAFETY: pub_triple and msg_triple are valid; signature is intentionally null.
        let result = unsafe {
            hew_ed25519_verify_hew(
                &raw const msg_triple,
                std::ptr::null(),
                &raw const pub_triple,
            )
        };
        assert_eq!(result, 0, "null signature must return 0");
        unsafe { free_bytes_triple(&pub_triple) };
        unsafe { free_bytes_triple(&msg_triple) };
    }

    /// `sign_hew_raw` out-pointer variant writes the same 64-byte signature.
    #[test]
    fn sign_hew_raw_matches_by_value() {
        let pkcs8_triple = unsafe { hew_ed25519_generate_pkcs8_hew() };
        let msg_triple = make_bytes_triple(b"raw variant test");

        let by_value =
            unsafe { hew_ed25519_sign_hew(&raw const msg_triple, &raw const pkcs8_triple) };

        let mut out = std::mem::MaybeUninit::<BytesTriple>::uninit();
        unsafe {
            hew_ed25519_sign_hew_raw(
                &raw const msg_triple,
                &raw const pkcs8_triple,
                out.as_mut_ptr(),
            );
        };
        let via_raw = unsafe { out.assume_init() };

        let sig_by_value = triple_to_vec(&by_value);
        let sig_via_raw = triple_to_vec(&via_raw);
        assert_eq!(
            sig_by_value.len(),
            ED25519_SIG_LEN,
            "by-value sig must be 64 bytes"
        );
        assert_eq!(
            sig_by_value, sig_via_raw,
            "_raw must produce identical signature"
        );

        unsafe { free_bytes_triple(&pkcs8_triple) };
        unsafe { free_bytes_triple(&msg_triple) };
        unsafe { free_bytes_triple(&by_value) };
        unsafe { free_bytes_triple(&via_raw) };
    }
}
