//! Build-script half of the identity scheme: hashing the source input set.
//!
//! Gated behind the `scan` feature so that only build-dependency copies of this
//! crate pull in `sha2`. The driver depends on the crate without the feature
//! and gets the format constants alone.

use std::fmt;
use std::fmt::Write as _;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

use sha2::{Digest, Sha256};

use crate::{INPUT_CRATES, INPUT_FILE_EXTENSIONS, INPUT_FILE_NAMES, STAMP_LEN, STAMP_SYMBOL};

/// Domain separator mixed into the digest so the scheme can be revised without
/// a previously-stamped archive ever colliding with a new-scheme driver.
const DOMAIN: &[u8] = b"hew-build-identity-v1\n";

/// A computed build identity plus the exact inputs it was computed from.
#[derive(Debug, Clone)]
pub struct Identity {
    digest: String,
    files: Vec<PathBuf>,
    dirs: Vec<PathBuf>,
}

impl Identity {
    /// Lower-case hex SHA-256 digest of the runtime + stdlib source set.
    #[must_use]
    pub fn digest(&self) -> &str {
        &self.digest
    }

    /// Source files that contributed to [`Identity::digest`].
    #[must_use]
    pub fn files(&self) -> &[PathBuf] {
        &self.files
    }

    /// Prints the `cargo:rerun-if-changed` directives that keep the identity live.
    ///
    /// Both the files and the directories that contain them are declared: file
    /// entries catch edits, directory entries catch additions and removals
    /// (which change a directory's mtime but no tracked file's).
    pub fn emit_cargo_rerun_directives(&self) {
        for dir in &self.dirs {
            println!("cargo:rerun-if-changed={}", dir.display());
        }
        for file in &self.files {
            println!("cargo:rerun-if-changed={}", file.display());
        }
    }

    /// Renders the Rust source for the `#[no_mangle]` static that stamps the
    /// identity into `libhew.a` / `hew.lib`.
    ///
    /// The emitted item uses Rust 2024 `#[unsafe(no_mangle)]` spelling because
    /// its only consumer, `hew-lib`, is a 2024-edition crate.
    #[must_use]
    pub fn stamp_static_source(&self) -> String {
        let payload = format!("{}{}", crate::STAMP_PREFIX, self.digest);
        debug_assert_eq!(payload.len(), STAMP_LEN);
        format!(
            "/// Build identity of the runtime + stdlib sources this archive was built from.\n\
             ///\n\
             /// The compiler driver carries the same digest and refuses to link an\n\
             /// archive whose stamp disagrees, so a fresh driver can never silently\n\
             /// pair with a stale `libhew.a`. Generated by `build.rs`; do not edit.\n\
             #[used]\n\
             #[unsafe(no_mangle)]\n\
             pub static {STAMP_SYMBOL}: [u8; {len}] = *b\"{payload}\\0\";\n",
            len = STAMP_LEN + 1,
        )
    }
}

/// Failure modes of [`compute`].
#[derive(Debug)]
pub enum Error {
    /// A required input directory is missing from the workspace.
    MissingInputCrate(PathBuf),
    /// The scan found no source files at all — refuse rather than hash nothing.
    NoInputs,
    /// A filesystem error while walking or reading the input set.
    Io(PathBuf, io::Error),
}

impl fmt::Display for Error {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::MissingInputCrate(path) => write!(
                f,
                "build identity input crate not found: {} (expected a full Hew \
                 workspace checkout containing {})",
                path.display(),
                INPUT_CRATES.join(", ")
            ),
            Self::NoInputs => write!(
                f,
                "build identity scan matched no source files under {}",
                INPUT_CRATES.join(", ")
            ),
            Self::Io(path, err) => {
                write!(f, "build identity scan failed on {}: {err}", path.display())
            }
        }
    }
}

impl std::error::Error for Error {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::Io(_, err) => Some(err),
            Self::MissingInputCrate(_) | Self::NoInputs => None,
        }
    }
}

/// Computes the build identity of the runtime + stdlib sources under `workspace_root`.
///
/// The digest covers, for every input file in a stable order: its
/// workspace-relative path (normalised to `/` separators so the ordering does
/// not depend on the host), its length, and its bytes. Content changes,
/// renames, additions and deletions all move the digest; bumping the package
/// version alone does not.
///
/// # Errors
///
/// Returns [`Error::MissingInputCrate`] when an input crate directory is
/// absent, [`Error::NoInputs`] when the scan matches nothing, and
/// [`Error::Io`] when a directory cannot be walked or a file cannot be read.
/// There is no "unknown identity" success value: an identity that cannot be
/// computed must stop the build rather than produce an archive nothing can
/// validate.
pub fn compute(workspace_root: &Path) -> Result<Identity, Error> {
    let mut files: Vec<(String, PathBuf)> = Vec::new();
    let mut dirs: Vec<PathBuf> = Vec::new();

    let mut crates: Vec<&str> = INPUT_CRATES.to_vec();
    crates.sort_unstable();

    for crate_dir in crates {
        let root = workspace_root.join(crate_dir);
        if !root.is_dir() {
            return Err(Error::MissingInputCrate(root));
        }
        collect(&root, crate_dir, &mut files, &mut dirs)?;
    }

    if files.is_empty() {
        return Err(Error::NoInputs);
    }

    files.sort_unstable_by(|a, b| a.0.cmp(&b.0));
    dirs.sort_unstable();

    let mut hasher = Sha256::new();
    hasher.update(DOMAIN);
    for (rel, path) in &files {
        let bytes = fs::read(path).map_err(|err| Error::Io(path.clone(), err))?;
        hasher.update(rel.as_bytes());
        hasher.update([0u8]);
        hasher.update((bytes.len() as u64).to_le_bytes());
        hasher.update(&bytes);
    }

    let mut digest = String::with_capacity(crate::DIGEST_HEX_LEN);
    for byte in hasher.finalize() {
        write!(&mut digest, "{byte:02x}").expect("writing to a String cannot fail");
    }

    Ok(Identity {
        digest,
        files: files.into_iter().map(|(_, path)| path).collect(),
        dirs,
    })
}

/// Recursively collects identity inputs under `dir`, skipping Cargo `target/` trees.
fn collect(
    dir: &Path,
    rel_prefix: &str,
    files: &mut Vec<(String, PathBuf)>,
    dirs: &mut Vec<PathBuf>,
) -> Result<(), Error> {
    dirs.push(dir.to_path_buf());

    let entries = fs::read_dir(dir).map_err(|err| Error::Io(dir.to_path_buf(), err))?;
    for entry in entries {
        let entry = entry.map_err(|err| Error::Io(dir.to_path_buf(), err))?;
        let path = entry.path();
        let name = entry.file_name();
        let Some(name) = name.to_str() else { continue };

        let file_type = entry
            .file_type()
            .map_err(|err| Error::Io(path.clone(), err))?;

        if file_type.is_dir() {
            // Build outputs are derived, not inputs; hashing them would make the
            // identity depend on itself.
            if name == "target" {
                continue;
            }
            collect(&path, &format!("{rel_prefix}/{name}"), files, dirs)?;
            continue;
        }

        if !is_input_file(name) {
            continue;
        }
        files.push((format!("{rel_prefix}/{name}"), path));
    }

    Ok(())
}

fn is_input_file(name: &str) -> bool {
    if INPUT_FILE_NAMES.contains(&name) {
        return true;
    }
    Path::new(name)
        .extension()
        .and_then(|ext| ext.to_str())
        .is_some_and(|ext| INPUT_FILE_EXTENSIONS.contains(&ext))
}

/// Resolves the workspace root from a build script's `CARGO_MANIFEST_DIR`.
///
/// # Errors
///
/// Returns [`Error::MissingInputCrate`] when the manifest directory has no
/// parent, which would mean the crate is not sitting inside a workspace.
pub fn workspace_root_from_manifest_dir(manifest_dir: &Path) -> Result<PathBuf, Error> {
    manifest_dir
        .parent()
        .map(Path::to_path_buf)
        .ok_or_else(|| Error::MissingInputCrate(manifest_dir.to_path_buf()))
}

#[cfg(test)]
mod tests {
    use super::{compute, is_input_file};
    use std::fs;

    fn scratch(name: &str) -> std::path::PathBuf {
        let dir = std::env::temp_dir().join(format!("hew-build-identity-{name}"));
        let _ = fs::remove_dir_all(&dir);
        for krate in super::INPUT_CRATES {
            fs::create_dir_all(dir.join(krate)).expect("create input crate dir");
            fs::write(dir.join(krate).join("Cargo.toml"), b"[package]\n").expect("write manifest");
        }
        dir
    }

    #[test]
    fn input_file_matching_covers_the_documented_set() {
        assert!(is_input_file("lib.rs"));
        assert!(is_input_file("Cargo.toml"));
        assert!(is_input_file("build.rs"));
        assert!(!is_input_file("README.md"));
        assert!(!is_input_file("lsan.supp"));
    }

    #[test]
    fn digest_changes_when_source_content_changes() {
        let dir = scratch("content");
        let src = dir.join("hew-runtime").join("lib.rs");
        fs::write(&src, b"fn a() {}\n").expect("write source");
        let before = compute(&dir).expect("compute").digest().to_string();
        fs::write(&src, b"fn b() {}\n").expect("rewrite source");
        let after = compute(&dir).expect("compute").digest().to_string();
        assert_ne!(before, after);
        fs::remove_dir_all(&dir).expect("cleanup");
    }

    #[test]
    fn digest_is_stable_for_identical_content() {
        let dir = scratch("stable");
        fs::write(dir.join("hew-std").join("lib.rs"), b"fn a() {}\n").expect("write source");
        let first = compute(&dir).expect("compute").digest().to_string();
        let second = compute(&dir).expect("compute").digest().to_string();
        assert_eq!(first, second);
        fs::remove_dir_all(&dir).expect("cleanup");
    }

    #[test]
    fn digest_changes_when_a_source_file_is_added() {
        let dir = scratch("added");
        fs::write(dir.join("hew-lib").join("lib.rs"), b"fn a() {}\n").expect("write source");
        let before = compute(&dir).expect("compute").digest().to_string();
        fs::write(dir.join("hew-lib").join("extra.rs"), b"fn a() {}\n").expect("write source");
        let after = compute(&dir).expect("compute").digest().to_string();
        assert_ne!(before, after);
        fs::remove_dir_all(&dir).expect("cleanup");
    }

    #[test]
    fn build_outputs_do_not_feed_the_digest() {
        let dir = scratch("target-skip");
        fs::write(dir.join("hew-runtime").join("lib.rs"), b"fn a() {}\n").expect("write source");
        let before = compute(&dir).expect("compute").digest().to_string();
        let out = dir.join("hew-runtime").join("target").join("debug");
        fs::create_dir_all(&out).expect("create target dir");
        fs::write(out.join("generated.rs"), b"fn generated() {}\n").expect("write output");
        let after = compute(&dir).expect("compute").digest().to_string();
        assert_eq!(before, after);
        fs::remove_dir_all(&dir).expect("cleanup");
    }

    #[test]
    fn a_missing_input_crate_fails_closed() {
        let dir = scratch("missing");
        fs::remove_dir_all(dir.join("hew-std")).expect("remove input crate");
        assert!(compute(&dir).is_err());
        fs::remove_dir_all(&dir).expect("cleanup");
    }

    #[test]
    fn the_rendered_stamp_round_trips_through_the_reader() {
        let dir = scratch("stamp");
        fs::write(dir.join("hew-lib").join("lib.rs"), b"fn a() {}\n").expect("write source");
        let identity = compute(&dir).expect("compute");
        let source = identity.stamp_static_source();
        let start = source.find(crate::STAMP_PREFIX).expect("stamp in source");
        assert_eq!(
            crate::digest_from_stamp(&source.as_bytes()[start..]),
            Some(identity.digest())
        );
        fs::remove_dir_all(&dir).expect("cleanup");
    }
}
