//! Hew runtime: environment variables and process arguments.
//!
//! Provides access to environment variables, command-line arguments, and basic
//! process/system information for compiled Hew programs. All returned strings
//! are allocated with `libc::malloc` so callers can free them with `libc::free`.

use crate::cabi::malloc_cstring;
use crate::lifetime::PoisonSafeRw;
use std::ffi::{c_char, CStr};

/// Global lock for environment variable access synchronization.
///
/// This protects against thread-safety issues with `std::env::set_var` and
/// `std::env::remove_var`, which are unsafe in multi-threaded contexts because
/// they modify the process-global `environ` array without synchronization.
///
/// Note: External C code calling `setenv`/`getenv`/`unsetenv` bypasses this lock
/// (POSIX limitation). Hew programs should use the `hew_env_*` functions exclusively.
pub(crate) static ENV_LOCK: std::sync::LazyLock<PoisonSafeRw<()>> =
    std::sync::LazyLock::new(|| PoisonSafeRw::new(()));

/// Convert a Rust `String` to a malloc-allocated C string. Returns null on failure.
fn string_to_malloc(s: &str) -> *mut c_char {
    // SAFETY: s.as_ptr() is valid for s.len() bytes.
    unsafe { malloc_cstring(s.as_ptr(), s.len()) }
}

// ---------------------------------------------------------------------------
// Environment variables
// ---------------------------------------------------------------------------

/// Get the value of an environment variable.
///
/// Returns a `malloc`-allocated, NUL-terminated C string, or null if the
/// variable is not set. The caller must free the result with `libc::free`.
///
/// # Safety
///
/// `key` must be a valid NUL-terminated C string.
#[no_mangle]
pub unsafe extern "C" fn hew_env_get(key: *const c_char) -> *mut c_char {
    if key.is_null() {
        return std::ptr::null_mut();
    }
    // SAFETY: caller guarantees `key` is a valid NUL-terminated C string.
    let Ok(key_str) = (unsafe { CStr::from_ptr(key) }).to_str() else {
        return std::ptr::null_mut();
    };
    // SAFETY: ENV_LOCK synchronizes access to the process-global environ array.
    ENV_LOCK.read_access(|()| match std::env::var(key_str) {
        Ok(val) => string_to_malloc(&val),
        Err(_) => std::ptr::null_mut(),
    })
}

/// Set an environment variable.
///
/// # Safety
///
/// Both `key` and `val` must be valid NUL-terminated C strings.
#[no_mangle]
pub unsafe extern "C" fn hew_env_set(key: *const c_char, val: *const c_char) {
    if key.is_null() || val.is_null() {
        return;
    }
    // SAFETY: caller guarantees both pointers are valid NUL-terminated C strings.
    let Ok(key_str) = (unsafe { CStr::from_ptr(key) }).to_str() else {
        return;
    };
    // SAFETY: caller guarantees val is a valid NUL-terminated C string.
    let Ok(val_str) = (unsafe { CStr::from_ptr(val) }).to_str() else {
        return;
    };
    // SAFETY: ENV_LOCK synchronizes access to the process-global environ array;
    // set_var is safe when protected by exclusive write access.
    ENV_LOCK.access(|()| unsafe { std::env::set_var(key_str, val_str) });
}

/// Remove an environment variable.
///
/// # Safety
///
/// `key` must be a valid NUL-terminated C string.
#[no_mangle]
pub unsafe extern "C" fn hew_env_remove(key: *const c_char) {
    if key.is_null() {
        return;
    }
    // SAFETY: caller guarantees `key` is a valid NUL-terminated C string.
    let Ok(key_str) = (unsafe { CStr::from_ptr(key) }).to_str() else {
        return;
    };
    // SAFETY: ENV_LOCK synchronizes access to the process-global environ array;
    // remove_var is safe when protected by exclusive write access.
    ENV_LOCK.access(|()| unsafe { std::env::remove_var(key_str) });
}

/// Check if an environment variable exists. Returns 1 if set, 0 otherwise.
///
/// # Safety
///
/// `key` must be a valid NUL-terminated C string (or null, which returns 0).
#[no_mangle]
pub unsafe extern "C" fn hew_env_has(key: *const c_char) -> i32 {
    if key.is_null() {
        return 0;
    }
    // SAFETY: caller guarantees `key` is a valid NUL-terminated C string.
    let Ok(key_str) = (unsafe { CStr::from_ptr(key) }).to_str() else {
        return 0;
    };
    // SAFETY: ENV_LOCK synchronizes access to the process-global environ array.
    ENV_LOCK.read_access(|()| i32::from(std::env::var(key_str).is_ok()))
}

// ---------------------------------------------------------------------------
// Command-line arguments
// ---------------------------------------------------------------------------
//
// `std::env::args()` only works when the Rust runtime has been initialized
// (i.e. when `main` is the Rust-generated entry point).  In Hew, `main` is
// generated by the LLVM codegen — the Rust runtime is never started, so
// `std::env::args()` returns an empty iterator on platforms that don't have
// a fallback (FreeBSD, some BSDs).  Linux works by accident because Rust
// reads `/proc/self/cmdline`; macOS uses `_NSGetArgv()`.
//
// To be portable, we read process args via platform-specific APIs:
//   - Linux:   /proc/self/cmdline
//   - macOS:   _NSGetArgc / _NSGetArgv
//   - FreeBSD: sysctl(KERN_PROC_ARGS)
//   - Others:  fall back to std::env::args() (best-effort)

/// Read the process argv from the OS, returning a `Vec<String>`.
fn read_process_args() -> Vec<String> {
    #[cfg(target_os = "freebsd")]
    {
        freebsd_args().unwrap_or_default()
    }
    #[cfg(not(target_os = "freebsd"))]
    {
        // Linux reads /proc/self/cmdline; macOS uses _NSGetArgv — both work
        // without Rust runtime init.
        std::env::args().collect()
    }
}

/// Read process arguments via FreeBSD's `kern.proc.args` sysctl.
#[cfg(target_os = "freebsd")]
fn freebsd_args() -> Option<Vec<String>> {
    use std::mem;

    // CTL_KERN=1, KERN_PROC=14, KERN_PROC_ARGS=7
    let pid = std::process::id() as libc::c_int;
    let mut mib: [libc::c_int; 4] = [libc::CTL_KERN, libc::KERN_PROC, libc::KERN_PROC_ARGS, pid];

    // First call: get required buffer size.
    let mut len: libc::size_t = 0;
    // SAFETY: sysctl with null oldp and valid &mut len returns the buffer size.
    let rc = unsafe {
        libc::sysctl(
            mib.as_mut_ptr(),
            4,
            std::ptr::null_mut(),
            &mut len,
            std::ptr::null(),
            0,
        )
    };
    if rc != 0 || len == 0 {
        return None;
    }

    // Second call: fill buffer.
    let mut buf: Vec<u8> = vec![0u8; len];
    // SAFETY: buf is large enough and mib is valid.
    let rc = unsafe {
        libc::sysctl(
            mib.as_mut_ptr(),
            4,
            buf.as_mut_ptr().cast(),
            &mut len,
            std::ptr::null(),
            0,
        )
    };
    if rc != 0 {
        return None;
    }
    buf.truncate(len);

    // The buffer is NUL-separated C strings.  Split on NUL, skip empty trailing.
    let args: Vec<String> = buf
        .split(|&b| b == 0)
        .filter(|s| !s.is_empty())
        .map(|s| String::from_utf8_lossy(s).into_owned())
        .collect();
    Some(args)
}

/// Return the number of command-line arguments.
///
/// # Safety
///
/// No preconditions.
#[expect(
    clippy::cast_possible_truncation,
    clippy::cast_possible_wrap,
    reason = "Argument count is bounded by OS limits, always fits in i32"
)]
#[no_mangle]
pub unsafe extern "C" fn hew_args_count() -> i32 {
    read_process_args().len() as i32
}

/// Get the command-line argument at `index`.
///
/// Returns a `malloc`-allocated, NUL-terminated C string, or null if the
/// index is out of bounds. The caller must free the result with `libc::free`.
///
/// # Safety
///
/// No preconditions beyond a valid `i32`.
#[no_mangle]
pub unsafe extern "C" fn hew_args_get(index: i32) -> *mut c_char {
    if index < 0 {
        return std::ptr::null_mut();
    }
    let args = read_process_args();
    #[expect(clippy::cast_sign_loss, reason = "guarded by index >= 0")]
    let idx = index as usize;
    if idx >= args.len() {
        return std::ptr::null_mut();
    }
    string_to_malloc(&args[idx])
}

// ---------------------------------------------------------------------------
// Process / system info
// ---------------------------------------------------------------------------

/// Return the current working directory as a malloc-allocated C string.
/// Returns null on failure.
///
/// # Safety
///
/// No preconditions. The returned pointer must be freed with `libc::free`.
#[no_mangle]
pub unsafe extern "C" fn hew_cwd() -> *mut c_char {
    let Ok(cwd) = std::env::current_dir() else {
        return std::ptr::null_mut();
    };
    let Some(s) = cwd.to_str() else {
        return std::ptr::null_mut();
    };
    string_to_malloc(s)
}

/// Return the system temporary directory as a malloc-allocated C string.
///
/// Uses `std::env::temp_dir()` which respects `TMPDIR`/`TMP`/`TEMP` env vars.
/// Trailing path separators are stripped for cross-platform consistency.
///
/// # Safety
///
/// No preconditions. The returned pointer must be freed with `libc::free`.
#[no_mangle]
pub unsafe extern "C" fn hew_temp_dir() -> *mut c_char {
    // SAFETY: ENV_LOCK synchronises access to the process-global environ
    // array — std::env::temp_dir() reads TMPDIR/TMP/TEMP under the hood.
    ENV_LOCK.read_access(|()| {
        let mut tmp = std::env::temp_dir().to_string_lossy().into_owned();
        // Strip trailing separator for consistent path concatenation.
        while tmp.ends_with('/') || tmp.ends_with('\\') {
            tmp.pop();
        }
        string_to_malloc(&tmp)
    })
}

/// Return the home directory as a malloc-allocated C string.
/// Returns null if unavailable.
///
/// # Safety
///
/// No preconditions. The returned pointer must be freed with `libc::free`.
#[no_mangle]
pub unsafe extern "C" fn hew_home_dir() -> *mut c_char {
    // SAFETY: ENV_LOCK synchronizes access to the process-global environ array.
    ENV_LOCK.read_access(|()| {
        match std::env::var("HOME").or_else(|_| std::env::var("USERPROFILE")) {
            Ok(home) => string_to_malloc(&home),
            Err(_) => std::ptr::null_mut(),
        }
    })
}

/// Return the system hostname as a malloc-allocated C string.
/// Returns null on failure.
///
/// # Safety
///
/// No preconditions. The returned pointer must be freed with `libc::free`.
#[no_mangle]
pub unsafe extern "C" fn hew_hostname() -> *mut c_char {
    #[cfg(unix)]
    {
        let mut buf = [0u8; 256];
        // SAFETY: gethostname with a valid buffer and size is always safe.
        let rc = unsafe { libc::gethostname(buf.as_mut_ptr().cast::<c_char>(), buf.len()) };
        if rc != 0 {
            return std::ptr::null_mut();
        }
        // Ensure NUL-termination.
        buf[buf.len() - 1] = 0;
        // SAFETY: buf is NUL-terminated after gethostname success.
        let cstr = unsafe { CStr::from_ptr(buf.as_ptr().cast::<c_char>()) };
        let Ok(s) = cstr.to_str() else {
            return std::ptr::null_mut();
        };
        string_to_malloc(s)
    }
    #[cfg(windows)]
    {
        // Use COMPUTERNAME environment variable (always set on Windows).
        // SAFETY: ENV_LOCK synchronizes access to the process-global environ array.
        ENV_LOCK.read_access(|()| match std::env::var("COMPUTERNAME") {
            Ok(name) => string_to_malloc(&name),
            Err(_) => std::ptr::null_mut(),
        })
    }
    #[cfg(not(any(unix, windows)))]
    {
        std::ptr::null_mut()
    }
}

/// Return the current process ID.
///
/// # Safety
///
/// No preconditions.
#[no_mangle]
pub unsafe extern "C" fn hew_pid() -> i32 {
    std::process::id().cast_signed()
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::ffi::CString;

    /// Helper to read a malloc'd C string and free it.
    ///
    /// # Safety
    ///
    /// `ptr` must be a non-null, NUL-terminated, malloc-allocated C string.
    unsafe fn read_and_free(ptr: *mut c_char) -> String {
        assert!(!ptr.is_null());
        // SAFETY: ptr is a valid NUL-terminated C string per caller.
        let s = unsafe { CStr::from_ptr(ptr) }.to_str().unwrap().to_owned();
        // SAFETY: ptr was allocated with libc::malloc.
        unsafe { libc::free(ptr.cast()) };
        s
    }

    #[test]
    fn test_env_set_get_has_roundtrip() {
        let unique_key = format!("HEW_TEST_ENV_VAR_{}", std::process::id());
        let key = CString::new(unique_key).unwrap();
        let val = CString::new("hello_hew").unwrap();

        // SAFETY: both pointers are valid NUL-terminated C strings.
        unsafe {
            // Should not exist yet.
            assert_eq!(hew_env_has(key.as_ptr()), 0);
            assert!(hew_env_get(key.as_ptr()).is_null());

            // Set and verify.
            hew_env_set(key.as_ptr(), val.as_ptr());
            assert_eq!(hew_env_has(key.as_ptr()), 1);

            let got = hew_env_get(key.as_ptr());
            let text = read_and_free(got);
            assert_eq!(text, "hello_hew");

            // Remove and verify.
            hew_env_remove(key.as_ptr());
            assert_eq!(hew_env_has(key.as_ptr()), 0);
        }
    }

    #[test]
    fn test_env_get_null_and_missing() {
        // SAFETY: null is explicitly handled.
        assert!(unsafe { hew_env_get(std::ptr::null()) }.is_null());

        let missing = CString::new("HEW_DEFINITELY_NOT_SET_XYZ_123").unwrap();
        // SAFETY: missing.as_ptr() is a valid NUL-terminated C string.
        assert!(unsafe { hew_env_get(missing.as_ptr()) }.is_null());
    }

    #[test]
    fn test_args_count() {
        // SAFETY: no preconditions.
        let count = unsafe { hew_args_count() };
        // There is always at least the program name.
        assert!(count >= 1);
    }

    #[test]
    fn test_args_get_out_of_bounds() {
        // SAFETY: no preconditions.
        assert!(unsafe { hew_args_get(-1) }.is_null());
        // SAFETY: no preconditions; out-of-bounds index returns null.
        assert!(unsafe { hew_args_get(9999) }.is_null());
    }

    #[test]
    fn test_cwd_returns_nonempty() {
        // SAFETY: no preconditions.
        let ptr = unsafe { hew_cwd() };
        // SAFETY: cwd should succeed in test environment.
        let text = unsafe { read_and_free(ptr) };
        assert!(!text.is_empty());
    }

    #[test]
    fn test_hostname_returns_nonempty() {
        // SAFETY: no preconditions.
        let ptr = unsafe { hew_hostname() };
        // SAFETY: hostname should succeed in test environment.
        let text = unsafe { read_and_free(ptr) };
        assert!(!text.is_empty());
    }

    #[test]
    fn test_pid_is_positive() {
        // SAFETY: no preconditions.
        let pid = unsafe { hew_pid() };
        assert!(pid > 0);
    }

    #[test]
    fn test_temp_dir_returns_nonempty() {
        // SAFETY: hew_temp_dir returns a malloc'd C string; no preconditions.
        let ptr = unsafe { hew_temp_dir() };
        // SAFETY: ptr is a valid malloc'd NUL-terminated C string.
        let text = unsafe { read_and_free(ptr) };
        assert!(!text.is_empty());
        // Should not end with a separator.
        assert!(!text.ends_with('/') && !text.ends_with('\\'));
    }

    #[test]
    fn test_env_concurrent_access_stress() {
        use std::sync::{Arc, Barrier};
        use std::thread;

        const NUM_WRITER_THREADS: usize = 4;
        const NUM_READER_THREADS: usize = 4;
        const ITERATIONS_PER_THREAD: usize = 100;

        // Unique test key to avoid conflicts with other tests.
        let test_key_base = format!("HEW_STRESS_TEST_{}", std::process::id());
        let key_cstring = Arc::new(CString::new(test_key_base).unwrap());

        // Barrier to synchronize all threads starting at the same time.
        let barrier = Arc::new(Barrier::new(NUM_WRITER_THREADS + NUM_READER_THREADS));

        let mut handles = Vec::new();

        // Spawn writer threads.
        for i in 0..NUM_WRITER_THREADS {
            let key = Arc::clone(&key_cstring);
            let barrier = Arc::clone(&barrier);
            let handle = thread::spawn(move || {
                barrier.wait();
                for j in 0..ITERATIONS_PER_THREAD {
                    let value = format!("writer{i}_{j}");
                    let value_cstring = CString::new(value).unwrap();
                    // SAFETY: Both pointers are valid NUL-terminated C strings.
                    unsafe {
                        hew_env_set(key.as_ptr(), value_cstring.as_ptr());
                    }
                    // Occasionally remove the variable to test write/write contention.
                    if j % 10 == 0 {
                        // SAFETY: key is a valid NUL-terminated C string.
                        unsafe {
                            hew_env_remove(key.as_ptr());
                        }
                    }
                }
            });
            handles.push(handle);
        }

        // Spawn reader threads.
        for _i in 0..NUM_READER_THREADS {
            let key = Arc::clone(&key_cstring);
            let barrier = Arc::clone(&barrier);
            let handle = thread::spawn(move || {
                barrier.wait();
                for _j in 0..ITERATIONS_PER_THREAD {
                    // SAFETY: key is a valid NUL-terminated C string.
                    let has_var = unsafe { hew_env_has(key.as_ptr()) };
                    if has_var == 1 {
                        // SAFETY: key is a valid NUL-terminated C string.
                        let ptr = unsafe { hew_env_get(key.as_ptr()) };
                        if !ptr.is_null() {
                            // SAFETY: ptr is a valid malloc'd NUL-terminated C string.
                            unsafe {
                                libc::free(ptr.cast());
                            }
                        }
                    }
                }
            });
            handles.push(handle);
        }

        // Wait for all threads to complete.
        for handle in handles {
            handle.join().expect("Thread panicked");
        }

        // Clean up: remove the test variable if it exists.
        // SAFETY: key is a valid NUL-terminated C string.
        unsafe {
            hew_env_remove(key_cstring.as_ptr());
        }

        // If we reach here without panicking, the stress test passed.
    }

    /// `hew_temp_dir` must acquire `ENV_LOCK` so it doesn't race with
    /// concurrent `hew_env_set` calls that modify TMPDIR/TMP.
    #[test]
    fn temp_dir_concurrent_with_env_set() {
        use std::sync::{Arc, Barrier};
        use std::thread;

        const THREADS: usize = 4;
        const ITERS: usize = 200;

        let key = CString::new("TMPDIR").unwrap();

        // Snapshot original TMPDIR so we can restore it.
        // SAFETY: key is a valid NUL-terminated C string.
        let orig_ptr = unsafe { hew_env_get(key.as_ptr()) };
        let orig_value: Option<CString> = if orig_ptr.is_null() {
            None
        } else {
            // SAFETY: orig_ptr is a valid malloc'd NUL-terminated C string.
            let s = unsafe { CStr::from_ptr(orig_ptr) }.to_owned();
            // SAFETY: orig_ptr was allocated with libc::malloc.
            unsafe { libc::free(orig_ptr.cast()) };
            Some(s)
        };

        let barrier = Arc::new(Barrier::new(THREADS * 2));
        let mut handles = Vec::new();

        // Writer threads toggle TMPDIR between two values.
        for i in 0..THREADS {
            let key = key.clone();
            let b = Arc::clone(&barrier);
            handles.push(thread::spawn(move || {
                b.wait();
                for j in 0..ITERS {
                    let val = if j % 2 == 0 {
                        CString::new(format!("/tmp/hew_test_{i}")).unwrap()
                    } else {
                        CString::new("/tmp").unwrap()
                    };
                    // SAFETY: both pointers are valid NUL-terminated C strings.
                    unsafe { hew_env_set(key.as_ptr(), val.as_ptr()) };
                }
            }));
        }

        // Reader threads call hew_temp_dir concurrently.
        for _ in 0..THREADS {
            let b = Arc::clone(&barrier);
            handles.push(thread::spawn(move || {
                b.wait();
                for _ in 0..ITERS {
                    // SAFETY: no preconditions for hew_temp_dir.
                    let ptr = unsafe { hew_temp_dir() };
                    assert!(!ptr.is_null());
                    // SAFETY: ptr is a valid malloc'd NUL-terminated C string.
                    unsafe { libc::free(ptr.cast()) };
                }
            }));
        }

        for h in handles {
            h.join().expect("thread panicked — possible data race");
        }

        // Restore original TMPDIR.
        match orig_value {
            // SAFETY: both key and val are valid NUL-terminated C strings.
            Some(val) => unsafe { hew_env_set(key.as_ptr(), val.as_ptr()) },
            // SAFETY: key is a valid NUL-terminated C string.
            None => unsafe { hew_env_remove(key.as_ptr()) },
        }
    }
}
