//! Minimal HTML template with embedded CSS for generated documentation.

/// Embedded CSS styles for the documentation pages.
///
/// The colour palette matches the Shiki `dark-plus` theme as configured on the
/// Hew website (`hew.sh`), with the same design-system overrides applied in the
/// website's `CodeBlock.astro` component.
const CSS: &str = r#"
:root {
    --bg: #0d1117;
    --fg: #e2e8f0;
    --code-bg: #111827;
    --border: #30363d;
    --accent: #60a5fa;
    --accent-light: #1e293b;
    --kw: #22d3ee;
    --ty: #2dd4bf;
    --fn-color: #facc15;
    --str: #4ade80;
    --num: #fb923c;
    --comment: #8b949e;
    --op: #94a3b8;
}
* { margin: 0; padding: 0; box-sizing: border-box; }
body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
    line-height: 1.6;
    color: var(--fg);
    background: var(--bg);
    max-width: 56rem;
    margin: 0 auto;
    padding: 2rem 1.5rem;
}
h1 { font-size: 2rem; margin-bottom: 0.5rem; }
h2 { font-size: 1.5rem; margin: 2rem 0 0.75rem; border-bottom: 1px solid var(--border); padding-bottom: 0.25rem; }
h3 { font-size: 1.15rem; margin: 1.25rem 0 0.5rem; }
a { color: var(--accent); text-decoration: none; }
a:hover { text-decoration: underline; }
code, pre {
    font-family: "JetBrains Mono", "Fira Code", "Cascadia Code", monospace;
    font-size: 0.9em;
}
code { background: var(--code-bg); padding: 0.1em 0.35em; border-radius: 3px; }
pre { background: var(--code-bg); padding: 1em; border-radius: 6px; overflow-x: auto; margin: 0.75rem 0; }
pre code { background: none; padding: 0; }
pre.shiki { border: 1px solid var(--border); }
pre.shiki code { counter-reset: line; display: flex; flex-direction: column; }
pre.shiki .line { display: block; }
pre.shiki .line::before {
    counter-increment: line;
    content: counter(line);
    display: inline-block;
    width: 2.5em;
    margin-right: 1em;
    text-align: right;
    color: #4b5563;
    user-select: none;
    font-size: 0.8em;
}
.sig { font-weight: 600; font-family: monospace; font-size: 1rem; background: var(--accent-light); padding: 0.5em 0.75em; border-radius: 6px; border-left: 3px solid var(--accent); margin-bottom: 0.5rem; display: block; }
.doc { margin: 0.5rem 0 1.5rem 0; }
.fields { margin: 0.5rem 0 0.75rem 1rem; }
.fields dt { font-family: monospace; font-weight: 600; }
.fields dd { margin-left: 1rem; margin-bottom: 0.25rem; color: var(--comment); }
.item { margin-bottom: 2rem; }
.module-list { list-style: none; }
.module-list li { margin: 0.5rem 0; }
nav { margin-bottom: 1.5rem; font-size: 0.95em; }
nav a + a::before { content: " · "; color: var(--comment); }
footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid var(--border); font-size: 0.85em; color: var(--comment); }
"#;

/// Wrap HTML body content in a full page with the documentation stylesheet.
#[must_use]
pub fn wrap_page(title: &str, body: &str, breadcrumb: Option<&str>) -> String {
    let nav = breadcrumb.map_or(String::new(), |bc| format!("<nav>{bc}</nav>\n"));
    format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title} — Hew Documentation</title>
<style>{CSS}</style>
</head>
<body>
{nav}{body}
<footer>Generated by <code>hew doc</code></footer>
</body>
</html>
"#
    )
}

/// Apply syntax highlighting to a code string using the hew-lexer.
///
/// Wraps known Hew tokens in coloured `<span>` elements matching the website's
/// Shiki theme.
#[must_use]
pub fn highlight_signature(sig: &str) -> String {
    super::highlight::highlight_signature(sig)
}

/// Escape HTML special characters.
#[must_use]
pub fn html_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn wrap_page_contains_title() {
        let html = wrap_page("TestMod", "<p>hello</p>", None);
        assert!(html.contains("<title>TestMod — Hew Documentation</title>"));
        assert!(html.contains("<p>hello</p>"));
    }

    #[test]
    fn html_escape_works() {
        assert_eq!(html_escape("<i32>"), "&lt;i32&gt;");
    }

    #[test]
    fn highlight_keywords() {
        let out = highlight_signature("pub fn add(a: i32)");
        assert!(out.contains("pub</span>"));
        assert!(out.contains("fn</span>"));
    }
}
