mod support;

use support::{assert_success, run_hew};

fn run_doc(args: &[&str]) -> std::process::Output {
    run_hew(args)
}

/// A syntactically valid Hew source file should exit 0.
#[test]
fn valid_file_exits_zero() {
    let dir = support::tempdir();
    let src = dir.path().join("ok.hew");
    std::fs::write(
        &src,
        "/// A simple module.\nfn greet(name: str) -> str {\n    name\n}\n",
    )
    .unwrap();
    let out_dir = dir.path().join("docs");

    let output = run_doc(&[
        "doc",
        src.to_str().unwrap(),
        "--output-dir",
        out_dir.to_str().unwrap(),
    ]);

    assert_success(&output, "expected exit 0 for valid file");
    assert!(out_dir.join("index.html").is_file(), "missing index.html");
    assert!(out_dir.join("ok.html").is_file(), "missing ok.html");
}

/// A file with parse errors must exit nonzero and emit an error message.
#[test]
fn parse_error_file_exits_nonzero() {
    let dir = support::tempdir();
    let src = dir.path().join("bad.hew");
    // Intentionally broken syntax: unclosed brace.
    std::fs::write(&src, "fn broken( {\n").unwrap();
    let out_dir = dir.path().join("docs");

    let output = run_doc(&[
        "doc",
        src.to_str().unwrap(),
        "--output-dir",
        out_dir.to_str().unwrap(),
    ]);

    assert!(
        !output.status.success(),
        "expected nonzero exit for parse-error file\nstderr: {}",
        String::from_utf8_lossy(&output.stderr),
    );
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        stderr.contains("Error:"),
        "expected 'Error:' in stderr, got: {stderr}",
    );
}

/// Passing a nonexistent file must exit nonzero.
#[test]
fn nonexistent_file_exits_nonzero() {
    let dir = support::tempdir();
    let out_dir = dir.path().join("docs");

    let output = run_doc(&[
        "doc",
        "/this/path/does/not/exist.hew",
        "--output-dir",
        out_dir.to_str().unwrap(),
    ]);

    assert!(
        !output.status.success(),
        "expected nonzero exit for nonexistent file\nstderr: {}",
        String::from_utf8_lossy(&output.stderr),
    );
}

/// File input should render an index plus a module page with the expected HTML structure.
#[test]
fn file_input_renders_expected_html_structure() {
    let dir = support::tempdir();
    let src = dir.path().join("math.hew");
    std::fs::write(
        &src,
        "//! Math utilities.\n/// Adds numbers.\npub fn add(a: i32, b: i32) -> i32 { a + b }\n",
    )
    .unwrap();
    let out_dir = dir.path().join("docs");

    let output = run_doc(&[
        "doc",
        src.to_str().unwrap(),
        "--output-dir",
        out_dir.to_str().unwrap(),
    ]);

    assert_success(&output, "expected exit 0 for valid file");

    let index = std::fs::read_to_string(out_dir.join("index.html")).unwrap();
    assert!(index.contains("math.html"), "index: {index}");
    assert!(index.contains("Math utilities."), "index: {index}");

    let module = std::fs::read_to_string(out_dir.join("math.html")).unwrap();
    assert!(module.contains("<!DOCTYPE html>"), "module: {module}");
    assert!(
        module.contains("<title>math — Hew Standard Library</title>"),
        "module: {module}"
    );
    assert!(
        module.contains("Module <code>math</code>"),
        "module: {module}"
    );
    assert!(module.contains("<h2>Functions</h2>"), "module: {module}");
    assert!(
        module.contains("Generated by <code>hew doc</code>"),
        "module: {module}"
    );
}

/// Directory input should recurse through `.hew` files and use directory-qualified module names.
#[test]
fn directory_input_recurses_and_uses_directory_module_names() {
    let dir = support::tempdir();
    let pkg_dir = dir.path().join("pkg");
    std::fs::create_dir_all(pkg_dir.join("nested")).unwrap();
    std::fs::write(
        pkg_dir.join("math.hew"),
        "//! Math utilities.\nfn add(a: i32, b: i32) -> i32 { a + b }\n",
    )
    .unwrap();
    std::fs::write(
        pkg_dir.join("nested").join("util.hew"),
        "//! Nested utilities.\nfn id(x: i32) -> i32 { x }\n",
    )
    .unwrap();
    let out_dir = dir.path().join("docs");

    let output = run_doc(&[
        "doc",
        pkg_dir.to_str().unwrap(),
        "--output-dir",
        out_dir.to_str().unwrap(),
    ]);

    assert!(
        output.status.success(),
        "expected exit 0 for directory input\nstderr: {}",
        String::from_utf8_lossy(&output.stderr),
    );
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        stderr.contains("Generated HTML documentation for 2 modules"),
        "stderr: {stderr}"
    );

    assert!(out_dir.join("index.html").is_file(), "missing index.html");
    assert!(
        out_dir.join("pkg.math.html").is_file(),
        "missing pkg.math.html"
    );
    assert!(
        out_dir.join("pkg.nested.util.html").is_file(),
        "missing pkg.nested.util.html"
    );

    let index = std::fs::read_to_string(out_dir.join("index.html")).unwrap();
    assert!(index.contains("pkg::math"), "index: {index}");
    assert!(index.contains("pkg::nested::util"), "index: {index}");
}

/// Parse warnings should be reported but still produce documentation and exit 0.
#[test]
fn parse_warnings_report_but_do_not_fail_generation() {
    let dir = support::tempdir();
    let src = dir.path().join("warn.hew");
    std::fs::write(&src, "//! Warning test.\nfn main() {\n    let x = 1;;\n}\n").unwrap();
    let out_dir = dir.path().join("docs");

    let output = run_doc(&[
        "doc",
        src.to_str().unwrap(),
        "--output-dir",
        out_dir.to_str().unwrap(),
    ]);

    assert!(
        output.status.success(),
        "expected exit 0 for parse warnings\nstderr: {}",
        String::from_utf8_lossy(&output.stderr),
    );

    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("Warning:"), "stderr: {stderr}");
    assert!(stderr.contains("unnecessary semicolon"), "stderr: {stderr}");
    assert!(
        stderr.contains("Generated HTML documentation for 1 module"),
        "stderr: {stderr}"
    );
    assert!(out_dir.join("index.html").is_file(), "missing index.html");
    assert!(out_dir.join("warn.html").is_file(), "missing warn.html");
}
