// @generated by `cargo run -p hew-capability-gen`; do not edit.
// Source: wasm-capability-manifest.toml

#[rustfmt::skip]
mod generated {
/// Stable identity of a manifest-owned WASM capability.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct WasmCapabilityId(&'static str);

impl WasmCapabilityId {
/// Return the stable kebab-case manifest identity.
#[must_use]
pub const fn as_str(self) -> &'static str { self.0 }
}

impl std::fmt::Display for WasmCapabilityId {
fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
f.write_str(self.0)
}
}

/// Manifest-owned checker disposition.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum WasmFeatureDisposition { Warn, Reject }

/// Exhaustive reject/warn feature carrier generated from the manifest.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum WasmUnsupportedFeature {
    SupervisionTrees,
    LinkMonitor,
    StructuredConcurrency,
    Tasks,
    BlockingChannelRecv,
    BlockingSemaphoreAcquire,
    Timers,
    PeriodicTimers,
    Streams,
    FilesystemStreams,
    HttpClient,
    Smtp,
    WebSocket,
    HttpServer,
    TcpNetworking,
    ProcessExecution,
    Tls,
    Quic,
    Dns,
    OsEnv,
    Distributed,
    CryptoRandom,
    CryptoEncrypt,
    CryptoSign,
}

#[allow(clippy::match_same_arms, reason = "one generated arm per manifest row keeps identity and mutation coverage explicit")]
impl WasmUnsupportedFeature {
    /// Every reject/warn variant, in manifest order.
    pub const ALL: &'static [Self] = &[
        Self::SupervisionTrees,
        Self::LinkMonitor,
        Self::StructuredConcurrency,
        Self::Tasks,
        Self::BlockingChannelRecv,
        Self::BlockingSemaphoreAcquire,
        Self::Timers,
        Self::PeriodicTimers,
        Self::Streams,
        Self::FilesystemStreams,
        Self::HttpClient,
        Self::Smtp,
        Self::WebSocket,
        Self::HttpServer,
        Self::TcpNetworking,
        Self::ProcessExecution,
        Self::Tls,
        Self::Quic,
        Self::Dns,
        Self::OsEnv,
        Self::Distributed,
        Self::CryptoRandom,
        Self::CryptoEncrypt,
        Self::CryptoSign,
    ];

    /// Stable manifest identity.
    #[must_use]
    pub const fn capability_id(self) -> WasmCapabilityId {
        match self {
            Self::SupervisionTrees => WasmCapabilityId("supervision-trees"),
            Self::LinkMonitor => WasmCapabilityId("link-monitor"),
            Self::StructuredConcurrency => WasmCapabilityId("structured-concurrency"),
            Self::Tasks => WasmCapabilityId("tasks"),
            Self::BlockingChannelRecv => WasmCapabilityId("channel-blocking-recv"),
            Self::BlockingSemaphoreAcquire => WasmCapabilityId("semaphore-blocking-acquire"),
            Self::Timers => WasmCapabilityId("timers-sleep"),
            Self::PeriodicTimers => WasmCapabilityId("timers-every"),
            Self::Streams => WasmCapabilityId("streams"),
            Self::FilesystemStreams => WasmCapabilityId("filesystem-streams"),
            Self::HttpClient => WasmCapabilityId("http-client"),
            Self::Smtp => WasmCapabilityId("smtp"),
            Self::WebSocket => WasmCapabilityId("websocket"),
            Self::HttpServer => WasmCapabilityId("http-server"),
            Self::TcpNetworking => WasmCapabilityId("tcp-networking"),
            Self::ProcessExecution => WasmCapabilityId("process-execution"),
            Self::Tls => WasmCapabilityId("tls"),
            Self::Quic => WasmCapabilityId("quic"),
            Self::Dns => WasmCapabilityId("dns"),
            Self::OsEnv => WasmCapabilityId("std-os"),
            Self::Distributed => WasmCapabilityId("distributed"),
            Self::CryptoRandom => WasmCapabilityId("crypto-random"),
            Self::CryptoEncrypt => WasmCapabilityId("crypto-encrypt"),
            Self::CryptoSign => WasmCapabilityId("crypto-sign"),
        }
    }

    /// Checker disposition supplied by the manifest.
    #[must_use]
    pub const fn disposition(self) -> WasmFeatureDisposition {
        match self {
            Self::SupervisionTrees => WasmFeatureDisposition::Reject,
            Self::LinkMonitor => WasmFeatureDisposition::Reject,
            Self::StructuredConcurrency => WasmFeatureDisposition::Reject,
            Self::Tasks => WasmFeatureDisposition::Reject,
            Self::BlockingChannelRecv => WasmFeatureDisposition::Reject,
            Self::BlockingSemaphoreAcquire => WasmFeatureDisposition::Reject,
            Self::Timers => WasmFeatureDisposition::Warn,
            Self::PeriodicTimers => WasmFeatureDisposition::Warn,
            Self::Streams => WasmFeatureDisposition::Reject,
            Self::FilesystemStreams => WasmFeatureDisposition::Reject,
            Self::HttpClient => WasmFeatureDisposition::Reject,
            Self::Smtp => WasmFeatureDisposition::Reject,
            Self::WebSocket => WasmFeatureDisposition::Reject,
            Self::HttpServer => WasmFeatureDisposition::Reject,
            Self::TcpNetworking => WasmFeatureDisposition::Reject,
            Self::ProcessExecution => WasmFeatureDisposition::Reject,
            Self::Tls => WasmFeatureDisposition::Reject,
            Self::Quic => WasmFeatureDisposition::Reject,
            Self::Dns => WasmFeatureDisposition::Reject,
            Self::OsEnv => WasmFeatureDisposition::Reject,
            Self::Distributed => WasmFeatureDisposition::Reject,
            Self::CryptoRandom => WasmFeatureDisposition::Reject,
            Self::CryptoEncrypt => WasmFeatureDisposition::Reject,
            Self::CryptoSign => WasmFeatureDisposition::Reject,
        }
    }

    /// Stable diagnostic label.
    #[must_use]
    pub const fn label(self) -> &'static str {
        match self {
            Self::SupervisionTrees => "Supervision tree operations",
            Self::LinkMonitor => "Link/monitor operations",
            Self::StructuredConcurrency => "Structured concurrency scopes",
            Self::Tasks => "Task handles spawned from scopes",
            Self::BlockingChannelRecv => "Blocking channel receive operations",
            Self::BlockingSemaphoreAcquire => "Blocking semaphore acquire operations",
            Self::Timers => "Timer operations",
            Self::PeriodicTimers => "Timer operations",
            Self::Streams => "Stream operations",
            Self::FilesystemStreams => "File-backed stream operations",
            Self::HttpClient => "std::net::http::http_client operations",
            Self::Smtp => "std::net::smtp operations",
            Self::WebSocket => "std::net::websocket operations",
            Self::HttpServer => "HTTP server operations",
            Self::TcpNetworking => "TCP networking operations",
            Self::ProcessExecution => "Process execution operations",
            Self::Tls => "std::net::tls operations",
            Self::Quic => "std::net::quic operations",
            Self::Dns => "std::net::dns resolver operations",
            Self::OsEnv => "std::os environment and path operations",
            Self::Distributed => "Distributed node and remote-actor operations",
            Self::CryptoRandom => "std::crypto::crypto.random_bytes operations",
            Self::CryptoEncrypt => "std::crypto::encrypt operations",
            Self::CryptoSign => "std::crypto::sign operations",
        }
    }

    /// Stable diagnostic reason.
    #[must_use]
    pub const fn reason(self) -> &'static str {
        match self {
            Self::SupervisionTrees => "they require OS threads for restart strategies and child supervision",
            Self::LinkMonitor => "they rely on OS threads to watch linked actors and propagate exits",
            Self::StructuredConcurrency => "the wasm32 scheduler has no cooperative task executor or non-blocking scope join",
            Self::Tasks => "task spawn is thread-based and no cooperative task executor drives forked bodies on wasm32",
            Self::BlockingChannelRecv => "Receiver<T>::recv still requires cooperative scheduler yield/resume on wasm32; use try_recv or the actor ask pattern instead",
            Self::BlockingSemaphoreAcquire => "Semaphore::acquire and Semaphore::acquire_timeout still require a blocking permit wait that has no cooperative wasm32 implementation; use try_acquire or actor coordination instead",
            Self::Timers => "timers are cooperative on wasm32: sleep parks at the message boundary, and #[every(duration)] handlers fire only when the host drives the timer queue",
            Self::PeriodicTimers => "timers are cooperative on wasm32: sleep parks at the message boundary, and #[every(duration)] handlers fire only when the host drives the timer queue",
            Self::Streams => "I/O streams require the OS threading and networking stack; the stream runtime module is not compiled for wasm32",
            Self::FilesystemStreams => "the FileReadStream runtime and stream collector are not compiled for wasm32; reject before code generation rather than leaving unresolved native symbols",
            Self::HttpClient => "the std::net::http::http_client wrappers are still native-only; no wasm32 networking bridge exists yet",
            Self::Smtp => "the std::net::smtp transport is still native-only; no wasm32 SMTP bridge exists yet",
            Self::WebSocket => "the std::net::websocket transport uses native sockets and OS threads; no wasm32 WebSocket bridge exists yet",
            Self::HttpServer => "the std::net::http server is backed by native sockets and tiny_http; no cooperative wasm32 server implementation exists yet",
            Self::TcpNetworking => "hew_tcp_listen / hew_tcp_connect require the native OS socket layer; the transport runtime module is not compiled for wasm32",
            Self::ProcessExecution => "hew_process_run / hew_process_spawn require the native OS process model; the process runtime module is not compiled for wasm32",
            Self::Tls => "the std::net::tls transport is backed by rustls over native sockets; no wasm32 TLS bridge exists yet",
            Self::Quic => "the std::net::quic transport is backed by quinn over native sockets; no wasm32 QUIC bridge exists yet",
            Self::Dns => "the std::net::dns resolver uses the native OS resolver; no wasm32 implementation exists yet",
            Self::OsEnv => "the std::os helpers rely on native POSIX APIs; the os runtime layer is not compiled for wasm32",
            Self::Distributed => "the Node:: cluster API and RemotePid messaging route through the native mesh transport (hew_node_api_* / hew_remote_pid_send), which is not compiled for wasm32; no wasm32 distributed runtime exists yet",
            Self::CryptoRandom => "the std::crypto.random_bytes secure entropy source (ring::SystemRandom) is native-only and absent from the wasm32 link set; no cryptographically secure wasm32 implementation exists yet; generating key material on wasm32 would not be secure",
            Self::CryptoEncrypt => "the std::crypto::encrypt module is backed by a native-only staticlib companion crate (std/crypto/encrypt) that is absent from the wasm32 link set; no wasm32 AES-GCM seal/open implementation exists yet",
            Self::CryptoSign => "the std::crypto::sign module is backed by a native-only staticlib companion crate (std/crypto/sign) that is absent from the wasm32 link set; no wasm32 Ed25519 implementation exists yet",
        }
    }
}

/// Typed constants for every reject/warn feature and backlog identity.
pub mod wasm_capability_ids {
    use super::WasmCapabilityId;
    pub const ACTOR_CRASH_CONTAINMENT: WasmCapabilityId = WasmCapabilityId("actor-crash-containment");
    pub const ACTOR_DRAIN: WasmCapabilityId = WasmCapabilityId("actor-drain");
    pub const ACTOR_HEAP_LIMITS: WasmCapabilityId = WasmCapabilityId("actor-heap-limits");
    pub const ALIAS_MESSAGING: WasmCapabilityId = WasmCapabilityId("alias-messaging");
    pub const BLOCKING_POOL: WasmCapabilityId = WasmCapabilityId("blocking-pool");
    pub const CHANNELS: WasmCapabilityId = WasmCapabilityId("channels");
    pub const CHANNEL_BLOCKING_RECV: WasmCapabilityId = WasmCapabilityId("channel-blocking-recv");
    pub const COMPRESSION: WasmCapabilityId = WasmCapabilityId("compression");
    pub const COOPERATIVE_YIELD: WasmCapabilityId = WasmCapabilityId("cooperative-yield");
    pub const CRYPTO_ENCRYPT: WasmCapabilityId = WasmCapabilityId("crypto-encrypt");
    pub const CRYPTO_RANDOM: WasmCapabilityId = WasmCapabilityId("crypto-random");
    pub const CRYPTO_SIGN: WasmCapabilityId = WasmCapabilityId("crypto-sign");
    pub const DIAGNOSTIC_SOURCE_MAP: WasmCapabilityId = WasmCapabilityId("diagnostic-source-map");
    pub const DISTRIBUTED: WasmCapabilityId = WasmCapabilityId("distributed");
    pub const DNS: WasmCapabilityId = WasmCapabilityId("dns");
    pub const DUPLEX: WasmCapabilityId = WasmCapabilityId("duplex");
    pub const FILESYSTEM_STREAMS: WasmCapabilityId = WasmCapabilityId("filesystem-streams");
    pub const HTTP_CLIENT: WasmCapabilityId = WasmCapabilityId("http-client");
    pub const HTTP_SERVER: WasmCapabilityId = WasmCapabilityId("http-server");
    pub const LAMBDA_ACTORS: WasmCapabilityId = WasmCapabilityId("lambda-actors");
    pub const LINK_MONITOR: WasmCapabilityId = WasmCapabilityId("link-monitor");
    pub const OS: WasmCapabilityId = WasmCapabilityId("os");
    pub const PROCESS_EXECUTION: WasmCapabilityId = WasmCapabilityId("process-execution");
    pub const PROFILER: WasmCapabilityId = WasmCapabilityId("profiler");
    pub const QUIC: WasmCapabilityId = WasmCapabilityId("quic");
    pub const RUNTIME_SUBSTRATE_CLASSIFICATION: WasmCapabilityId = WasmCapabilityId("runtime-substrate-classification");
    pub const RUNTIME_TRAPS: WasmCapabilityId = WasmCapabilityId("runtime-traps");
    pub const SCOPE: WasmCapabilityId = WasmCapabilityId("scope");
    pub const SEMAPHORE: WasmCapabilityId = WasmCapabilityId("semaphore");
    pub const SEMAPHORE_BLOCKING_ACQUIRE: WasmCapabilityId = WasmCapabilityId("semaphore-blocking-acquire");
    pub const SMTP: WasmCapabilityId = WasmCapabilityId("smtp");
    pub const STD_OS: WasmCapabilityId = WasmCapabilityId("std-os");
    pub const STREAMS: WasmCapabilityId = WasmCapabilityId("streams");
    pub const STRUCTURED_CONCURRENCY: WasmCapabilityId = WasmCapabilityId("structured-concurrency");
    pub const SUPERVISION: WasmCapabilityId = WasmCapabilityId("supervision");
    pub const SUPERVISION_TREES: WasmCapabilityId = WasmCapabilityId("supervision-trees");
    pub const SUSPENDING_RECEIVE: WasmCapabilityId = WasmCapabilityId("suspending-receive");
    pub const SUSPENDING_SELECT: WasmCapabilityId = WasmCapabilityId("suspending-select");
    pub const SUSPENSION_DEADLINE: WasmCapabilityId = WasmCapabilityId("suspension-deadline");
    pub const TASKS: WasmCapabilityId = WasmCapabilityId("tasks");
    pub const TCP_NETWORKING: WasmCapabilityId = WasmCapabilityId("tcp-networking");
    pub const TIMERS_EVERY: WasmCapabilityId = WasmCapabilityId("timers-every");
    pub const TIMERS_SLEEP: WasmCapabilityId = WasmCapabilityId("timers-sleep");
    pub const TIMER_SUSPENSION: WasmCapabilityId = WasmCapabilityId("timer-suspension");
    pub const TLS: WasmCapabilityId = WasmCapabilityId("tls");
    pub const WASI_ERRNO: WasmCapabilityId = WasmCapabilityId("wasi-errno");
    pub const WASI_SOCKETS: WasmCapabilityId = WasmCapabilityId("wasi-sockets");
    pub const WEBSOCKET: WasmCapabilityId = WasmCapabilityId("websocket");
}

/// A native-only stdlib module and its manifest feature identity.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WasmModuleRejection {
    pub module: &'static str,
    pub feature: WasmUnsupportedFeature,
}

/// A native-only stdlib function in an otherwise supported module.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WasmFunctionRejection {
    pub module: &'static str,
    pub function: &'static str,
    pub feature: WasmUnsupportedFeature,
}

/// Generated module rejection classification.
pub const NATIVE_ONLY_WASM_MODULE_REJECTIONS: &[WasmModuleRejection] = &[
    WasmModuleRejection { module: "stream", feature: WasmUnsupportedFeature::Streams },
    WasmModuleRejection { module: "http_client", feature: WasmUnsupportedFeature::HttpClient },
    WasmModuleRejection { module: "smtp", feature: WasmUnsupportedFeature::Smtp },
    WasmModuleRejection { module: "websocket", feature: WasmUnsupportedFeature::WebSocket },
    WasmModuleRejection { module: "http", feature: WasmUnsupportedFeature::HttpServer },
    WasmModuleRejection { module: "net", feature: WasmUnsupportedFeature::TcpNetworking },
    WasmModuleRejection { module: "process", feature: WasmUnsupportedFeature::ProcessExecution },
    WasmModuleRejection { module: "tls", feature: WasmUnsupportedFeature::Tls },
    WasmModuleRejection { module: "quic", feature: WasmUnsupportedFeature::Quic },
    WasmModuleRejection { module: "dns", feature: WasmUnsupportedFeature::Dns },
    WasmModuleRejection { module: "os", feature: WasmUnsupportedFeature::OsEnv },
    WasmModuleRejection { module: "encrypt", feature: WasmUnsupportedFeature::CryptoEncrypt },
    WasmModuleRejection { module: "sign", feature: WasmUnsupportedFeature::CryptoSign },
];

/// Generated exact-function rejection classification.
pub const NATIVE_ONLY_WASM_FUNCTION_REJECTIONS: &[WasmFunctionRejection] = &[
    WasmFunctionRejection { module: "std.fs", function: "try_read", feature: WasmUnsupportedFeature::FilesystemStreams },
];

/// Generated native-only module short-names for sandbox and checker consumers.
pub const NATIVE_ONLY_WASM_MODULES: &[&str] = &[
    "stream",
    "http_client",
    "smtp",
    "websocket",
    "http",
    "net",
    "process",
    "tls",
    "quic",
    "dns",
    "os",
    "encrypt",
    "sign",
];

}

pub use generated::*;
