//! Build script for hew-types.
//!
//! Generates compiler facts whose readable authority is stdlib `.hew` source.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

#[path = "src/stdlib_authority/codegen.rs"]
mod authority_codegen;

use authority_codegen::{derive_builtin_enums, derive_monitor_ref_projection, AuthoritySource};

// This parser remains physically owned by the FFI-contract producer while the
// typed table now lives at the lowest shared compiler layer. The parser
// hardening test includes the same source, so it exercises this exact producer.
include!("../hew-mir/build_support/ownership_contract_parse.rs");

fn main() {
    let manifest_dir =
        PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set"));
    let repo_root = manifest_dir
        .parent()
        .expect("hew-types should be in repo root");

    // Emit rerun-if-changed for .hew source directories so Cargo rebuilds
    // when stdlib files change (the ModuleRegistry loads them at compile time).
    println!("cargo:rerun-if-changed={}", repo_root.join("std").display());
    println!(
        "cargo:rerun-if-changed={}",
        repo_root.join("ecosystem").display()
    );

    let builtins_path = repo_root.join("std/builtins.hew");
    let failure_path = repo_root.join("std/failure.hew");
    let link_monitor_path = repo_root.join("std/link_monitor.hew");
    let ffi_contracts_path = repo_root.join("scripts/jit-symbol-classification.toml");
    for path in [&builtins_path, &failure_path, &link_monitor_path] {
        println!("cargo:rerun-if-changed={}", path.display());
    }
    println!("cargo:rerun-if-changed={}", ffi_contracts_path.display());

    let builtins = read_source("std.builtins", &builtins_path);
    let failure = read_source("std.failure", &failure_path);
    let link_monitor = read_source("std.link_monitor", &link_monitor_path);
    let enums = derive_builtin_enums(&[builtins, failure, link_monitor])
        .unwrap_or_else(|error| panic!("failed to derive builtin enum ABI facts: {error}"));
    let monitor_projection = derive_monitor_ref_projection(builtins, link_monitor)
        .unwrap_or_else(|error| panic!("failed to derive monitor prelude projection: {error}"));

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR not set"));
    fs::write(
        out_dir.join("builtin_enums.rs"),
        render_builtin_enums(&enums),
    )
    .expect("write generated builtin enum catalog");
    fs::write(out_dir.join("monitor_ref.hew"), monitor_projection)
        .expect("write generated monitor prelude projection");
    generate_ffi_ownership_table(&toml_ownership_contracts(&ffi_contracts_path), &out_dir);
}

fn toml_ownership_contracts(path: &Path) -> BTreeMap<String, ContractRow> {
    let source = fs::read_to_string(path).expect("read FFI classification TOML");
    parse_ownership_contracts(&source)
}

fn generate_ffi_ownership_table(contracts: &BTreeMap<String, ContractRow>, out_dir: &Path) {
    let mut generated = String::from(
        "// Generated by hew-types/build.rs from scripts/jit-symbol-classification.toml.\n\
         // Do not edit; edit the TOML `[[ownership.contracts]]` rows instead.\n\
         pub static FFI_OWNERSHIP_CONTRACTS: &[(&str, ExternOwnershipContract)] = &[\n",
    );
    for (symbol, row) in contracts {
        let params = row
            .params
            .iter()
            .map(|param| match param.as_str() {
                "borrow" => "ExternParamOwnership::Borrow",
                "consume" => "ExternParamOwnership::Consume",
                "retain" => "ExternParamOwnership::Retain",
                other => panic!("unmapped param ownership: {other}"),
            })
            .collect::<Vec<_>>()
            .join(", ");
        let resource_param_types = row
            .resource_param_types
            .iter()
            .map(|resource_type| format!("\"{resource_type}\""))
            .collect::<Vec<_>>()
            .join(", ");
        let resource_result_type = row
            .resource_result_type
            .as_ref()
            .map_or_else(|| "None".to_string(), |ty| format!("Some(\"{ty}\")"));
        let result = match row.result.as_str() {
            "fresh" => "ExternResultOwnership::Fresh",
            "retained" => "ExternResultOwnership::Retained",
            "borrowed" => "ExternResultOwnership::Borrowed",
            "none" => "ExternResultOwnership::None",
            other => panic!("unmapped result ownership: {other}"),
        };
        let depth = match row.discharge_depth.as_str() {
            "shallow" => "ReleaseDischargeDepth::Shallow",
            "deep" => "ReleaseDischargeDepth::Deep",
            "none" => "ReleaseDischargeDepth::None",
            other => panic!("unmapped discharge depth: {other}"),
        };
        let retention = match row.result_retention.as_str() {
            "transferred" => "ExternResultRetention::Transferred",
            "shared-refcount" => "ExternResultRetention::SharedRefcount",
            "" => "ExternResultRetention::Unspecified",
            other => panic!("unmapped result retention: {other}"),
        };
        writeln!(
            generated,
            "    (\"{symbol}\", ExternOwnershipContract {{ params: &[{params}], resource_param_types: &[{resource_param_types}], \
             resource_result_type: {resource_result_type}, result: {result}, release_symbol: \"{}\", discharge_depth: {depth}, \
             result_retention: {retention} }}),",
            row.release_symbol
        )
        .expect("write generated contract row");
    }
    generated.push_str("];\n");
    fs::write(out_dir.join("ffi_ownership_contracts.rs"), generated)
        .expect("write generated FFI ownership table");
}

fn read_source(module: &'static str, path: &Path) -> AuthoritySource<'static> {
    let path_string = path.display().to_string();
    let source = fs::read_to_string(path).unwrap_or_else(|error| {
        panic!("failed to read {}: {error}", path.display());
    });
    AuthoritySource {
        module,
        path: Box::leak(path_string.into_boxed_str()),
        source: Box::leak(source.into_boxed_str()),
    }
}

fn render_builtin_enums(enums: &[authority_codegen::DerivedBuiltinEnum]) -> String {
    let mut output =
        String::from("// @generated by hew-types/build.rs from stdlib .hew declarations.\n");
    for enum_fact in enums {
        let variants_const = format!("{}_VARIANTS", screaming_snake(enum_fact.name));
        writeln!(
            output,
            "const {variants_const}: &[BuiltinMonomorphicEnumVariant] = &["
        )
        .unwrap();
        for variant in &enum_fact.variants {
            writeln!(
                output,
                "    BuiltinMonomorphicEnumVariant {{ name: {variant:?} }},"
            )
            .unwrap();
        }
        output.push_str("];\n\n");
    }
    output.push_str("const DERIVED_MONOMORPHIC_BUILTIN_ENUMS: &[BuiltinMonomorphicEnum] = &[\n");
    for enum_fact in enums {
        let variants_const = format!("{}_VARIANTS", screaming_snake(enum_fact.name));
        writeln!(
            output,
            "    BuiltinMonomorphicEnum {{ owner: {:?}, name: {:?}, canonical_name: {:?}, variants: {variants_const}, suppress_from_sandbox_emit: {} }},",
            enum_fact.owner,
            enum_fact.name,
            enum_fact.canonical_name,
            enum_fact.suppress_from_sandbox_emit
        )
        .unwrap();
    }
    output.push_str("];\n");
    output
}

fn screaming_snake(name: &str) -> String {
    let mut output = String::new();
    for (index, ch) in name.chars().enumerate() {
        if index > 0 && ch.is_ascii_uppercase() {
            output.push('_');
        }
        output.push(ch.to_ascii_uppercase());
    }
    output
}
