// @generated by scripts/generate-observe-protocol.py; DO NOT EDIT.
use serde::{Deserialize, Serialize};

pub const OBSERVE_SCHEMA_VERSION: &str = "v1";
pub const ACTIONABLE_TRACE_EVENT_TYPES: &[&str] = &[
    "send",
    "spawn",
    "crash",
    "stop",
    "duplex_created",
    "duplex_half_split",
    "duplex_closed",
    "sink_closed",
    "stream_closed",
    "lambda_spawned",
    "lambda_released",
];

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Envelope<T> {
    pub schema_version: String,
    pub data: T,
}

fn deserialize_required_nullable<'de, D>(deserializer: D) -> Result<Option<String>, D::Error>
where
    D: serde::Deserializer<'de>,
{
    Option::<String>::deserialize(deserializer)
}

macro_rules! decimal_string_serde {
    ($module:ident, $native:ty) => {
        mod $module {
            use serde::{Deserialize, Deserializer, Serializer};
            pub fn serialize<S>(value: &$native, serializer: S) -> Result<S::Ok, S::Error>
            where
                S: Serializer,
            {
                serializer.serialize_str(&value.to_string())
            }
            pub fn deserialize<'de, D>(deserializer: D) -> Result<$native, D::Error>
            where
                D: Deserializer<'de>,
            {
                let wire = String::deserialize(deserializer)?;
                let value = wire.parse::<$native>().map_err(serde::de::Error::custom)?;
                if value.to_string() != wire {
                    return Err(serde::de::Error::custom(
                        "expected canonical decimal string",
                    ));
                }
                Ok(value)
            }
        }
    };
}
decimal_string_serde!(uint64_decimal, u64);
decimal_string_serde!(int64_decimal, i64);

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Metrics {
    #[serde(with = "uint64_decimal")]
    pub timestamp_secs: u64,
    #[serde(with = "uint64_decimal")]
    pub tasks_spawned: u64,
    #[serde(with = "uint64_decimal")]
    pub tasks_completed: u64,
    #[serde(with = "uint64_decimal")]
    pub steals: u64,
    #[serde(with = "uint64_decimal")]
    pub messages_sent: u64,
    #[serde(with = "uint64_decimal")]
    pub messages_received: u64,
    #[serde(with = "uint64_decimal")]
    pub active_workers: u64,
    #[serde(with = "uint64_decimal")]
    pub alloc_count: u64,
    #[serde(with = "uint64_decimal")]
    pub dealloc_count: u64,
    #[serde(with = "uint64_decimal")]
    pub bytes_allocated: u64,
    #[serde(with = "uint64_decimal")]
    pub bytes_freed: u64,
    #[serde(with = "uint64_decimal")]
    pub bytes_live: u64,
    #[serde(with = "uint64_decimal")]
    pub peak_bytes_live: u64,
    #[serde(with = "uint64_decimal")]
    pub tcp_bytes_read: u64,
    #[serde(with = "uint64_decimal")]
    pub tcp_bytes_written: u64,
    #[serde(with = "uint64_decimal")]
    pub tcp_accept_count: u64,
    #[serde(with = "uint64_decimal")]
    pub tcp_connect_count: u64,
    #[serde(with = "uint64_decimal")]
    pub tcp_error_count: u64,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Memory {
    #[serde(with = "uint64_decimal")]
    pub alloc_count: u64,
    #[serde(with = "uint64_decimal")]
    pub dealloc_count: u64,
    #[serde(with = "uint64_decimal")]
    pub bytes_allocated: u64,
    #[serde(with = "uint64_decimal")]
    pub bytes_freed: u64,
    #[serde(with = "uint64_decimal")]
    pub bytes_live: u64,
    #[serde(with = "uint64_decimal")]
    pub peak_bytes_live: u64,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ActorInfo {
    #[serde(with = "uint64_decimal")]
    pub id: u64,
    #[serde(with = "uint64_decimal")]
    pub pid: u64,
    pub actor_type: String,
    pub state: String,
    #[serde(with = "uint64_decimal")]
    pub msgs: u64,
    #[serde(with = "uint64_decimal")]
    pub time_ns: u64,
    #[serde(with = "int64_decimal")]
    pub mbox_depth: i64,
    #[serde(with = "int64_decimal")]
    pub mbox_hwm: i64,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct HistoryEntry {
    #[serde(with = "uint64_decimal")]
    pub t: u64,
    #[serde(rename = "ts")]
    #[serde(with = "uint64_decimal")]
    pub tasks_spawned: u64,
    #[serde(rename = "tc")]
    #[serde(with = "uint64_decimal")]
    pub tasks_completed: u64,
    #[serde(rename = "st")]
    #[serde(with = "uint64_decimal")]
    pub steals: u64,
    #[serde(rename = "ms")]
    #[serde(with = "uint64_decimal")]
    pub messages_sent: u64,
    #[serde(rename = "mr")]
    #[serde(with = "uint64_decimal")]
    pub messages_received: u64,
    #[serde(rename = "aw")]
    #[serde(with = "uint64_decimal")]
    pub active_workers: u64,
    #[serde(rename = "ac")]
    #[serde(with = "uint64_decimal")]
    pub alloc_count: u64,
    #[serde(rename = "dc")]
    #[serde(with = "uint64_decimal")]
    pub dealloc_count: u64,
    #[serde(rename = "ba")]
    #[serde(with = "uint64_decimal")]
    pub bytes_allocated: u64,
    #[serde(rename = "bf")]
    #[serde(with = "uint64_decimal")]
    pub bytes_freed: u64,
    #[serde(rename = "bl")]
    #[serde(with = "uint64_decimal")]
    pub bytes_live: u64,
    #[serde(rename = "pb")]
    #[serde(with = "uint64_decimal")]
    pub peak_bytes_live: u64,
    #[serde(rename = "tbr")]
    #[serde(with = "uint64_decimal")]
    pub tcp_bytes_read: u64,
    #[serde(rename = "tbw")]
    #[serde(with = "uint64_decimal")]
    pub tcp_bytes_written: u64,
    #[serde(rename = "tac")]
    #[serde(with = "uint64_decimal")]
    pub tcp_accept_count: u64,
    #[serde(rename = "tcc")]
    #[serde(with = "uint64_decimal")]
    pub tcp_connect_count: u64,
    #[serde(rename = "tec")]
    #[serde(with = "uint64_decimal")]
    pub tcp_error_count: u64,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ClusterMember {
    pub route_slot: u16,
    pub state: String,
    #[serde(with = "uint64_decimal")]
    pub incarnation: u64,
    pub addr: String,
    #[serde(with = "uint64_decimal")]
    pub last_seen_ms: u64,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ConnectionInfo {
    pub conn_id: i32,
    pub peer_route_slot: u16,
    pub state: String,
    #[serde(with = "uint64_decimal")]
    pub last_activity_ms: u64,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct RouteEntry {
    pub node_id: String,
    pub route_slot: u16,
    pub session_incarnation: u32,
    pub conn_id: i32,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct RoutingSnapshot {
    pub local_node_id: String,
    pub local_route_slot: u16,
    pub session_incarnation: u32,
    pub routes: Vec<RouteEntry>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct TraceEvent {
    pub trace_id: String,
    #[serde(with = "uint64_decimal")]
    pub span_id: u64,
    #[serde(with = "uint64_decimal")]
    pub parent_span_id: u64,
    #[serde(with = "uint64_decimal")]
    pub actor_id: u64,
    #[serde(with = "uint64_decimal")]
    pub actor_type_id: u64,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    pub actor_type: Option<String>,
    pub event_type: String,
    pub msg_type: i32,
    #[serde(with = "uint64_decimal")]
    pub timestamp_ns: u64,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    pub handler_name: Option<String>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SupervisorRow {
    pub depth: u16,
    pub label: String,
    pub state: String,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CrashEntry {
    pub time_s: f64,
    #[serde(with = "uint64_decimal")]
    pub actor_id: u64,
    pub signal: i32,
    pub trap_kind: String,
    pub msg_type: i32,
    #[serde(with = "uint64_decimal")]
    pub fault_addr: u64,
}
