// @generated by scripts/generate-observe-protocol.py; DO NOT EDIT.
use serde::{Deserialize, Serialize};

pub const OBSERVE_SCHEMA_VERSION: &str = "v0.5";
pub const ACTIONABLE_TRACE_EVENT_TYPES: &[&str] = &[
    "send",
    "spawn",
    "crash",
    "stop",
    "duplex_created",
    "duplex_half_split",
    "duplex_closed",
    "sink_closed",
    "stream_closed",
    "lambda_spawned",
    "lambda_released",
];

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Envelope<T> {
    pub schema_version: String,
    pub data: T,
}

fn deserialize_required_nullable<'de, D>(deserializer: D) -> Result<Option<String>, D::Error>
where
    D: serde::Deserializer<'de>,
{
    Option::<String>::deserialize(deserializer)
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Metrics {
    pub timestamp_secs: u64,
    pub tasks_spawned: u64,
    pub tasks_completed: u64,
    pub steals: u64,
    pub messages_sent: u64,
    pub messages_received: u64,
    pub active_workers: u64,
    pub alloc_count: u64,
    pub dealloc_count: u64,
    pub bytes_allocated: u64,
    pub bytes_freed: u64,
    pub bytes_live: u64,
    pub peak_bytes_live: u64,
    pub tcp_bytes_read: u64,
    pub tcp_bytes_written: u64,
    pub tcp_accept_count: u64,
    pub tcp_connect_count: u64,
    pub tcp_error_count: u64,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Memory {
    pub alloc_count: u64,
    pub dealloc_count: u64,
    pub bytes_allocated: u64,
    pub bytes_freed: u64,
    pub bytes_live: u64,
    pub peak_bytes_live: u64,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ActorInfo {
    pub id: u64,
    pub pid: u64,
    pub actor_type: String,
    pub state: String,
    pub msgs: u64,
    pub time_ns: u64,
    pub mbox_depth: i64,
    pub mbox_hwm: i64,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct HistoryEntry {
    pub t: u64,
    #[serde(rename = "ts")]
    pub tasks_spawned: u64,
    #[serde(rename = "tc")]
    pub tasks_completed: u64,
    #[serde(rename = "st")]
    pub steals: u64,
    #[serde(rename = "ms")]
    pub messages_sent: u64,
    #[serde(rename = "mr")]
    pub messages_received: u64,
    #[serde(rename = "aw")]
    pub active_workers: u64,
    #[serde(rename = "ac")]
    pub alloc_count: u64,
    #[serde(rename = "dc")]
    pub dealloc_count: u64,
    #[serde(rename = "ba")]
    pub bytes_allocated: u64,
    #[serde(rename = "bf")]
    pub bytes_freed: u64,
    #[serde(rename = "bl")]
    pub bytes_live: u64,
    #[serde(rename = "pb")]
    pub peak_bytes_live: u64,
    #[serde(rename = "tbr")]
    pub tcp_bytes_read: u64,
    #[serde(rename = "tbw")]
    pub tcp_bytes_written: u64,
    #[serde(rename = "tac")]
    pub tcp_accept_count: u64,
    #[serde(rename = "tcc")]
    pub tcp_connect_count: u64,
    #[serde(rename = "tec")]
    pub tcp_error_count: u64,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ClusterMember {
    pub node_id: u16,
    pub state: String,
    pub incarnation: u64,
    pub addr: String,
    pub last_seen_ms: u64,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ConnectionInfo {
    pub conn_id: i32,
    pub peer_node_id: u16,
    pub state: String,
    pub last_activity_ms: u64,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct RouteEntry {
    pub node_id: String,
    pub route_slot: u16,
    pub session_incarnation: u32,
    pub conn_id: i32,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct RoutingSnapshot {
    pub local_node_id: String,
    pub local_route_slot: u16,
    pub session_incarnation: u32,
    pub routes: Vec<RouteEntry>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct TraceEvent {
    pub trace_id: String,
    pub span_id: u64,
    pub parent_span_id: u64,
    pub actor_id: u64,
    pub actor_type_id: u64,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    pub actor_type: Option<String>,
    pub event_type: String,
    pub msg_type: i32,
    pub timestamp_ns: u64,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    pub handler_name: Option<String>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SupervisorRow {
    pub depth: u16,
    pub label: String,
    pub state: String,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CrashEntry {
    pub time_s: f64,
    pub actor_id: u64,
    pub signal: i32,
    pub trap_kind: String,
    pub msg_type: i32,
    pub fault_addr: u64,
}
