import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const repoRoot = path.resolve(root, "..");
const fixturesRoot = path.join(root, "fixtures");
const deferred = readDeferredManifest();
const workspaceVersion = readWorkspaceVersion();
const canonicalCompilerVersion = `hew-sandbox-wasm-${workspaceVersion}`;

test("fixture bytecode provenance is compiled or explicitly deferred", () => {
  const fixtureDirs = fs
    .readdirSync(fixturesRoot, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();
  const fixtureSet = new Set(fixtureDirs);

  for (const fixture of deferred.keys()) {
    assert.ok(fixtureSet.has(fixture), `deferred fixture ${fixture} does not exist`);
  }

  for (const fixture of fixtureDirs) {
    const bytecodePath = path.join(fixturesRoot, fixture, "bytecode.json");
    if (!fs.existsSync(bytecodePath)) {
      continue;
    }

    const bytecode = readJson(bytecodePath);
    const deferredEntry = deferred.get(fixture);
    assert.equal(typeof bytecode.compiler_version, "string", `${fixture} compiler_version must be a string`);
    assert.ok(!bytecode.compiler_version.includes("m2-fixture"), `${fixture} still uses the M2 fixture marker`);
    assert.ok(!bytecode.compiler_version.includes("m4-fixture"), `${fixture} still uses the M4 fixture marker`);
    assert.ok(!bytecode.compiler_version.includes("m6-fixture"), `${fixture} still uses the M6 fixture marker`);

    if (deferredEntry) {
      assert.equal(
        bytecode.compiler_version,
        deferredEntry.compiler_version,
        `${fixture} deferred marker must match fixtures/README.md`
      );
    } else {
      assert.equal(
        bytecode.compiler_version,
        canonicalCompilerVersion,
        `${fixture} must be generated by the canonical sandbox compiler`
      );
    }
  }
});

test("sandbox fixture check fails closed on bytecode drift", () => {
  const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "hew-sandbox-fixtures-"));
  const tempFixtures = path.join(tempDir, "fixtures");
  fs.cpSync(fixturesRoot, tempFixtures, { recursive: true });

  try {
    const bytecodePath = path.join(tempFixtures, "01-hello-world", "bytecode.json");
    const bytecode = readJson(bytecodePath);
    bytecode.compiler_version = "handcrafted-edit";
    fs.writeFileSync(bytecodePath, `${JSON.stringify(bytecode, null, 2)}\n`);

    const result = spawnSync("make", ["sandbox-fixtures-check"], {
      cwd: repoRoot,
      env: { ...process.env, HEW_SANDBOX_FIXTURES_DIR: tempFixtures },
      encoding: "utf8"
    });

    assert.notEqual(result.status, 0, "sandbox-fixtures-check should fail after a bytecode hand edit");
    assert.match(result.stderr + result.stdout, /out of date|fixture error/i);
  } finally {
    fs.rmSync(tempDir, { recursive: true, force: true });
  }
});

function readDeferredManifest() {
  const readme = fs.readFileSync(path.join(fixturesRoot, "README.md"), "utf8");
  const match = readme.match(/```json sandbox-fixtures-deferred\n([\s\S]*?)\n```/);
  assert.ok(match, "fixtures/README.md must contain sandbox-fixtures-deferred JSON block");
  const parsed = JSON.parse(match[1]);
  const entries = new Map();
  for (const entry of parsed.deferred) {
    assert.equal(typeof entry.fixture, "string");
    assert.equal(typeof entry.feature, "string");
    assert.equal(typeof entry.reason, "string");
    if (entry.compiler_version !== undefined) {
      assert.match(entry.compiler_version, /^handcrafted-pending-/);
    }
    assert.ok(!entries.has(entry.fixture), `duplicate deferred fixture ${entry.fixture}`);
    entries.set(entry.fixture, entry);
  }
  return entries;
}

function readWorkspaceVersion() {
  const cargoToml = fs.readFileSync(path.join(repoRoot, "Cargo.toml"), "utf8");
  const match = cargoToml.match(/\[workspace\.package\][\s\S]*?\nversion\s*=\s*"([^"]+)"/);
  assert.ok(match, "workspace package version must be declared");
  return match[1];
}

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, "utf8"));
}
